// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const completeCommand = `-- name: CompleteCommand :one
UPDATE commands
SET status = ?, completed_at = ?, failure_code = ?
WHERE id = ? AND status IN ('requested', 'accepted')
RETURNING id, entity_id, adapter_id, runtime_id, operation, parameters_json,
          correlation_id, status, requested_at, deadline_at, accepted_at,
          completed_at, outcome_observation_id, failure_code
`

type CompleteCommandParams struct {
	Status      string
	CompletedAt sql.NullString
	FailureCode sql.NullString
	ID          string
}

func (q *Queries) CompleteCommand(ctx context.Context, arg CompleteCommandParams) (Command, error) {
	row := q.db.QueryRowContext(ctx, completeCommand,
		arg.Status,
		arg.CompletedAt,
		arg.FailureCode,
		arg.ID,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.AdapterID,
		&i.RuntimeID,
		&i.Operation,
		&i.ParametersJson,
		&i.CorrelationID,
		&i.Status,
		&i.RequestedAt,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.OutcomeObservationID,
		&i.FailureCode,
	)
	return i, err
}

const createCommand = `-- name: CreateCommand :exec
INSERT INTO commands (
    id, entity_id, adapter_id, runtime_id, operation, parameters_json,
    correlation_id, status, requested_at, deadline_at, accepted_at,
    completed_at, outcome_observation_id, failure_code
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCommandParams struct {
	ID                   string
	EntityID             string
	AdapterID            string
	RuntimeID            sql.NullString
	Operation            string
	ParametersJson       string
	CorrelationID        string
	Status               string
	RequestedAt          string
	DeadlineAt           string
	AcceptedAt           sql.NullString
	CompletedAt          sql.NullString
	OutcomeObservationID sql.NullString
	FailureCode          sql.NullString
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) error {
	_, err := q.db.ExecContext(ctx, createCommand,
		arg.ID,
		arg.EntityID,
		arg.AdapterID,
		arg.RuntimeID,
		arg.Operation,
		arg.ParametersJson,
		arg.CorrelationID,
		arg.Status,
		arg.RequestedAt,
		arg.DeadlineAt,
		arg.AcceptedAt,
		arg.CompletedAt,
		arg.OutcomeObservationID,
		arg.FailureCode,
	)
	return err
}

const getCommand = `-- name: GetCommand :one
SELECT id, entity_id, adapter_id, runtime_id, operation, parameters_json,
       correlation_id, status, requested_at, deadline_at, accepted_at,
       completed_at, outcome_observation_id, failure_code
FROM commands
WHERE id = ?
`

type GetCommandParams struct {
	ID string
}

func (q *Queries) GetCommand(ctx context.Context, arg GetCommandParams) (Command, error) {
	row := q.db.QueryRowContext(ctx, getCommand, arg.ID)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.AdapterID,
		&i.RuntimeID,
		&i.Operation,
		&i.ParametersJson,
		&i.CorrelationID,
		&i.Status,
		&i.RequestedAt,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.OutcomeObservationID,
		&i.FailureCode,
	)
	return i, err
}

const interruptActiveCommands = `-- name: InterruptActiveCommands :many
UPDATE commands
SET status = 'interrupted', completed_at = ?, failure_code = 'core_restarted'
WHERE status IN ('requested', 'accepted')
RETURNING id, entity_id, adapter_id, runtime_id, operation, parameters_json,
          correlation_id, status, requested_at, deadline_at, accepted_at,
          completed_at, outcome_observation_id, failure_code
`

type InterruptActiveCommandsParams struct {
	CompletedAt sql.NullString
}

// InterruptActiveCommands commits one interruption of every active row and
// returns each post-transition record. Repeating the call matches no active
// row and returns an empty slice.
func (q *Queries) InterruptActiveCommands(ctx context.Context, arg InterruptActiveCommandsParams) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, interruptActiveCommands, arg.CompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.AdapterID,
			&i.RuntimeID,
			&i.Operation,
			&i.ParametersJson,
			&i.CorrelationID,
			&i.Status,
			&i.RequestedAt,
			&i.DeadlineAt,
			&i.AcceptedAt,
			&i.CompletedAt,
			&i.OutcomeObservationID,
			&i.FailureCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityCommandsAfter = `-- name: ListEntityCommandsAfter :many
SELECT id, entity_id, adapter_id, runtime_id, operation, parameters_json,
       correlation_id, status, requested_at, deadline_at, accepted_at,
       completed_at, outcome_observation_id, failure_code
FROM commands
WHERE entity_id = ?
  AND (requested_at < ? OR (requested_at = ? AND id < ?))
ORDER BY requested_at DESC, id DESC
LIMIT ?
`

type ListEntityCommandsAfterParams struct {
	EntityID      string
	RequestedAt   string
	RequestedAt_2 string
	ID            string
	Limit         int64
}

func (q *Queries) ListEntityCommandsAfter(ctx context.Context, arg ListEntityCommandsAfterParams) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, listEntityCommandsAfter,
		arg.EntityID,
		arg.RequestedAt,
		arg.RequestedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.AdapterID,
			&i.RuntimeID,
			&i.Operation,
			&i.ParametersJson,
			&i.CorrelationID,
			&i.Status,
			&i.RequestedAt,
			&i.DeadlineAt,
			&i.AcceptedAt,
			&i.CompletedAt,
			&i.OutcomeObservationID,
			&i.FailureCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityCommandsFirstPage = `-- name: ListEntityCommandsFirstPage :many
SELECT id, entity_id, adapter_id, runtime_id, operation, parameters_json,
       correlation_id, status, requested_at, deadline_at, accepted_at,
       completed_at, outcome_observation_id, failure_code
FROM commands
WHERE entity_id = ?
ORDER BY requested_at DESC, id DESC
LIMIT ?
`

type ListEntityCommandsFirstPageParams struct {
	EntityID string
	Limit    int64
}

func (q *Queries) ListEntityCommandsFirstPage(ctx context.Context, arg ListEntityCommandsFirstPageParams) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, listEntityCommandsFirstPage, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.AdapterID,
			&i.RuntimeID,
			&i.Operation,
			&i.ParametersJson,
			&i.CorrelationID,
			&i.Status,
			&i.RequestedAt,
			&i.DeadlineAt,
			&i.AcceptedAt,
			&i.CompletedAt,
			&i.OutcomeObservationID,
			&i.FailureCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommandAccepted = `-- name: MarkCommandAccepted :one
UPDATE commands
SET accepted_at = COALESCE(accepted_at, ?),
    status = CASE WHEN status = 'requested' THEN 'accepted' ELSE status END
WHERE id = ? AND status IN ('requested', 'accepted', 'satisfied')
RETURNING id, entity_id, adapter_id, runtime_id, operation, parameters_json,
          correlation_id, status, requested_at, deadline_at, accepted_at,
          completed_at, outcome_observation_id, failure_code
`

type MarkCommandAcceptedParams struct {
	AcceptedAt sql.NullString
	ID         string
}

// MarkCommandAccepted commits one acceptance write and returns the committed
// row. Callers read the prior row in the same transaction to classify the
// transition: only requested -> accepted is a real transition.
func (q *Queries) MarkCommandAccepted(ctx context.Context, arg MarkCommandAcceptedParams) (Command, error) {
	row := q.db.QueryRowContext(ctx, markCommandAccepted, arg.AcceptedAt, arg.ID)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.AdapterID,
		&i.RuntimeID,
		&i.Operation,
		&i.ParametersJson,
		&i.CorrelationID,
		&i.Status,
		&i.RequestedAt,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.OutcomeObservationID,
		&i.FailureCode,
	)
	return i, err
}

const satisfyCommandFromObservation = `-- name: SatisfyCommandFromObservation :one
UPDATE commands
SET status = 'satisfied', completed_at = ?, outcome_observation_id = ?
WHERE id = ?
  AND entity_id = ?
  AND adapter_id = ?
  AND runtime_id = ?
  AND status IN ('requested', 'accepted')
RETURNING id, entity_id, adapter_id, runtime_id, operation, parameters_json,
          correlation_id, status, requested_at, deadline_at, accepted_at,
          completed_at, outcome_observation_id, failure_code
`

type SatisfyCommandFromObservationParams struct {
	CompletedAt          sql.NullString
	OutcomeObservationID sql.NullString
	ID                   string
	EntityID             string
	AdapterID            string
	RuntimeID            sql.NullString
}

func (q *Queries) SatisfyCommandFromObservation(ctx context.Context, arg SatisfyCommandFromObservationParams) (Command, error) {
	row := q.db.QueryRowContext(ctx, satisfyCommandFromObservation,
		arg.CompletedAt,
		arg.OutcomeObservationID,
		arg.ID,
		arg.EntityID,
		arg.AdapterID,
		arg.RuntimeID,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.AdapterID,
		&i.RuntimeID,
		&i.Operation,
		&i.ParametersJson,
		&i.CorrelationID,
		&i.Status,
		&i.RequestedAt,
		&i.DeadlineAt,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.OutcomeObservationID,
		&i.FailureCode,
	)
	return i, err
}
