// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_events.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const deleteDeviceEventsBefore = `-- name: DeleteDeviceEventsBefore :execrows
DELETE FROM device_events
WHERE receive_order IN (
    SELECT receive_order
    FROM device_events
    WHERE recorded_at < CAST(?1 AS TEXT)
    ORDER BY recorded_at, receive_order
    LIMIT CAST(?2 AS INTEGER)
)
`

type DeleteDeviceEventsBeforeParams struct {
	RecordedAt string
	BatchSize  int64
}

func (q *Queries) DeleteDeviceEventsBefore(ctx context.Context, arg DeleteDeviceEventsBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeviceEventsBefore, arg.RecordedAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeviceEvent = `-- name: GetDeviceEvent :one
SELECT receive_order, event_id, adapter_id, runtime_id, entity_id,
       correlation_id, name, fingerprint, disposition, rejection_code,
       emitted_at, received_at, recorded_at
FROM device_events
WHERE event_id = ?
`

type GetDeviceEventParams struct {
	EventID string
}

func (q *Queries) GetDeviceEvent(ctx context.Context, arg GetDeviceEventParams) (DeviceEvent, error) {
	row := q.db.QueryRowContext(ctx, getDeviceEvent, arg.EventID)
	var i DeviceEvent
	err := row.Scan(
		&i.ReceiveOrder,
		&i.EventID,
		&i.AdapterID,
		&i.RuntimeID,
		&i.EntityID,
		&i.CorrelationID,
		&i.Name,
		&i.Fingerprint,
		&i.Disposition,
		&i.RejectionCode,
		&i.EmittedAt,
		&i.ReceivedAt,
		&i.RecordedAt,
	)
	return i, err
}

const insertDeviceEvent = `-- name: InsertDeviceEvent :one
INSERT INTO device_events (
    event_id, adapter_id, runtime_id, entity_id, correlation_id, name,
    fingerprint, disposition, rejection_code, emitted_at, received_at,
    recorded_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING receive_order
`

type InsertDeviceEventParams struct {
	EventID       string
	AdapterID     string
	RuntimeID     string
	EntityID      string
	CorrelationID string
	Name          string
	Fingerprint   []byte
	Disposition   string
	RejectionCode sql.NullString
	EmittedAt     string
	ReceivedAt    string
	RecordedAt    string
}

func (q *Queries) InsertDeviceEvent(ctx context.Context, arg InsertDeviceEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDeviceEvent,
		arg.EventID,
		arg.AdapterID,
		arg.RuntimeID,
		arg.EntityID,
		arg.CorrelationID,
		arg.Name,
		arg.Fingerprint,
		arg.Disposition,
		arg.RejectionCode,
		arg.EmittedAt,
		arg.ReceivedAt,
		arg.RecordedAt,
	)
	var receive_order int64
	err := row.Scan(&receive_order)
	return receive_order, err
}

const listEntityDeviceEventsAfter = `-- name: ListEntityDeviceEventsAfter :many
SELECT event_id, entity_id, name, disposition, rejection_code,
       emitted_at, received_at, recorded_at, receive_order
FROM device_events
WHERE entity_id = ?
  AND receive_order < ?
ORDER BY receive_order DESC
LIMIT ?
`

type ListEntityDeviceEventsAfterParams struct {
	EntityID     string
	ReceiveOrder int64
	Limit        int64
}

type ListEntityDeviceEventsAfterRow struct {
	EventID       string
	EntityID      string
	Name          string
	Disposition   string
	RejectionCode sql.NullString
	EmittedAt     string
	ReceivedAt    string
	RecordedAt    string
	ReceiveOrder  int64
}

func (q *Queries) ListEntityDeviceEventsAfter(ctx context.Context, arg ListEntityDeviceEventsAfterParams) ([]ListEntityDeviceEventsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityDeviceEventsAfter, arg.EntityID, arg.ReceiveOrder, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityDeviceEventsAfterRow
	for rows.Next() {
		var i ListEntityDeviceEventsAfterRow
		if err := rows.Scan(
			&i.EventID,
			&i.EntityID,
			&i.Name,
			&i.Disposition,
			&i.RejectionCode,
			&i.EmittedAt,
			&i.ReceivedAt,
			&i.RecordedAt,
			&i.ReceiveOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityDeviceEventsFirstPage = `-- name: ListEntityDeviceEventsFirstPage :many
SELECT event_id, entity_id, name, disposition, rejection_code,
       emitted_at, received_at, recorded_at, receive_order
FROM device_events
WHERE entity_id = ?
ORDER BY receive_order DESC
LIMIT ?
`

type ListEntityDeviceEventsFirstPageParams struct {
	EntityID string
	Limit    int64
}

type ListEntityDeviceEventsFirstPageRow struct {
	EventID       string
	EntityID      string
	Name          string
	Disposition   string
	RejectionCode sql.NullString
	EmittedAt     string
	ReceivedAt    string
	RecordedAt    string
	ReceiveOrder  int64
}

func (q *Queries) ListEntityDeviceEventsFirstPage(ctx context.Context, arg ListEntityDeviceEventsFirstPageParams) ([]ListEntityDeviceEventsFirstPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityDeviceEventsFirstPage, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityDeviceEventsFirstPageRow
	for rows.Next() {
		var i ListEntityDeviceEventsFirstPageRow
		if err := rows.Scan(
			&i.EventID,
			&i.EntityID,
			&i.Name,
			&i.Disposition,
			&i.RejectionCode,
			&i.EmittedAt,
			&i.ReceivedAt,
			&i.RecordedAt,
			&i.ReceiveOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
