// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_facts.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const deleteDeviceFact = `-- name: DeleteDeviceFact :exec
DELETE FROM device_facts_outbox
WHERE fact_id = ?
`

type DeleteDeviceFactParams struct {
	FactID string
}

func (q *Queries) DeleteDeviceFact(ctx context.Context, arg DeleteDeviceFactParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceFact, arg.FactID)
	return err
}

const insertEntityEventDeviceFact = `-- name: InsertEntityEventDeviceFact :exec
INSERT INTO device_facts_outbox (
    fact_id, family, entity_id, variant, source_id, correlation_id, created_at,
    traceparent, tracestate, reported_at, received_at, recorded_at
) VALUES (?, 'entity-event', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEntityEventDeviceFactParams struct {
	FactID        string
	EntityID      string
	Variant       string
	SourceID      string
	CorrelationID string
	CreatedAt     string
	Traceparent   string
	Tracestate    string
	ReportedAt    sql.NullString
	ReceivedAt    sql.NullString
	RecordedAt    sql.NullString
}

func (q *Queries) InsertEntityEventDeviceFact(ctx context.Context, arg InsertEntityEventDeviceFactParams) error {
	_, err := q.db.ExecContext(ctx, insertEntityEventDeviceFact,
		arg.FactID,
		arg.EntityID,
		arg.Variant,
		arg.SourceID,
		arg.CorrelationID,
		arg.CreatedAt,
		arg.Traceparent,
		arg.Tracestate,
		arg.ReportedAt,
		arg.ReceivedAt,
		arg.RecordedAt,
	)
	return err
}

const insertObservationDeviceFact = `-- name: InsertObservationDeviceFact :exec
INSERT INTO device_facts_outbox (
    fact_id, family, entity_id, variant, source_id, correlation_id, created_at,
    traceparent, tracestate, value_json, adapter_received_at, source_updated_at,
    observed_at
) VALUES (?, 'observation', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertObservationDeviceFactParams struct {
	FactID            string
	EntityID          string
	Variant           string
	SourceID          string
	CorrelationID     string
	CreatedAt         string
	Traceparent       string
	Tracestate        string
	ValueJson         sql.NullString
	AdapterReceivedAt sql.NullString
	SourceUpdatedAt   sql.NullString
	ObservedAt        sql.NullString
}

func (q *Queries) InsertObservationDeviceFact(ctx context.Context, arg InsertObservationDeviceFactParams) error {
	_, err := q.db.ExecContext(ctx, insertObservationDeviceFact,
		arg.FactID,
		arg.EntityID,
		arg.Variant,
		arg.SourceID,
		arg.CorrelationID,
		arg.CreatedAt,
		arg.Traceparent,
		arg.Tracestate,
		arg.ValueJson,
		arg.AdapterReceivedAt,
		arg.SourceUpdatedAt,
		arg.ObservedAt,
	)
	return err
}

const listPendingDeviceFacts = `-- name: ListPendingDeviceFacts :many
SELECT enqueue_order, fact_id, family, entity_id, variant, source_id,
       correlation_id, created_at, traceparent, tracestate,
       value_json, adapter_received_at, source_updated_at, observed_at,
       reported_at, received_at, recorded_at
FROM device_facts_outbox
ORDER BY enqueue_order
LIMIT ?
`

type ListPendingDeviceFactsParams struct {
	Limit int64
}

func (q *Queries) ListPendingDeviceFacts(ctx context.Context, arg ListPendingDeviceFactsParams) ([]DeviceFactsOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeviceFacts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceFactsOutbox
	for rows.Next() {
		var i DeviceFactsOutbox
		if err := rows.Scan(
			&i.EnqueueOrder,
			&i.FactID,
			&i.Family,
			&i.EntityID,
			&i.Variant,
			&i.SourceID,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.Traceparent,
			&i.Tracestate,
			&i.ValueJson,
			&i.AdapterReceivedAt,
			&i.SourceUpdatedAt,
			&i.ObservedAt,
			&i.ReportedAt,
			&i.ReceivedAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
