// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity_events.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const deleteEntityEventsBefore = `-- name: DeleteEntityEventsBefore :execrows
DELETE FROM entity_events
WHERE receive_order IN (
    SELECT receive_order
    FROM entity_events
    WHERE recorded_at < CAST(?1 AS TEXT)
    ORDER BY recorded_at, receive_order
    LIMIT CAST(?2 AS INTEGER)
)
`

type DeleteEntityEventsBeforeParams struct {
	RecordedAt string
	BatchSize  int64
}

func (q *Queries) DeleteEntityEventsBefore(ctx context.Context, arg DeleteEntityEventsBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEntityEventsBefore, arg.RecordedAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEntityEvent = `-- name: GetEntityEvent :one
SELECT receive_order, event_id, adapter_id, runtime_id, entity_id,
       correlation_id, name, fingerprint, disposition, rejection_code,
       emitted_at, received_at, recorded_at
FROM entity_events
WHERE event_id = ?
`

type GetEntityEventParams struct {
	EventID string
}

func (q *Queries) GetEntityEvent(ctx context.Context, arg GetEntityEventParams) (EntityEvent, error) {
	row := q.db.QueryRowContext(ctx, getEntityEvent, arg.EventID)
	var i EntityEvent
	err := row.Scan(
		&i.ReceiveOrder,
		&i.EventID,
		&i.AdapterID,
		&i.RuntimeID,
		&i.EntityID,
		&i.CorrelationID,
		&i.Name,
		&i.Fingerprint,
		&i.Disposition,
		&i.RejectionCode,
		&i.EmittedAt,
		&i.ReceivedAt,
		&i.RecordedAt,
	)
	return i, err
}

const insertEntityEvent = `-- name: InsertEntityEvent :one
INSERT INTO entity_events (
    event_id, adapter_id, runtime_id, entity_id, correlation_id, name,
    fingerprint, disposition, rejection_code, emitted_at, received_at,
    recorded_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING receive_order
`

type InsertEntityEventParams struct {
	EventID       string
	AdapterID     string
	RuntimeID     string
	EntityID      string
	CorrelationID string
	Name          string
	Fingerprint   []byte
	Disposition   string
	RejectionCode sql.NullString
	EmittedAt     string
	ReceivedAt    string
	RecordedAt    string
}

func (q *Queries) InsertEntityEvent(ctx context.Context, arg InsertEntityEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEntityEvent,
		arg.EventID,
		arg.AdapterID,
		arg.RuntimeID,
		arg.EntityID,
		arg.CorrelationID,
		arg.Name,
		arg.Fingerprint,
		arg.Disposition,
		arg.RejectionCode,
		arg.EmittedAt,
		arg.ReceivedAt,
		arg.RecordedAt,
	)
	var receive_order int64
	err := row.Scan(&receive_order)
	return receive_order, err
}

const listEntityEventsAfter = `-- name: ListEntityEventsAfter :many
SELECT event_id, entity_id, name, disposition, rejection_code,
       emitted_at, received_at, recorded_at, receive_order
FROM entity_events
WHERE entity_id = ?
  AND receive_order < ?
ORDER BY receive_order DESC
LIMIT ?
`

type ListEntityEventsAfterParams struct {
	EntityID     string
	ReceiveOrder int64
	Limit        int64
}

type ListEntityEventsAfterRow struct {
	EventID       string
	EntityID      string
	Name          string
	Disposition   string
	RejectionCode sql.NullString
	EmittedAt     string
	ReceivedAt    string
	RecordedAt    string
	ReceiveOrder  int64
}

func (q *Queries) ListEntityEventsAfter(ctx context.Context, arg ListEntityEventsAfterParams) ([]ListEntityEventsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityEventsAfter, arg.EntityID, arg.ReceiveOrder, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityEventsAfterRow
	for rows.Next() {
		var i ListEntityEventsAfterRow
		if err := rows.Scan(
			&i.EventID,
			&i.EntityID,
			&i.Name,
			&i.Disposition,
			&i.RejectionCode,
			&i.EmittedAt,
			&i.ReceivedAt,
			&i.RecordedAt,
			&i.ReceiveOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityEventsFirstPage = `-- name: ListEntityEventsFirstPage :many
SELECT event_id, entity_id, name, disposition, rejection_code,
       emitted_at, received_at, recorded_at, receive_order
FROM entity_events
WHERE entity_id = ?
ORDER BY receive_order DESC
LIMIT ?
`

type ListEntityEventsFirstPageParams struct {
	EntityID string
	Limit    int64
}

type ListEntityEventsFirstPageRow struct {
	EventID       string
	EntityID      string
	Name          string
	Disposition   string
	RejectionCode sql.NullString
	EmittedAt     string
	ReceivedAt    string
	RecordedAt    string
	ReceiveOrder  int64
}

func (q *Queries) ListEntityEventsFirstPage(ctx context.Context, arg ListEntityEventsFirstPageParams) ([]ListEntityEventsFirstPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityEventsFirstPage, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityEventsFirstPageRow
	for rows.Next() {
		var i ListEntityEventsFirstPageRow
		if err := rows.Scan(
			&i.EventID,
			&i.EntityID,
			&i.Name,
			&i.Disposition,
			&i.RejectionCode,
			&i.EmittedAt,
			&i.ReceivedAt,
			&i.RecordedAt,
			&i.ReceiveOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
