// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const archiveAdapter = `-- name: ArchiveAdapter :exec
UPDATE adapter_instances
SET archived_at = ?, active_runtime_id = NULL, health_runtime_id = NULL,
    health_status = NULL, health_reason_code = NULL,
    health_since = NULL, health_evidence_at = NULL,
    external_system_status = NULL, external_system_reason_code = NULL,
    external_system_source_observed_at = NULL,
    external_system_evidence_at = NULL
WHERE adapter_id = ?
`

type ArchiveAdapterParams struct {
	ArchivedAt sql.NullString
	AdapterID  string
}

func (q *Queries) ArchiveAdapter(ctx context.Context, arg ArchiveAdapterParams) error {
	_, err := q.db.ExecContext(ctx, archiveAdapter, arg.ArchivedAt, arg.AdapterID)
	return err
}

const countAdapterBindings = `-- name: CountAdapterBindings :one
SELECT count(*)
FROM adapter_bindings
WHERE adapter_id = ?
`

type CountAdapterBindingsParams struct {
	AdapterID string
}

func (q *Queries) CountAdapterBindings(ctx context.Context, arg CountAdapterBindingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdapterBindings, arg.AdapterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdapterInstance = `-- name: CreateAdapterInstance :exec
INSERT INTO adapter_instances (
    adapter_id, health_status, health_reason_code, health_since, health_evidence_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateAdapterInstanceParams struct {
	AdapterID        string
	HealthStatus     sql.NullString
	HealthReasonCode sql.NullString
	HealthSince      sql.NullString
	HealthEvidenceAt sql.NullString
}

func (q *Queries) CreateAdapterInstance(ctx context.Context, arg CreateAdapterInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createAdapterInstance,
		arg.AdapterID,
		arg.HealthStatus,
		arg.HealthReasonCode,
		arg.HealthSince,
		arg.HealthEvidenceAt,
	)
	return err
}

const deleteAdapterEntityAvailability = `-- name: DeleteAdapterEntityAvailability :exec
DELETE FROM entity_availability_current
WHERE adapter_id = ?
`

type DeleteAdapterEntityAvailabilityParams struct {
	AdapterID string
}

func (q *Queries) DeleteAdapterEntityAvailability(ctx context.Context, arg DeleteAdapterEntityAvailabilityParams) error {
	_, err := q.db.ExecContext(ctx, deleteAdapterEntityAvailability, arg.AdapterID)
	return err
}

const endRuntime = `-- name: EndRuntime :execrows
UPDATE adapter_runtimes
SET ended_at = ?, end_reason = ?
WHERE runtime_id = ? AND adapter_id = ? AND ended_at IS NULL
`

type EndRuntimeParams struct {
	EndedAt   sql.NullString
	EndReason sql.NullString
	RuntimeID string
	AdapterID string
}

func (q *Queries) EndRuntime(ctx context.Context, arg EndRuntimeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endRuntime,
		arg.EndedAt,
		arg.EndReason,
		arg.RuntimeID,
		arg.AdapterID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAdapterInstance = `-- name: GetAdapterInstance :one
SELECT adapter_id, archived_at, active_runtime_id, health_runtime_id,
       health_status, health_reason_code, health_since, health_evidence_at,
       external_system_status, external_system_reason_code,
       external_system_source_observed_at, external_system_evidence_at
FROM adapter_instances
WHERE adapter_id = ?
`

type GetAdapterInstanceParams struct {
	AdapterID string
}

func (q *Queries) GetAdapterInstance(ctx context.Context, arg GetAdapterInstanceParams) (AdapterInstance, error) {
	row := q.db.QueryRowContext(ctx, getAdapterInstance, arg.AdapterID)
	var i AdapterInstance
	err := row.Scan(
		&i.AdapterID,
		&i.ArchivedAt,
		&i.ActiveRuntimeID,
		&i.HealthRuntimeID,
		&i.HealthStatus,
		&i.HealthReasonCode,
		&i.HealthSince,
		&i.HealthEvidenceAt,
		&i.ExternalSystemStatus,
		&i.ExternalSystemReasonCode,
		&i.ExternalSystemSourceObservedAt,
		&i.ExternalSystemEvidenceAt,
	)
	return i, err
}

const getAdapterView = `-- name: GetAdapterView :one
SELECT
    ai.adapter_id,
    ai.archived_at,
    ai.health_status,
    ai.health_reason_code,
    ai.health_since,
    ai.health_evidence_at,
    ai.external_system_status,
    ai.external_system_reason_code,
    ai.external_system_source_observed_at,
    ai.external_system_evidence_at,
    ar.runtime_id,
    ar.software_name,
    ar.software_version,
    ar.claimed_at,
    ar.last_heartbeat_at,
    ar.lease_expires_at,
    ar.ended_at
FROM adapter_instances AS ai
LEFT JOIN adapter_runtimes AS ar ON ar.runtime_id = ai.health_runtime_id
WHERE ai.adapter_id = ?
`

type GetAdapterViewParams struct {
	AdapterID string
}

type GetAdapterViewRow struct {
	AdapterID                      string
	ArchivedAt                     sql.NullString
	HealthStatus                   sql.NullString
	HealthReasonCode               sql.NullString
	HealthSince                    sql.NullString
	HealthEvidenceAt               sql.NullString
	ExternalSystemStatus           sql.NullString
	ExternalSystemReasonCode       sql.NullString
	ExternalSystemSourceObservedAt sql.NullString
	ExternalSystemEvidenceAt       sql.NullString
	RuntimeID                      sql.NullString
	SoftwareName                   sql.NullString
	SoftwareVersion                sql.NullString
	ClaimedAt                      sql.NullString
	LastHeartbeatAt                sql.NullString
	LeaseExpiresAt                 sql.NullString
	EndedAt                        sql.NullString
}

func (q *Queries) GetAdapterView(ctx context.Context, arg GetAdapterViewParams) (GetAdapterViewRow, error) {
	row := q.db.QueryRowContext(ctx, getAdapterView, arg.AdapterID)
	var i GetAdapterViewRow
	err := row.Scan(
		&i.AdapterID,
		&i.ArchivedAt,
		&i.HealthStatus,
		&i.HealthReasonCode,
		&i.HealthSince,
		&i.HealthEvidenceAt,
		&i.ExternalSystemStatus,
		&i.ExternalSystemReasonCode,
		&i.ExternalSystemSourceObservedAt,
		&i.ExternalSystemEvidenceAt,
		&i.RuntimeID,
		&i.SoftwareName,
		&i.SoftwareVersion,
		&i.ClaimedAt,
		&i.LastHeartbeatAt,
		&i.LeaseExpiresAt,
		&i.EndedAt,
	)
	return i, err
}

const getEntityAvailabilityCurrent = `-- name: GetEntityAvailabilityCurrent :one
SELECT entity_id, adapter_id, runtime_id, status, reason_code,
       source_observed_at, evidence_at, current_since,
       latest_transition_receive_order
FROM entity_availability_current
WHERE entity_id = ?
`

type GetEntityAvailabilityCurrentParams struct {
	EntityID string
}

func (q *Queries) GetEntityAvailabilityCurrent(ctx context.Context, arg GetEntityAvailabilityCurrentParams) (EntityAvailabilityCurrent, error) {
	row := q.db.QueryRowContext(ctx, getEntityAvailabilityCurrent, arg.EntityID)
	var i EntityAvailabilityCurrent
	err := row.Scan(
		&i.EntityID,
		&i.AdapterID,
		&i.RuntimeID,
		&i.Status,
		&i.ReasonCode,
		&i.SourceObservedAt,
		&i.EvidenceAt,
		&i.CurrentSince,
		&i.LatestTransitionReceiveOrder,
	)
	return i, err
}

const getEntityOwner = `-- name: GetEntityOwner :one
SELECT adapter_id
FROM adapter_entity_mappings
WHERE entity_id = ?
`

type GetEntityOwnerParams struct {
	EntityID string
}

func (q *Queries) GetEntityOwner(ctx context.Context, arg GetEntityOwnerParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getEntityOwner, arg.EntityID)
	var adapter_id string
	err := row.Scan(&adapter_id)
	return adapter_id, err
}

const getLatestRuntimeForAdapter = `-- name: GetLatestRuntimeForAdapter :one
SELECT runtime_id, claim_id, adapter_id, software_name, software_version,
       claimed_at, last_heartbeat_at, lease_expires_at, ended_at, end_reason
FROM adapter_runtimes
WHERE adapter_id = ?
ORDER BY rowid DESC
LIMIT 1
`

type GetLatestRuntimeForAdapterParams struct {
	AdapterID string
}

func (q *Queries) GetLatestRuntimeForAdapter(ctx context.Context, arg GetLatestRuntimeForAdapterParams) (AdapterRuntime, error) {
	row := q.db.QueryRowContext(ctx, getLatestRuntimeForAdapter, arg.AdapterID)
	var i AdapterRuntime
	err := row.Scan(
		&i.RuntimeID,
		&i.ClaimID,
		&i.AdapterID,
		&i.SoftwareName,
		&i.SoftwareVersion,
		&i.ClaimedAt,
		&i.LastHeartbeatAt,
		&i.LeaseExpiresAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const getRuntime = `-- name: GetRuntime :one
SELECT runtime_id, claim_id, adapter_id, software_name, software_version,
       claimed_at, last_heartbeat_at, lease_expires_at, ended_at, end_reason
FROM adapter_runtimes
WHERE runtime_id = ?
`

type GetRuntimeParams struct {
	RuntimeID string
}

func (q *Queries) GetRuntime(ctx context.Context, arg GetRuntimeParams) (AdapterRuntime, error) {
	row := q.db.QueryRowContext(ctx, getRuntime, arg.RuntimeID)
	var i AdapterRuntime
	err := row.Scan(
		&i.RuntimeID,
		&i.ClaimID,
		&i.AdapterID,
		&i.SoftwareName,
		&i.SoftwareVersion,
		&i.ClaimedAt,
		&i.LastHeartbeatAt,
		&i.LeaseExpiresAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const getRuntimeByClaimID = `-- name: GetRuntimeByClaimID :one
SELECT runtime_id, claim_id, adapter_id, software_name, software_version,
       claimed_at, last_heartbeat_at, lease_expires_at, ended_at, end_reason
FROM adapter_runtimes
WHERE claim_id = ?
`

type GetRuntimeByClaimIDParams struct {
	ClaimID string
}

func (q *Queries) GetRuntimeByClaimID(ctx context.Context, arg GetRuntimeByClaimIDParams) (AdapterRuntime, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeByClaimID, arg.ClaimID)
	var i AdapterRuntime
	err := row.Scan(
		&i.RuntimeID,
		&i.ClaimID,
		&i.AdapterID,
		&i.SoftwareName,
		&i.SoftwareVersion,
		&i.ClaimedAt,
		&i.LastHeartbeatAt,
		&i.LeaseExpiresAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const insertHealthTransition = `-- name: InsertHealthTransition :one
INSERT INTO health_transitions (
    resource_kind, adapter_id, entity_id, runtime_id, status, source,
    reason_code, source_observed_at, observed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING receive_order
`

type InsertHealthTransitionParams struct {
	ResourceKind     string
	AdapterID        string
	EntityID         sql.NullString
	RuntimeID        sql.NullString
	Status           string
	Source           string
	ReasonCode       sql.NullString
	SourceObservedAt sql.NullString
	ObservedAt       string
}

func (q *Queries) InsertHealthTransition(ctx context.Context, arg InsertHealthTransitionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertHealthTransition,
		arg.ResourceKind,
		arg.AdapterID,
		arg.EntityID,
		arg.RuntimeID,
		arg.Status,
		arg.Source,
		arg.ReasonCode,
		arg.SourceObservedAt,
		arg.ObservedAt,
	)
	var receive_order int64
	err := row.Scan(&receive_order)
	return receive_order, err
}

const insertRuntime = `-- name: InsertRuntime :exec
INSERT INTO adapter_runtimes (
    runtime_id, claim_id, adapter_id, software_name, software_version,
    claimed_at, lease_expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertRuntimeParams struct {
	RuntimeID       string
	ClaimID         string
	AdapterID       string
	SoftwareName    string
	SoftwareVersion string
	ClaimedAt       string
	LeaseExpiresAt  string
}

func (q *Queries) InsertRuntime(ctx context.Context, arg InsertRuntimeParams) error {
	_, err := q.db.ExecContext(ctx, insertRuntime,
		arg.RuntimeID,
		arg.ClaimID,
		arg.AdapterID,
		arg.SoftwareName,
		arg.SoftwareVersion,
		arg.ClaimedAt,
		arg.LeaseExpiresAt,
	)
	return err
}

const listAdapterHealthHistoryBefore = `-- name: ListAdapterHealthHistoryBefore :many
SELECT receive_order, status, source, reason_code, source_observed_at, observed_at
FROM health_transitions
WHERE resource_kind = 'adapter' AND adapter_id = ? AND receive_order < ?
ORDER BY receive_order DESC
LIMIT ?
`

type ListAdapterHealthHistoryBeforeParams struct {
	AdapterID    string
	ReceiveOrder int64
	Limit        int64
}

type ListAdapterHealthHistoryBeforeRow struct {
	ReceiveOrder     int64
	Status           string
	Source           string
	ReasonCode       sql.NullString
	SourceObservedAt sql.NullString
	ObservedAt       string
}

func (q *Queries) ListAdapterHealthHistoryBefore(ctx context.Context, arg ListAdapterHealthHistoryBeforeParams) ([]ListAdapterHealthHistoryBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdapterHealthHistoryBefore, arg.AdapterID, arg.ReceiveOrder, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdapterHealthHistoryBeforeRow
	for rows.Next() {
		var i ListAdapterHealthHistoryBeforeRow
		if err := rows.Scan(
			&i.ReceiveOrder,
			&i.Status,
			&i.Source,
			&i.ReasonCode,
			&i.SourceObservedAt,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdapterHealthHistoryFirstPage = `-- name: ListAdapterHealthHistoryFirstPage :many
SELECT receive_order, status, source, reason_code, source_observed_at, observed_at
FROM health_transitions
WHERE resource_kind = 'adapter' AND adapter_id = ?
ORDER BY receive_order DESC
LIMIT ?
`

type ListAdapterHealthHistoryFirstPageParams struct {
	AdapterID string
	Limit     int64
}

type ListAdapterHealthHistoryFirstPageRow struct {
	ReceiveOrder     int64
	Status           string
	Source           string
	ReasonCode       sql.NullString
	SourceObservedAt sql.NullString
	ObservedAt       string
}

func (q *Queries) ListAdapterHealthHistoryFirstPage(ctx context.Context, arg ListAdapterHealthHistoryFirstPageParams) ([]ListAdapterHealthHistoryFirstPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdapterHealthHistoryFirstPage, arg.AdapterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdapterHealthHistoryFirstPageRow
	for rows.Next() {
		var i ListAdapterHealthHistoryFirstPageRow
		if err := rows.Scan(
			&i.ReceiveOrder,
			&i.Status,
			&i.Source,
			&i.ReasonCode,
			&i.SourceObservedAt,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdapterViewsAfter = `-- name: ListAdapterViewsAfter :many
SELECT
    ai.adapter_id,
    ai.archived_at,
    ai.health_status,
    ai.health_reason_code,
    ai.health_since,
    ai.health_evidence_at,
    ai.external_system_status,
    ai.external_system_reason_code,
    ai.external_system_source_observed_at,
    ai.external_system_evidence_at,
    ar.runtime_id,
    ar.software_name,
    ar.software_version,
    ar.claimed_at,
    ar.last_heartbeat_at,
    ar.lease_expires_at,
    ar.ended_at
FROM adapter_instances AS ai
LEFT JOIN adapter_runtimes AS ar ON ar.runtime_id = ai.health_runtime_id
WHERE ai.adapter_id > ?1
  AND (?2 OR ai.archived_at IS NULL)
ORDER BY ai.adapter_id
LIMIT ?3
`

type ListAdapterViewsAfterParams struct {
	AfterAdapterID  string
	IncludeArchived interface{}
	PageLimit       int64
}

type ListAdapterViewsAfterRow struct {
	AdapterID                      string
	ArchivedAt                     sql.NullString
	HealthStatus                   sql.NullString
	HealthReasonCode               sql.NullString
	HealthSince                    sql.NullString
	HealthEvidenceAt               sql.NullString
	ExternalSystemStatus           sql.NullString
	ExternalSystemReasonCode       sql.NullString
	ExternalSystemSourceObservedAt sql.NullString
	ExternalSystemEvidenceAt       sql.NullString
	RuntimeID                      sql.NullString
	SoftwareName                   sql.NullString
	SoftwareVersion                sql.NullString
	ClaimedAt                      sql.NullString
	LastHeartbeatAt                sql.NullString
	LeaseExpiresAt                 sql.NullString
	EndedAt                        sql.NullString
}

func (q *Queries) ListAdapterViewsAfter(ctx context.Context, arg ListAdapterViewsAfterParams) ([]ListAdapterViewsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdapterViewsAfter, arg.AfterAdapterID, arg.IncludeArchived, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdapterViewsAfterRow
	for rows.Next() {
		var i ListAdapterViewsAfterRow
		if err := rows.Scan(
			&i.AdapterID,
			&i.ArchivedAt,
			&i.HealthStatus,
			&i.HealthReasonCode,
			&i.HealthSince,
			&i.HealthEvidenceAt,
			&i.ExternalSystemStatus,
			&i.ExternalSystemReasonCode,
			&i.ExternalSystemSourceObservedAt,
			&i.ExternalSystemEvidenceAt,
			&i.RuntimeID,
			&i.SoftwareName,
			&i.SoftwareVersion,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.LeaseExpiresAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdapterViewsFirstPage = `-- name: ListAdapterViewsFirstPage :many
SELECT
    ai.adapter_id,
    ai.archived_at,
    ai.health_status,
    ai.health_reason_code,
    ai.health_since,
    ai.health_evidence_at,
    ai.external_system_status,
    ai.external_system_reason_code,
    ai.external_system_source_observed_at,
    ai.external_system_evidence_at,
    ar.runtime_id,
    ar.software_name,
    ar.software_version,
    ar.claimed_at,
    ar.last_heartbeat_at,
    ar.lease_expires_at,
    ar.ended_at
FROM adapter_instances AS ai
LEFT JOIN adapter_runtimes AS ar ON ar.runtime_id = ai.health_runtime_id
WHERE (?1 OR ai.archived_at IS NULL)
ORDER BY ai.adapter_id
LIMIT ?2
`

type ListAdapterViewsFirstPageParams struct {
	IncludeArchived interface{}
	PageLimit       int64
}

type ListAdapterViewsFirstPageRow struct {
	AdapterID                      string
	ArchivedAt                     sql.NullString
	HealthStatus                   sql.NullString
	HealthReasonCode               sql.NullString
	HealthSince                    sql.NullString
	HealthEvidenceAt               sql.NullString
	ExternalSystemStatus           sql.NullString
	ExternalSystemReasonCode       sql.NullString
	ExternalSystemSourceObservedAt sql.NullString
	ExternalSystemEvidenceAt       sql.NullString
	RuntimeID                      sql.NullString
	SoftwareName                   sql.NullString
	SoftwareVersion                sql.NullString
	ClaimedAt                      sql.NullString
	LastHeartbeatAt                sql.NullString
	LeaseExpiresAt                 sql.NullString
	EndedAt                        sql.NullString
}

func (q *Queries) ListAdapterViewsFirstPage(ctx context.Context, arg ListAdapterViewsFirstPageParams) ([]ListAdapterViewsFirstPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdapterViewsFirstPage, arg.IncludeArchived, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdapterViewsFirstPageRow
	for rows.Next() {
		var i ListAdapterViewsFirstPageRow
		if err := rows.Scan(
			&i.AdapterID,
			&i.ArchivedAt,
			&i.HealthStatus,
			&i.HealthReasonCode,
			&i.HealthSince,
			&i.HealthEvidenceAt,
			&i.ExternalSystemStatus,
			&i.ExternalSystemReasonCode,
			&i.ExternalSystemSourceObservedAt,
			&i.ExternalSystemEvidenceAt,
			&i.RuntimeID,
			&i.SoftwareName,
			&i.SoftwareVersion,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.LeaseExpiresAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityAvailabilityHistoryBefore = `-- name: ListEntityAvailabilityHistoryBefore :many
WITH entity_lifetime AS (
    SELECT initial.adapter_id, MIN(initial.receive_order) AS starting_receive_order
    FROM health_transitions AS initial
    WHERE initial.resource_kind = 'entity' AND initial.entity_id = ?3
    GROUP BY initial.adapter_id
), candidates AS (
    SELECT
        transition.receive_order,
        transition.status,
        transition.source,
        transition.reason_code,
        transition.source_observed_at,
        transition.observed_at
    FROM health_transitions AS transition
    WHERE transition.resource_kind = 'entity'
      AND transition.entity_id = ?3

    UNION ALL

    SELECT
        transition.receive_order,
        CASE WHEN transition.status = 'unhealthy' THEN 'unavailable' ELSE 'unknown' END AS status,
        CASE WHEN transition.status = 'healthy' THEN 'core' ELSE 'adapter_health' END AS source,
        CASE
            WHEN transition.status = 'healthy' THEN 'hearth.awaiting_entity_report'
            ELSE transition.reason_code
        END AS reason_code,
        CASE WHEN transition.status = 'healthy' THEN NULL ELSE transition.source_observed_at END AS source_observed_at,
        transition.observed_at
    FROM entity_lifetime AS lifetime
    JOIN health_transitions AS transition
        ON transition.resource_kind = 'adapter'
        AND transition.adapter_id = lifetime.adapter_id
        AND transition.receive_order >= lifetime.starting_receive_order
), sequenced AS (
    SELECT
        candidates.receive_order, candidates.status, candidates.source, candidates.reason_code, candidates.source_observed_at, candidates.observed_at,
        lag(status) OVER (ORDER BY receive_order) AS prior_status,
        lag(reason_code) OVER (ORDER BY receive_order) AS prior_reason_code
    FROM candidates
), effective AS (
    SELECT receive_order, status, source, reason_code, source_observed_at, observed_at
    FROM sequenced
    WHERE prior_status IS NULL
       OR status <> prior_status
       OR reason_code IS NOT prior_reason_code
)
SELECT receive_order, status, source, reason_code, source_observed_at, observed_at
FROM effective
WHERE receive_order < CAST(?1 AS INTEGER)
ORDER BY receive_order DESC
LIMIT ?2
`

type ListEntityAvailabilityHistoryBeforeParams struct {
	BeforeReceiveOrder int64
	PageLimit          int64
	EntityID           sql.NullString
}

type ListEntityAvailabilityHistoryBeforeRow struct {
	ReceiveOrder     int64
	Status           string
	Source           string
	ReasonCode       sql.NullString
	SourceObservedAt sql.NullString
	ObservedAt       string
}

func (q *Queries) ListEntityAvailabilityHistoryBefore(ctx context.Context, arg ListEntityAvailabilityHistoryBeforeParams) ([]ListEntityAvailabilityHistoryBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityAvailabilityHistoryBefore, arg.BeforeReceiveOrder, arg.PageLimit, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityAvailabilityHistoryBeforeRow
	for rows.Next() {
		var i ListEntityAvailabilityHistoryBeforeRow
		if err := rows.Scan(
			&i.ReceiveOrder,
			&i.Status,
			&i.Source,
			&i.ReasonCode,
			&i.SourceObservedAt,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityAvailabilityHistoryFirstPage = `-- name: ListEntityAvailabilityHistoryFirstPage :many
WITH entity_lifetime AS (
    SELECT initial.adapter_id, MIN(initial.receive_order) AS starting_receive_order
    FROM health_transitions AS initial
    WHERE initial.resource_kind = 'entity' AND initial.entity_id = ?2
    GROUP BY initial.adapter_id
), candidates AS (
    SELECT
        transition.receive_order,
        transition.status,
        transition.source,
        transition.reason_code,
        transition.source_observed_at,
        transition.observed_at
    FROM health_transitions AS transition
    WHERE transition.resource_kind = 'entity'
      AND transition.entity_id = ?2

    UNION ALL

    SELECT
        transition.receive_order,
        CASE WHEN transition.status = 'unhealthy' THEN 'unavailable' ELSE 'unknown' END AS status,
        CASE WHEN transition.status = 'healthy' THEN 'core' ELSE 'adapter_health' END AS source,
        CASE
            WHEN transition.status = 'healthy' THEN 'hearth.awaiting_entity_report'
            ELSE transition.reason_code
        END AS reason_code,
        CASE WHEN transition.status = 'healthy' THEN NULL ELSE transition.source_observed_at END AS source_observed_at,
        transition.observed_at
    FROM entity_lifetime AS lifetime
    JOIN health_transitions AS transition
        ON transition.resource_kind = 'adapter'
        AND transition.adapter_id = lifetime.adapter_id
        AND transition.receive_order >= lifetime.starting_receive_order
), sequenced AS (
    SELECT
        candidates.receive_order, candidates.status, candidates.source, candidates.reason_code, candidates.source_observed_at, candidates.observed_at,
        lag(status) OVER (ORDER BY receive_order) AS prior_status,
        lag(reason_code) OVER (ORDER BY receive_order) AS prior_reason_code
    FROM candidates
), effective AS (
    SELECT receive_order, status, source, reason_code, source_observed_at, observed_at
    FROM sequenced
    WHERE prior_status IS NULL
       OR status <> prior_status
       OR reason_code IS NOT prior_reason_code
)
SELECT receive_order, status, source, reason_code, source_observed_at, observed_at
FROM effective
ORDER BY receive_order DESC
LIMIT ?1
`

type ListEntityAvailabilityHistoryFirstPageParams struct {
	PageLimit int64
	EntityID  sql.NullString
}

type ListEntityAvailabilityHistoryFirstPageRow struct {
	ReceiveOrder     int64
	Status           string
	Source           string
	ReasonCode       sql.NullString
	SourceObservedAt sql.NullString
	ObservedAt       string
}

func (q *Queries) ListEntityAvailabilityHistoryFirstPage(ctx context.Context, arg ListEntityAvailabilityHistoryFirstPageParams) ([]ListEntityAvailabilityHistoryFirstPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityAvailabilityHistoryFirstPage, arg.PageLimit, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityAvailabilityHistoryFirstPageRow
	for rows.Next() {
		var i ListEntityAvailabilityHistoryFirstPageRow
		if err := rows.Scan(
			&i.ReceiveOrder,
			&i.Status,
			&i.Source,
			&i.ReasonCode,
			&i.SourceObservedAt,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredRuntimes = `-- name: ListExpiredRuntimes :many
SELECT runtime_id, claim_id, adapter_id, software_name, software_version,
       claimed_at, last_heartbeat_at, lease_expires_at, ended_at, end_reason
FROM adapter_runtimes
WHERE ended_at IS NULL
  AND julianday(lease_expires_at) <= julianday(CAST(?1 AS TEXT))
ORDER BY lease_expires_at, runtime_id
`

type ListExpiredRuntimesParams struct {
	ExpiresAt string
}

func (q *Queries) ListExpiredRuntimes(ctx context.Context, arg ListExpiredRuntimesParams) ([]AdapterRuntime, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredRuntimes, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdapterRuntime
	for rows.Next() {
		var i AdapterRuntime
		if err := rows.Scan(
			&i.RuntimeID,
			&i.ClaimID,
			&i.AdapterID,
			&i.SoftwareName,
			&i.SoftwareVersion,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.LeaseExpiresAt,
			&i.EndedAt,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdapterCurrentHealth = `-- name: UpdateAdapterCurrentHealth :exec
UPDATE adapter_instances
SET active_runtime_id = ?,
    health_runtime_id = ?,
    health_status = ?,
    health_reason_code = ?,
    health_since = ?,
    health_evidence_at = ?,
    external_system_status = ?,
    external_system_reason_code = ?,
    external_system_source_observed_at = ?,
    external_system_evidence_at = ?
WHERE adapter_id = ?
`

type UpdateAdapterCurrentHealthParams struct {
	ActiveRuntimeID                sql.NullString
	HealthRuntimeID                sql.NullString
	HealthStatus                   sql.NullString
	HealthReasonCode               sql.NullString
	HealthSince                    sql.NullString
	HealthEvidenceAt               sql.NullString
	ExternalSystemStatus           sql.NullString
	ExternalSystemReasonCode       sql.NullString
	ExternalSystemSourceObservedAt sql.NullString
	ExternalSystemEvidenceAt       sql.NullString
	AdapterID                      string
}

func (q *Queries) UpdateAdapterCurrentHealth(ctx context.Context, arg UpdateAdapterCurrentHealthParams) error {
	_, err := q.db.ExecContext(ctx, updateAdapterCurrentHealth,
		arg.ActiveRuntimeID,
		arg.HealthRuntimeID,
		arg.HealthStatus,
		arg.HealthReasonCode,
		arg.HealthSince,
		arg.HealthEvidenceAt,
		arg.ExternalSystemStatus,
		arg.ExternalSystemReasonCode,
		arg.ExternalSystemSourceObservedAt,
		arg.ExternalSystemEvidenceAt,
		arg.AdapterID,
	)
	return err
}

const updateRuntimeHeartbeat = `-- name: UpdateRuntimeHeartbeat :execrows
UPDATE adapter_runtimes
SET last_heartbeat_at = ?, lease_expires_at = ?
WHERE runtime_id = ? AND adapter_id = ? AND ended_at IS NULL
`

type UpdateRuntimeHeartbeatParams struct {
	LastHeartbeatAt sql.NullString
	LeaseExpiresAt  string
	RuntimeID       string
	AdapterID       string
}

func (q *Queries) UpdateRuntimeHeartbeat(ctx context.Context, arg UpdateRuntimeHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRuntimeHeartbeat,
		arg.LastHeartbeatAt,
		arg.LeaseExpiresAt,
		arg.RuntimeID,
		arg.AdapterID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEntityAvailabilityCurrent = `-- name: UpsertEntityAvailabilityCurrent :exec
INSERT INTO entity_availability_current (
    entity_id, adapter_id, runtime_id, status, reason_code,
    source_observed_at, evidence_at, current_since,
    latest_transition_receive_order
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(entity_id) DO UPDATE SET
    adapter_id = excluded.adapter_id,
    runtime_id = excluded.runtime_id,
    status = excluded.status,
    reason_code = excluded.reason_code,
    source_observed_at = excluded.source_observed_at,
    evidence_at = excluded.evidence_at,
    current_since = excluded.current_since,
    latest_transition_receive_order = excluded.latest_transition_receive_order
`

type UpsertEntityAvailabilityCurrentParams struct {
	EntityID                     string
	AdapterID                    string
	RuntimeID                    string
	Status                       string
	ReasonCode                   sql.NullString
	SourceObservedAt             string
	EvidenceAt                   string
	CurrentSince                 string
	LatestTransitionReceiveOrder sql.NullInt64
}

func (q *Queries) UpsertEntityAvailabilityCurrent(ctx context.Context, arg UpsertEntityAvailabilityCurrentParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntityAvailabilityCurrent,
		arg.EntityID,
		arg.AdapterID,
		arg.RuntimeID,
		arg.Status,
		arg.ReasonCode,
		arg.SourceObservedAt,
		arg.EvidenceAt,
		arg.CurrentSince,
		arg.LatestTransitionReceiveOrder,
	)
	return err
}
