// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"database/sql"
)

type AdapterBinding struct {
	AdapterID        string
	BindingKey       string
	DeviceID         string
	ExternalDeviceID sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

type AdapterEntityMapping struct {
	AdapterID        string
	BindingKey       string
	EntityKey        string
	EntityID         string
	ExternalEntityID string
	CreatedAt        string
	UpdatedAt        string
}

type AdapterInstance struct {
	AdapterID                      string
	ArchivedAt                     sql.NullString
	ActiveRuntimeID                sql.NullString
	HealthRuntimeID                sql.NullString
	HealthStatus                   sql.NullString
	HealthReasonCode               sql.NullString
	HealthSince                    sql.NullString
	HealthEvidenceAt               sql.NullString
	ExternalSystemStatus           sql.NullString
	ExternalSystemReasonCode       sql.NullString
	ExternalSystemSourceObservedAt sql.NullString
	ExternalSystemEvidenceAt       sql.NullString
}

type AdapterRuntime struct {
	RuntimeID       string
	ClaimID         string
	AdapterID       string
	SoftwareName    string
	SoftwareVersion string
	ClaimedAt       string
	LastHeartbeatAt sql.NullString
	LeaseExpiresAt  string
	EndedAt         sql.NullString
	EndReason       sql.NullString
}

type Command struct {
	ID                   string
	EntityID             string
	AdapterID            string
	RuntimeID            sql.NullString
	Operation            string
	ParametersJson       string
	CorrelationID        string
	Status               string
	RequestedAt          string
	DeadlineAt           string
	AcceptedAt           sql.NullString
	CompletedAt          sql.NullString
	OutcomeObservationID sql.NullString
	FailureCode          sql.NullString
}

type Device struct {
	ID        string
	Kind      string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type Entity struct {
	ID          string
	DeviceID    string
	Name        string
	TypeID      string
	SupportJson string
	CreatedAt   string
	UpdatedAt   string
	Enabled     int64
}

type EntityAvailabilityCurrent struct {
	EntityID                     string
	AdapterID                    string
	RuntimeID                    string
	Status                       string
	ReasonCode                   sql.NullString
	SourceObservedAt             string
	EvidenceAt                   string
	CurrentSince                 string
	LatestTransitionReceiveOrder sql.NullInt64
}

type EntityReadProjection struct {
	ID                                   string
	DeviceID                             string
	AdapterID                            string
	Name                                 string
	TypeID                               string
	SupportJson                          string
	Enabled                              int64
	EntityCreatedAt                      string
	ObservationID                        sql.NullString
	ValueJson                            sql.NullString
	AdapterReceivedAt                    sql.NullString
	SourceUpdatedAt                      sql.NullString
	ObservedAt                           sql.NullString
	ReceiveOrder                         sql.NullInt64
	AdapterHealthStatus                  sql.NullString
	AdapterHealthReasonCode              sql.NullString
	AdapterHealthSince                   sql.NullString
	AdapterHealthEvidenceAt              sql.NullString
	ReportedAvailabilityStatus           sql.NullString
	ReportedAvailabilityReasonCode       sql.NullString
	ReportedAvailabilitySourceObservedAt sql.NullString
	ReportedAvailabilityEvidenceAt       sql.NullString
	ReportedAvailabilitySince            sql.NullString
}

type EntityState struct {
	EntityID          string
	ObservationID     string
	ValueJson         string
	AdapterReceivedAt string
	SourceUpdatedAt   sql.NullString
	ObservedAt        string
	ReceiveOrder      int64
}

type HealthTransition struct {
	ReceiveOrder     int64
	ResourceKind     string
	AdapterID        string
	EntityID         sql.NullString
	RuntimeID        sql.NullString
	Status           string
	Source           string
	ReasonCode       sql.NullString
	SourceObservedAt sql.NullString
	ObservedAt       string
}

type ObservationReceipt struct {
	ReceiveOrder      int64
	ObservationID     string
	AdapterID         string
	RuntimeID         sql.NullString
	EntityID          string
	Disposition       string
	RejectionCode     sql.NullString
	AdapterReceivedAt string
	ObservedAt        string
	ExpiresAt         string
}
