// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const getAdapterRuntime = `-- name: GetAdapterRuntime :one
SELECT runtime_id
FROM adapter_runtimes
WHERE adapter_id = ?1
  AND runtime_id = CAST(?2 AS TEXT)
`

type GetAdapterRuntimeParams struct {
	AdapterID string
	RuntimeID string
}

func (q *Queries) GetAdapterRuntime(ctx context.Context, arg GetAdapterRuntimeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getAdapterRuntime, arg.AdapterID, arg.RuntimeID)
	var runtime_id string
	err := row.Scan(&runtime_id)
	return runtime_id, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, kind, name
FROM devices
WHERE id = ?
`

type GetDeviceParams struct {
	ID string
}

type GetDeviceRow struct {
	ID   string
	Kind string
	Name string
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (GetDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getDevice, arg.ID)
	var i GetDeviceRow
	err := row.Scan(&i.ID, &i.Kind, &i.Name)
	return i, err
}

const getEntity = `-- name: GetEntity :one
SELECT id, device_id, adapter_id, name, type_id, support_json, enabled, entity_created_at, observation_id, value_json, adapter_received_at, source_updated_at, observed_at, receive_order, adapter_health_status, adapter_health_reason_code, adapter_health_since, adapter_health_evidence_at, reported_availability_status, reported_availability_reason_code, reported_availability_source_observed_at, reported_availability_evidence_at, reported_availability_since
FROM entity_read_projection
WHERE id = ?
`

type GetEntityParams struct {
	ID string
}

func (q *Queries) GetEntity(ctx context.Context, arg GetEntityParams) (EntityReadProjection, error) {
	row := q.db.QueryRowContext(ctx, getEntity, arg.ID)
	var i EntityReadProjection
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.AdapterID,
		&i.Name,
		&i.TypeID,
		&i.SupportJson,
		&i.Enabled,
		&i.EntityCreatedAt,
		&i.ObservationID,
		&i.ValueJson,
		&i.AdapterReceivedAt,
		&i.SourceUpdatedAt,
		&i.ObservedAt,
		&i.ReceiveOrder,
		&i.AdapterHealthStatus,
		&i.AdapterHealthReasonCode,
		&i.AdapterHealthSince,
		&i.AdapterHealthEvidenceAt,
		&i.ReportedAvailabilityStatus,
		&i.ReportedAvailabilityReasonCode,
		&i.ReportedAvailabilitySourceObservedAt,
		&i.ReportedAvailabilityEvidenceAt,
		&i.ReportedAvailabilitySince,
	)
	return i, err
}

const getEntityState = `-- name: GetEntityState :one
SELECT entity_id, observation_id, value_json, adapter_received_at,
       source_updated_at, observed_at, receive_order
FROM entity_states
WHERE entity_id = ?
`

type GetEntityStateParams struct {
	EntityID string
}

func (q *Queries) GetEntityState(ctx context.Context, arg GetEntityStateParams) (EntityState, error) {
	row := q.db.QueryRowContext(ctx, getEntityState, arg.EntityID)
	var i EntityState
	err := row.Scan(
		&i.EntityID,
		&i.ObservationID,
		&i.ValueJson,
		&i.AdapterReceivedAt,
		&i.SourceUpdatedAt,
		&i.ObservedAt,
		&i.ReceiveOrder,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, kind, name
FROM devices
WHERE id > ?
ORDER BY id ASC
LIMIT ?
`

type ListDevicesParams struct {
	ID    string
	Limit int64
}

type ListDevicesRow struct {
	ID   string
	Kind string
	Name string
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesRow
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntities = `-- name: ListEntities :many
SELECT id, device_id, adapter_id, name, type_id, support_json, enabled, entity_created_at, observation_id, value_json, adapter_received_at, source_updated_at, observed_at, receive_order, adapter_health_status, adapter_health_reason_code, adapter_health_since, adapter_health_evidence_at, reported_availability_status, reported_availability_reason_code, reported_availability_source_observed_at, reported_availability_evidence_at, reported_availability_since
FROM entity_read_projection
WHERE id > ?
ORDER BY id ASC
LIMIT ?
`

type ListEntitiesParams struct {
	ID    string
	Limit int64
}

func (q *Queries) ListEntities(ctx context.Context, arg ListEntitiesParams) ([]EntityReadProjection, error) {
	rows, err := q.db.QueryContext(ctx, listEntities, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityReadProjection
	for rows.Next() {
		var i EntityReadProjection
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.AdapterID,
			&i.Name,
			&i.TypeID,
			&i.SupportJson,
			&i.Enabled,
			&i.EntityCreatedAt,
			&i.ObservationID,
			&i.ValueJson,
			&i.AdapterReceivedAt,
			&i.SourceUpdatedAt,
			&i.ObservedAt,
			&i.ReceiveOrder,
			&i.AdapterHealthStatus,
			&i.AdapterHealthReasonCode,
			&i.AdapterHealthSince,
			&i.AdapterHealthEvidenceAt,
			&i.ReportedAvailabilityStatus,
			&i.ReportedAvailabilityReasonCode,
			&i.ReportedAvailabilitySourceObservedAt,
			&i.ReportedAvailabilityEvidenceAt,
			&i.ReportedAvailabilitySince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByDevice = `-- name: ListEntitiesByDevice :many
SELECT id, device_id, adapter_id, name, type_id, support_json, enabled, entity_created_at, observation_id, value_json, adapter_received_at, source_updated_at, observed_at, receive_order, adapter_health_status, adapter_health_reason_code, adapter_health_since, adapter_health_evidence_at, reported_availability_status, reported_availability_reason_code, reported_availability_source_observed_at, reported_availability_evidence_at, reported_availability_since
FROM entity_read_projection
WHERE device_id = ? AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListEntitiesByDeviceParams struct {
	DeviceID string
	ID       string
	Limit    int64
}

func (q *Queries) ListEntitiesByDevice(ctx context.Context, arg ListEntitiesByDeviceParams) ([]EntityReadProjection, error) {
	rows, err := q.db.QueryContext(ctx, listEntitiesByDevice, arg.DeviceID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityReadProjection
	for rows.Next() {
		var i EntityReadProjection
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.AdapterID,
			&i.Name,
			&i.TypeID,
			&i.SupportJson,
			&i.Enabled,
			&i.EntityCreatedAt,
			&i.ObservationID,
			&i.ValueJson,
			&i.AdapterReceivedAt,
			&i.SourceUpdatedAt,
			&i.ObservedAt,
			&i.ReceiveOrder,
			&i.AdapterHealthStatus,
			&i.AdapterHealthReasonCode,
			&i.AdapterHealthSince,
			&i.AdapterHealthEvidenceAt,
			&i.ReportedAvailabilityStatus,
			&i.ReportedAvailabilityReasonCode,
			&i.ReportedAvailabilitySourceObservedAt,
			&i.ReportedAvailabilityEvidenceAt,
			&i.ReportedAvailabilitySince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntityEnablement = `-- name: UpdateEntityEnablement :execrows
UPDATE entities
SET enabled = ?1, updated_at = ?2
WHERE id = ?3 AND enabled <> ?1
`

type UpdateEntityEnablementParams struct {
	Enabled   int64
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateEntityEnablement(ctx context.Context, arg UpdateEntityEnablementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEntityEnablement, arg.Enabled, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEntityState = `-- name: UpsertEntityState :exec
INSERT INTO entity_states (
    entity_id, observation_id, value_json, adapter_received_at,
    source_updated_at, observed_at, receive_order
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (entity_id) DO UPDATE SET
    observation_id = excluded.observation_id,
    value_json = excluded.value_json,
    adapter_received_at = excluded.adapter_received_at,
    source_updated_at = excluded.source_updated_at,
    observed_at = excluded.observed_at,
    receive_order = excluded.receive_order
`

type UpsertEntityStateParams struct {
	EntityID          string
	ObservationID     string
	ValueJson         string
	AdapterReceivedAt string
	SourceUpdatedAt   sql.NullString
	ObservedAt        string
	ReceiveOrder      int64
}

func (q *Queries) UpsertEntityState(ctx context.Context, arg UpsertEntityStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntityState,
		arg.EntityID,
		arg.ObservationID,
		arg.ValueJson,
		arg.AdapterReceivedAt,
		arg.SourceUpdatedAt,
		arg.ObservedAt,
		arg.ReceiveOrder,
	)
	return err
}
