// Code generated by entitytypegen; DO NOT EDIT.

package speedv1

func ValidateState(support Support, state State) error {
	return nil
}

func ValidateSupport(support Support) error {
	return nil
}

func EqualState(left, right State) bool { return left == right }
