// Code generated by entitytypegen; DO NOT EDIT.

// Package speedv1 provides schemas, behavior, and Go bindings for hearth.speed/v1.
package speedv1

const TypeID = "hearth.speed/v1"

type State float64

type StateSupport struct {
}

type OperationSupport struct {
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}
