// Code generated by entitytypegen; DO NOT EDIT.

// Package relativehumidityv1 provides schemas, behavior, and Go bindings for hearth.relativehumidity/v1.
package relativehumidityv1

const TypeID = "hearth.relativehumidity/v1"

type State float64

type StateSupport struct {
	Unit string `json:"unit"`
}

type OperationSupport struct {
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}
