// Code generated by entitytypegen; DO NOT EDIT.

package colorhsv1

import (
	"encoding/json"
	"testing"
	"time"
)

func TestGeneratedObservationConformance(t *testing.T) {
	codecs, err := codecs()
	if err != nil {
		t.Fatal(err)
	}
	t.Run("hs-target", func(t *testing.T) {
		support, _, err := codecs.Support.Decode(json.RawMessage("{\n        \"state\": {},\n        \"operations\": {\"set\": {}}\n      }"))
		if err != nil {
			t.Fatalf("support: %v", err)
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("{\"active\": true, \"hue\": 120, \"saturation\": 80}"))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != true {
				t.Errorf("State example 1: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("{\"active\": false, \"hue\": 0, \"saturation\": 0}"))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != true {
				t.Errorf("State example 2: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("{\"active\": true, \"hue\": 360, \"saturation\": 80}"))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != false {
				t.Errorf("State example 3: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("{\"hue\": 120, \"saturation\": 80}"))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != false {
				t.Errorf("State example 4: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
	})
}
