// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const updateDeviceNameOverride = `-- name: UpdateDeviceNameOverride :exec
UPDATE devices SET name_override = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateDeviceNameOverrideParams struct {
	NameOverride sql.NullString
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateDeviceNameOverride(ctx context.Context, arg UpdateDeviceNameOverrideParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceNameOverride, arg.NameOverride, arg.UpdatedAt, arg.ID)
	return err
}

const updateEntityNameOverride = `-- name: UpdateEntityNameOverride :exec
UPDATE entities SET name_override = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateEntityNameOverrideParams struct {
	NameOverride sql.NullString
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateEntityNameOverride(ctx context.Context, arg UpdateEntityNameOverrideParams) error {
	_, err := q.db.ExecContext(ctx, updateEntityNameOverride, arg.NameOverride, arg.UpdatedAt, arg.ID)
	return err
}
