// Code generated by entitytypegen; DO NOT EDIT.

package colormodev1

import (
	"errors"
	"fmt"
	"sync"
	"time"

	contractcolormodev1 "github.com/mholtzscher/hearth/entitytypes/colormodev1"
	"github.com/mholtzscher/hearth/sdk/adapter"
)

type Support = contractcolormodev1.Support
type State = contractcolormodev1.State
type StateSupport = contractcolormodev1.StateSupport
type OperationSupport = contractcolormodev1.OperationSupport

type ObservationInput struct {
	EntityID          string
	Support           Support
	State             State
	AdapterReceivedAt time.Time
	SourceUpdatedAt   *time.Time
}

var (
	compileOnce  sync.Once
	sharedCodecs *contractcolormodev1.Codecs
	compileErr   error
)

func NewEntityDescriptor(metadata adapter.EntityMetadata, support Support) (adapter.EntityDescriptor, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	normalized, err := codecs.Support.Encode(support)
	if err != nil {
		return adapter.EntityDescriptor{}, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	return adapter.EntityDescriptor{Key: metadata.Key, ExternalID: metadata.ExternalID, Name: metadata.Name, Type: contractcolormodev1.TypeID, Support: normalized}, nil
}

func NewObservation(input ObservationInput) (adapter.Observation, error) {
	if input.EntityID == "" {
		return adapter.Observation{}, validationError(errors.New("Observation entity ID is required"))
	}
	if input.AdapterReceivedAt.IsZero() {
		return adapter.Observation{}, validationError(errors.New("Observation adapter received time is required"))
	}
	if input.SourceUpdatedAt != nil && input.SourceUpdatedAt.IsZero() {
		return adapter.Observation{}, validationError(errors.New("Observation source updated time must be non-zero"))
	}
	codecs, err := codecs()
	if err != nil {
		return adapter.Observation{}, err
	}
	if _, err := codecs.Support.Encode(input.Support); err != nil {
		return adapter.Observation{}, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	if err := contractcolormodev1.ValidateState(input.Support, input.State); err != nil {
		return adapter.Observation{}, validationError(fmt.Errorf("unsupported State: %w", err))
	}
	value, err := codecs.State.Encode(input.State)
	if err != nil {
		return adapter.Observation{}, validationError(fmt.Errorf("invalid State: %w", err))
	}
	observation := adapter.Observation{EntityID: input.EntityID, Value: value, AdapterReceivedAt: input.AdapterReceivedAt.UTC().Format(time.RFC3339Nano)}
	if input.SourceUpdatedAt != nil {
		formatted := input.SourceUpdatedAt.UTC().Format(time.RFC3339Nano)
		observation.SourceUpdatedAt = &formatted
	}
	return observation, nil
}

func codecs() (*contractcolormodev1.Codecs, error) {
	compileOnce.Do(func() { sharedCodecs, compileErr = contractcolormodev1.Compile() })
	if compileErr != nil {
		return nil, fmt.Errorf("compile Entity-type schemas: %w", compileErr)
	}
	return sharedCodecs, nil
}

func validationError(err error) error { return &adapter.ValidationError{Err: err} }
