// Code generated by entitytypegen; DO NOT EDIT.

package colormodev1

import (
	"encoding/json"
	"testing"
	"time"
)

func TestGeneratedObservationConformance(t *testing.T) {
	codecs, err := codecs()
	if err != nil {
		t.Fatal(err)
	}
	t.Run("reported-modes", func(t *testing.T) {
		support, _, err := codecs.Support.Decode(json.RawMessage("{\"state\": {}, \"operations\": {}}"))
		if err != nil {
			t.Fatalf("support: %v", err)
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("\"xy\""))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != true {
				t.Errorf("State example 1: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("\"hs\""))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != true {
				t.Errorf("State example 2: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("\"color_temp\""))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != true {
				t.Errorf("State example 3: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("\"rgb\""))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != false {
				t.Errorf("State example 4: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
		{
			state, _, decodeErr := codecs.State.Decode(json.RawMessage("123"))
			valid := false
			var observationErr error
			if decodeErr == nil {
				_, observationErr = NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()})
				valid = observationErr == nil
			}
			if valid != false {
				t.Errorf("State example 5: valid = %v, decode error = %v, Observation error = %v", valid, decodeErr, observationErr)
			}
		}
	})
}
