// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automations.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const beginAutomationStep = `-- name: BeginAutomationStep :execrows
UPDATE automation_run_steps SET status = 'running', reserved_command_id = ?, reserved_correlation_id = ?, started_at = ?
WHERE automation_run_steps.run_id = ? AND automation_run_steps.step_index = ? AND automation_run_steps.status = 'pending'
AND EXISTS (SELECT 1 FROM automation_runs WHERE id = automation_run_steps.run_id AND status = 'running')
AND NOT EXISTS (SELECT 1 FROM automation_run_steps AS prior WHERE prior.run_id = automation_run_steps.run_id
    AND prior.step_index < automation_run_steps.step_index AND prior.status NOT IN ('satisfied', 'dispatched'))
`

type BeginAutomationStepParams struct {
	ReservedCommandID     sql.NullString
	ReservedCorrelationID sql.NullString
	StartedAt             sql.NullString
	RunID                 string
	StepIndex             int64
}

func (q *Queries) BeginAutomationStep(ctx context.Context, arg BeginAutomationStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, beginAutomationStep,
		arg.ReservedCommandID,
		arg.ReservedCorrelationID,
		arg.StartedAt,
		arg.RunID,
		arg.StepIndex,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeAutomationRun = `-- name: CompleteAutomationRun :execrows
UPDATE automation_runs SET status = ?, completed_at = ?, failure_code = ? WHERE id = ? AND status = 'running'
`

type CompleteAutomationRunParams struct {
	Status      string
	CompletedAt sql.NullString
	FailureCode sql.NullString
	ID          string
}

func (q *Queries) CompleteAutomationRun(ctx context.Context, arg CompleteAutomationRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeAutomationRun,
		arg.Status,
		arg.CompletedAt,
		arg.FailureCode,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeAutomationStep = `-- name: CompleteAutomationStep :execrows
UPDATE automation_run_steps SET status = ?, outcome = ?, failure_code = ?, completed_at = ?
WHERE run_id = ? AND step_index = ? AND status = 'running'
AND EXISTS (SELECT 1 FROM automation_runs WHERE id = automation_run_steps.run_id AND status = 'running')
`

type CompleteAutomationStepParams struct {
	Status      string
	Outcome     sql.NullString
	FailureCode sql.NullString
	CompletedAt sql.NullString
	RunID       string
	StepIndex   int64
}

func (q *Queries) CompleteAutomationStep(ctx context.Context, arg CompleteAutomationStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeAutomationStep,
		arg.Status,
		arg.Outcome,
		arg.FailureCode,
		arg.CompletedAt,
		arg.RunID,
		arg.StepIndex,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAutomation = `-- name: CreateAutomation :one
INSERT INTO automations (id, revision, name, enabled, triggers_json, steps_json, created_at, updated_at)
VALUES (?, 1, ?, ?, ?, ?, ?, ?) RETURNING id, revision, name, enabled, triggers_json, steps_json, created_at, updated_at
`

type CreateAutomationParams struct {
	ID           string
	Name         string
	Enabled      int64
	TriggersJson string
	StepsJson    string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) (Automation, error) {
	row := q.db.QueryRowContext(ctx, createAutomation,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.TriggersJson,
		arg.StepsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Name,
		&i.Enabled,
		&i.TriggersJson,
		&i.StepsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAutomationRun = `-- name: CreateAutomationRun :exec
INSERT INTO automation_runs (id, automation_id, revision, snapshot_json, source, scheduled_at, matched_trigger_ids_json, status, started_at, idempotency_key)
VALUES (?, ?, ?, ?, ?, ?, ?, 'running', ?, ?)
`

type CreateAutomationRunParams struct {
	ID                    string
	AutomationID          string
	Revision              int64
	SnapshotJson          string
	Source                string
	ScheduledAt           sql.NullString
	MatchedTriggerIdsJson string
	StartedAt             string
	IdempotencyKey        sql.NullString
}

func (q *Queries) CreateAutomationRun(ctx context.Context, arg CreateAutomationRunParams) error {
	_, err := q.db.ExecContext(ctx, createAutomationRun,
		arg.ID,
		arg.AutomationID,
		arg.Revision,
		arg.SnapshotJson,
		arg.Source,
		arg.ScheduledAt,
		arg.MatchedTriggerIdsJson,
		arg.StartedAt,
		arg.IdempotencyKey,
	)
	return err
}

const createAutomationRunStep = `-- name: CreateAutomationRunStep :exec
INSERT INTO automation_run_steps (run_id, step_index, definition_json, status) VALUES (?, ?, ?, 'pending')
`

type CreateAutomationRunStepParams struct {
	RunID          string
	StepIndex      int64
	DefinitionJson string
}

func (q *Queries) CreateAutomationRunStep(ctx context.Context, arg CreateAutomationRunStepParams) error {
	_, err := q.db.ExecContext(ctx, createAutomationRunStep, arg.RunID, arg.StepIndex, arg.DefinitionJson)
	return err
}

const deleteAutomation = `-- name: DeleteAutomation :execrows
DELETE FROM automations WHERE id = ? AND revision = ?
`

type DeleteAutomationParams struct {
	ID       string
	Revision int64
}

func (q *Queries) DeleteAutomation(ctx context.Context, arg DeleteAutomationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAutomation, arg.ID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveAutomationRun = `-- name: GetActiveAutomationRun :one
SELECT id FROM automation_runs WHERE automation_id = ? AND status = 'running'
`

type GetActiveAutomationRunParams struct {
	AutomationID string
}

func (q *Queries) GetActiveAutomationRun(ctx context.Context, arg GetActiveAutomationRunParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getActiveAutomationRun, arg.AutomationID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAutomation = `-- name: GetAutomation :one
SELECT id, revision, name, enabled, triggers_json, steps_json, created_at, updated_at FROM automations WHERE id = ?
`

type GetAutomationParams struct {
	ID string
}

func (q *Queries) GetAutomation(ctx context.Context, arg GetAutomationParams) (Automation, error) {
	row := q.db.QueryRowContext(ctx, getAutomation, arg.ID)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Name,
		&i.Enabled,
		&i.TriggersJson,
		&i.StepsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutomationCommandCandidate = `-- name: GetAutomationCommandCandidate :one
SELECT id, correlation_id, status FROM commands WHERE id = ?
`

type GetAutomationCommandCandidateParams struct {
	ID string
}

type GetAutomationCommandCandidateRow struct {
	ID            string
	CorrelationID string
	Status        string
}

// Command candidates are deliberately private. The module's one ownership predicate
// must verify both identities and pre-creation exclusion before exposing evidence.
func (q *Queries) GetAutomationCommandCandidate(ctx context.Context, arg GetAutomationCommandCandidateParams) (GetAutomationCommandCandidateRow, error) {
	row := q.db.QueryRowContext(ctx, getAutomationCommandCandidate, arg.ID)
	var i GetAutomationCommandCandidateRow
	err := row.Scan(&i.ID, &i.CorrelationID, &i.Status)
	return i, err
}

const getAutomationRun = `-- name: GetAutomationRun :one
SELECT id, automation_id, revision, snapshot_json, source, scheduled_at, matched_trigger_ids_json, status, started_at, completed_at, failure_code, idempotency_key FROM automation_runs WHERE id = ?
`

type GetAutomationRunParams struct {
	ID string
}

func (q *Queries) GetAutomationRun(ctx context.Context, arg GetAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRowContext(ctx, getAutomationRun, arg.ID)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Revision,
		&i.SnapshotJson,
		&i.Source,
		&i.ScheduledAt,
		&i.MatchedTriggerIdsJson,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.IdempotencyKey,
	)
	return i, err
}

const getManualAutomationRun = `-- name: GetManualAutomationRun :one
SELECT id, automation_id, revision, snapshot_json, source, scheduled_at, matched_trigger_ids_json, status, started_at, completed_at, failure_code, idempotency_key FROM automation_runs WHERE automation_id = ? AND idempotency_key = ?
`

type GetManualAutomationRunParams struct {
	AutomationID   string
	IdempotencyKey sql.NullString
}

func (q *Queries) GetManualAutomationRun(ctx context.Context, arg GetManualAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRowContext(ctx, getManualAutomationRun, arg.AutomationID, arg.IdempotencyKey)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Revision,
		&i.SnapshotJson,
		&i.Source,
		&i.ScheduledAt,
		&i.MatchedTriggerIdsJson,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureCode,
		&i.IdempotencyKey,
	)
	return i, err
}

const interruptRunningAutomationSteps = `-- name: InterruptRunningAutomationSteps :exec
UPDATE automation_run_steps SET status = 'interrupted', failure_code = ?, completed_at = ? WHERE run_id = ? AND status = 'running'
`

type InterruptRunningAutomationStepsParams struct {
	FailureCode sql.NullString
	CompletedAt sql.NullString
	RunID       string
}

func (q *Queries) InterruptRunningAutomationSteps(ctx context.Context, arg InterruptRunningAutomationStepsParams) error {
	_, err := q.db.ExecContext(ctx, interruptRunningAutomationSteps, arg.FailureCode, arg.CompletedAt, arg.RunID)
	return err
}

const listAutomationRunSteps = `-- name: ListAutomationRunSteps :many
SELECT run_id, step_index, definition_json, status, reserved_command_id, reserved_correlation_id, outcome, failure_code, started_at, completed_at FROM automation_run_steps WHERE run_id = ? ORDER BY step_index
`

type ListAutomationRunStepsParams struct {
	RunID string
}

func (q *Queries) ListAutomationRunSteps(ctx context.Context, arg ListAutomationRunStepsParams) ([]AutomationRunStep, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationRunSteps, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationRunStep
	for rows.Next() {
		var i AutomationRunStep
		if err := rows.Scan(
			&i.RunID,
			&i.StepIndex,
			&i.DefinitionJson,
			&i.Status,
			&i.ReservedCommandID,
			&i.ReservedCorrelationID,
			&i.Outcome,
			&i.FailureCode,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationRuns = `-- name: ListAutomationRuns :many
SELECT id, automation_id, revision, snapshot_json, source, scheduled_at, matched_trigger_ids_json, status, started_at, completed_at, failure_code, idempotency_key FROM automation_runs
WHERE (?1 IS NULL OR automation_id = ?1)
AND (?2 IS NULL OR (started_at, id) < (?2, ?3))
ORDER BY started_at DESC, id DESC LIMIT ?4
`

type ListAutomationRunsParams struct {
	AutomationFilter interface{}
	BeforeTime       interface{}
	BeforeID         sql.NullString
	PageLimit        int64
}

func (q *Queries) ListAutomationRuns(ctx context.Context, arg ListAutomationRunsParams) ([]AutomationRun, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationRuns,
		arg.AutomationFilter,
		arg.BeforeTime,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationRun
	for rows.Next() {
		var i AutomationRun
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.Revision,
			&i.SnapshotJson,
			&i.Source,
			&i.ScheduledAt,
			&i.MatchedTriggerIdsJson,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureCode,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomations = `-- name: ListAutomations :many
SELECT id, revision, name, enabled, triggers_json, steps_json, created_at, updated_at FROM automations WHERE id > ?1 ORDER BY id LIMIT ?2
`

type ListAutomationsParams struct {
	AfterID   string
	PageLimit int64
}

func (q *Queries) ListAutomations(ctx context.Context, arg ListAutomationsParams) ([]Automation, error) {
	rows, err := q.db.QueryContext(ctx, listAutomations, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.Name,
			&i.Enabled,
			&i.TriggersJson,
			&i.StepsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningAutomationRuns = `-- name: ListRunningAutomationRuns :many
SELECT id, automation_id, revision, snapshot_json, source, scheduled_at, matched_trigger_ids_json, status, started_at, completed_at, failure_code, idempotency_key FROM automation_runs WHERE status = 'running' ORDER BY id
`

func (q *Queries) ListRunningAutomationRuns(ctx context.Context) ([]AutomationRun, error) {
	rows, err := q.db.QueryContext(ctx, listRunningAutomationRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationRun
	for rows.Next() {
		var i AutomationRun
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.Revision,
			&i.SnapshotJson,
			&i.Source,
			&i.ScheduledAt,
			&i.MatchedTriggerIdsJson,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureCode,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAutomationHistory = `-- name: PruneAutomationHistory :execrows
DELETE FROM automation_runs WHERE id IN (
 SELECT id FROM automation_runs WHERE automation_runs.status <> 'running' AND automation_runs.completed_at < ?1
 ORDER BY automation_runs.completed_at, automation_runs.id LIMIT 500
)
`

type PruneAutomationHistoryParams struct {
	Cutoff sql.NullString
}

func (q *Queries) PruneAutomationHistory(ctx context.Context, arg PruneAutomationHistoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAutomationHistory, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const skipPendingAutomationSteps = `-- name: SkipPendingAutomationSteps :exec
UPDATE automation_run_steps SET status = 'not_attempted', completed_at = ? WHERE run_id = ? AND status = 'pending'
`

type SkipPendingAutomationStepsParams struct {
	CompletedAt sql.NullString
	RunID       string
}

func (q *Queries) SkipPendingAutomationSteps(ctx context.Context, arg SkipPendingAutomationStepsParams) error {
	_, err := q.db.ExecContext(ctx, skipPendingAutomationSteps, arg.CompletedAt, arg.RunID)
	return err
}

const updateAutomation = `-- name: UpdateAutomation :one
UPDATE automations SET revision = revision + 1, name = ?, enabled = ?, triggers_json = ?, steps_json = ?, updated_at = ?
WHERE id = ? AND revision = ?7 RETURNING id, revision, name, enabled, triggers_json, steps_json, created_at, updated_at
`

type UpdateAutomationParams struct {
	Name             string
	Enabled          int64
	TriggersJson     string
	StepsJson        string
	UpdatedAt        string
	ID               string
	ExpectedRevision int64
}

func (q *Queries) UpdateAutomation(ctx context.Context, arg UpdateAutomationParams) (Automation, error) {
	row := q.db.QueryRowContext(ctx, updateAutomation,
		arg.Name,
		arg.Enabled,
		arg.TriggersJson,
		arg.StepsJson,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Name,
		&i.Enabled,
		&i.TriggersJson,
		&i.StepsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
