defaultPlatforms:
  - linux/amd64
  - linux/arm64

builds:
  - id: hearthd
    main: ./cmd/hearthd
  - id: hearth-adapter-homeassistant
    main: ./cmd/hearth-adapter-homeassistant
  - id: hearth-adapter-zigbee2mqtt
    main: ./cmd/hearth-adapter-zigbee2mqtt
  - id: hearth-adapter-ecowitt
    main: ./cmd/hearth-adapter-ecowitt
  - id: hearth-adapter-zwavejs
    main: ./cmd/hearth-adapter-zwavejs
  - id: hearth-simulator
    main: ./cmd/hearth-simulator
