// Code generated by entitytypegen; DO NOT EDIT.

package enumactionv1

import (
	"embed"
	"encoding/json"
	"fmt"

	"github.com/mholtzscher/hearth/entitytypes"
)

const (
	StateSchemaID             = "urn:hearth:schema:entity-type:enumaction:v1:state"
	SupportSchemaID           = "urn:hearth:schema:entity-type:enumaction:v1:support"
	TriggerParametersSchemaID = "urn:hearth:schema:entity-type:enumaction:v1:trigger-parameters"
)

// FS contains the authoritative Entity-type JSON Schemas.
//
//go:embed "state.schema.json" "support.schema.json" "trigger-parameters.schema.json"
var FS embed.FS

func SchemaFiles() map[string]string {
	return map[string]string{
		StateSchemaID:             "state.schema.json",
		SupportSchemaID:           "support.schema.json",
		TriggerParametersSchemaID: "trigger-parameters.schema.json",
	}
}

type Codecs struct {
	State             *entitytypes.JSONCodec[State]
	Support           *entitytypes.JSONCodec[Support]
	TriggerParameters *entitytypes.JSONCodec[TriggerParameters]
}

func Compile() (*Codecs, error) {
	state, err := compileCodec[State](StateSchemaID, SchemaFiles()[StateSchemaID])
	if err != nil {
		return nil, err
	}
	support, err := compileCodec[Support](SupportSchemaID, SchemaFiles()[SupportSchemaID])
	if err != nil {
		return nil, err
	}
	triggerParameters, err := compileCodec[TriggerParameters](TriggerParametersSchemaID, SchemaFiles()[TriggerParametersSchemaID])
	if err != nil {
		return nil, err
	}
	return &Codecs{State: state, Support: support, TriggerParameters: triggerParameters}, nil
}

func compileCodec[T any](schemaID, path string) (*entitytypes.JSONCodec[T], error) {
	raw, err := FS.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	return entitytypes.CompileJSONCodec[T](schemaID, json.RawMessage(raw), nil)
}
