// Code generated by entitytypegen; DO NOT EDIT.

// Package enumactionv1 provides schemas, behavior, and Go bindings for hearth.enumaction/v1.
package enumactionv1

const TypeID = "hearth.enumaction/v1"

const (
	OperationTrigger = "trigger"
)

type State struct {
}

type StateSupport struct {
}

type TriggerSupportValues []string

type TriggerSupport struct {
	Values TriggerSupportValues `json:"values"`
}

type OperationSupport struct {
	Trigger TriggerSupport `json:"trigger"`
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}

type TriggerParameters struct {
	Name string `json:"name"`
}
