// Code generated by entitytypegen; DO NOT EDIT.

package pressurev1

import (
	"fmt"
	"sync"
	"time"

	contractpressurev1 "github.com/mholtzscher/hearth/entitytypes/pressurev1"
	"github.com/mholtzscher/hearth/sdk/adapter"
	"github.com/mholtzscher/hearth/sdk/adapter/typed"
)

type Support = contractpressurev1.Support
type State = contractpressurev1.State
type StateSupport = contractpressurev1.StateSupport
type OperationSupport = contractpressurev1.OperationSupport

type ObservationInput struct {
	EntityID          string
	Support           Support
	State             State
	AdapterReceivedAt time.Time
	SourceUpdatedAt   *time.Time
}

var (
	compileOnce  sync.Once
	sharedCodecs *contractpressurev1.Codecs
	compileErr   error
)

func NewEntityDescriptor(metadata adapter.EntityMetadata, support Support) (adapter.EntityDescriptor, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	descriptor, err := typed.NewTypedEntityDescriptor(metadata, contractpressurev1.TypeID, support, codecs.Support)
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	if err := contractpressurev1.ValidateSupport(support); err != nil {
		return adapter.EntityDescriptor{}, &adapter.ValidationError{Err: fmt.Errorf("invalid Entity support: %w", err)}
	}
	return descriptor, nil
}

func NewObservation(input ObservationInput) (adapter.Observation, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.Observation{}, err
	}
	return typed.NewTypedEntityObservation(typed.EntityObservationInput[State, Support]{EntityID: input.EntityID, Support: input.Support, State: input.State, AdapterReceivedAt: input.AdapterReceivedAt, SourceUpdatedAt: input.SourceUpdatedAt}, codecs.State, codecs.Support, contractpressurev1.ValidateState)
}

func codecs() (*contractpressurev1.Codecs, error) {
	compileOnce.Do(func() { sharedCodecs, compileErr = contractpressurev1.Compile() })
	if compileErr != nil {
		return nil, fmt.Errorf("compile Entity-type schemas: %w", compileErr)
	}
	return sharedCodecs, nil
}
