// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package commands

import (
	"database/sql"
)

type AdapterBinding struct {
	AdapterID        string
	BindingKey       string
	DeviceID         string
	ExternalDeviceID sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

type AdapterEntityMapping struct {
	AdapterID        string
	BindingKey       string
	EntityKey        string
	EntityID         string
	ExternalEntityID string
	CreatedAt        string
	UpdatedAt        string
}

type Command struct {
	ID                   string
	EntityID             string
	AdapterID            string
	Operation            string
	ParametersJson       string
	CorrelationID        string
	Status               string
	RequestedAt          string
	DeadlineAt           string
	AcceptedAt           sql.NullString
	CompletedAt          sql.NullString
	OutcomeObservationID sql.NullString
	FailureCode          sql.NullString
}

type Device struct {
	ID        string
	Kind      string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type Entity struct {
	ID          string
	DeviceID    string
	Name        string
	TypeID      string
	SupportJson string
	CreatedAt   string
	UpdatedAt   string
}

type EntityState struct {
	EntityID          string
	ObservationID     string
	ValueJson         string
	AdapterReceivedAt string
	SourceUpdatedAt   sql.NullString
	ObservedAt        string
	ReceiveOrder      int64
}

type ObservationReceipt struct {
	ReceiveOrder      int64
	ObservationID     string
	AdapterID         string
	EntityID          string
	Disposition       string
	RejectionCode     sql.NullString
	AdapterReceivedAt string
	ObservedAt        string
	ExpiresAt         string
}
