// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package commands

import (
	"context"
)

type Querier interface {
	CompleteCommand(ctx context.Context, arg CompleteCommandParams) (int64, error)
	CreateCommand(ctx context.Context, arg CreateCommandParams) error
	GetCommand(ctx context.Context, arg GetCommandParams) (Command, error)
	InterruptActiveCommands(ctx context.Context, arg InterruptActiveCommandsParams) (int64, error)
	ListEntityCommandsAfter(ctx context.Context, arg ListEntityCommandsAfterParams) ([]Command, error)
	ListEntityCommandsFirstPage(ctx context.Context, arg ListEntityCommandsFirstPageParams) ([]Command, error)
	MarkCommandAccepted(ctx context.Context, arg MarkCommandAcceptedParams) (int64, error)
	SatisfyCommandFromObservation(ctx context.Context, arg SatisfyCommandFromObservationParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
