// Code generated by entitytypegen; DO NOT EDIT.

package colorxyv1

import (
	"encoding/json"
	"testing"
)

func TestGeneratedConformance(t *testing.T) {
	codecs, err := Compile()
	if err != nil {
		t.Fatal(err)
	}
	t.Run("xy-target", func(t *testing.T) {
		support, _, err := codecs.Support.Decode(json.RawMessage("{\n        \"state\": {},\n        \"operations\": {\"set\": {}}\n      }"))
		if err != nil {
			t.Fatalf("support: %v", err)
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("{\"active\": true, \"x\": 3125, \"y\": 3291}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != true {
				t.Errorf("state example 1: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("{\"active\": false, \"x\": 0, \"y\": 0}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != true {
				t.Errorf("state example 2: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("{\"active\": true, \"x\": 10001, \"y\": 0}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != false {
				t.Errorf("state example 3: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("{\"x\": 3125, \"y\": 3291}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != false {
				t.Errorf("state example 4: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		setSupport := support.Operations.Set
		{
			value, _, decodeErr := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 3125, \"y\": 3291}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateSetParameters(support, setSupport, value) == nil
			}
			if valid != true {
				t.Errorf("set parameter example 1: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 0, \"y\": 0}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateSetParameters(support, setSupport, value) == nil
			}
			if valid != true {
				t.Errorf("set parameter example 2: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 10001, \"y\": 0}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateSetParameters(support, setSupport, value) == nil
			}
			if valid != false {
				t.Errorf("set parameter example 3: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 3125}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateSetParameters(support, setSupport, value) == nil
			}
			if valid != false {
				t.Errorf("set parameter example 4: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			parameters, _, err := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 3125, \"y\": 3291}"))
			if err != nil {
				t.Fatalf("set outcome 1 parameters: %v", err)
			}
			state, _, err := codecs.State.Decode(json.RawMessage("{\"active\": true, \"x\": 3125, \"y\": 3291}"))
			if err != nil {
				t.Fatalf("set outcome 1 State: %v", err)
			}
			if satisfied := SetSatisfied(parameters, state); satisfied != true {
				t.Errorf("set outcome 1: satisfied = %v", satisfied)
			}
		}
		{
			parameters, _, err := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 3125, \"y\": 3291}"))
			if err != nil {
				t.Fatalf("set outcome 2 parameters: %v", err)
			}
			state, _, err := codecs.State.Decode(json.RawMessage("{\"active\": true, \"x\": 3126, \"y\": 3290}"))
			if err != nil {
				t.Fatalf("set outcome 2 State: %v", err)
			}
			if satisfied := SetSatisfied(parameters, state); satisfied != true {
				t.Errorf("set outcome 2: satisfied = %v", satisfied)
			}
		}
		{
			parameters, _, err := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 3125, \"y\": 3291}"))
			if err != nil {
				t.Fatalf("set outcome 3 parameters: %v", err)
			}
			state, _, err := codecs.State.Decode(json.RawMessage("{\"active\": true, \"x\": 3127, \"y\": 3291}"))
			if err != nil {
				t.Fatalf("set outcome 3 State: %v", err)
			}
			if satisfied := SetSatisfied(parameters, state); satisfied != false {
				t.Errorf("set outcome 3: satisfied = %v", satisfied)
			}
		}
		{
			parameters, _, err := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 3125, \"y\": 3291}"))
			if err != nil {
				t.Fatalf("set outcome 4 parameters: %v", err)
			}
			state, _, err := codecs.State.Decode(json.RawMessage("{\"active\": true, \"x\": 3125, \"y\": 3293}"))
			if err != nil {
				t.Fatalf("set outcome 4 State: %v", err)
			}
			if satisfied := SetSatisfied(parameters, state); satisfied != false {
				t.Errorf("set outcome 4: satisfied = %v", satisfied)
			}
		}
		{
			parameters, _, err := codecs.SetParameters.Decode(json.RawMessage("{\"x\": 3125, \"y\": 3291}"))
			if err != nil {
				t.Fatalf("set outcome 5 parameters: %v", err)
			}
			state, _, err := codecs.State.Decode(json.RawMessage("{\"active\": false, \"x\": 3125, \"y\": 3291}"))
			if err != nil {
				t.Fatalf("set outcome 5 State: %v", err)
			}
			if satisfied := SetSatisfied(parameters, state); satisfied != false {
				t.Errorf("set outcome 5: satisfied = %v", satisfied)
			}
		}
	})
}
