// Code generated by entitytypegen; DO NOT EDIT.

package colorxyv1

import (
	"time"
)

func ValidateState(support Support, state State) error {
	return nil
}

func EqualState(left, right State) bool { return left == right }

const (
	SetDeadline time.Duration = 10000 * time.Millisecond
)

func ValidateSetParameters(support Support, operationSupport SetSupport, parameters SetParameters) error {
	return nil
}

func SetSatisfied(parameters SetParameters, state State) bool {
	return (bool(state.Active)) && ((int64(parameters.X) >= int64(state.X) && int64(parameters.X)-int64(state.X) <= 1) || (int64(state.X) > int64(parameters.X) && int64(state.X)-int64(parameters.X) <= 1)) && ((int64(parameters.Y) >= int64(state.Y) && int64(parameters.Y)-int64(state.Y) <= 1) || (int64(state.Y) > int64(parameters.Y) && int64(state.Y)-int64(parameters.Y) <= 1))
}
