// Code generated by entitytypegen; DO NOT EDIT.

package colorhsv1

import (
	"time"
)

func ValidateState(support Support, state State) error {
	return nil
}

func ValidateSupport(support Support) error {
	return nil
}

func EqualState(left, right State) bool { return left == right }

const (
	SetDeadline time.Duration = 10000 * time.Millisecond
)

func ValidateSetParameters(support Support, operationSupport SetSupport, parameters SetParameters) error {
	return nil
}

func SetSatisfied(parameters SetParameters, state State) bool {
	return (bool(state.Active)) && (func() bool {
		l := int64(parameters.Hue)
		r := int64(state.Hue)
		var d int64
		if l >= r {
			d = l - r
		} else {
			d = r - l
		}
		return d <= 2 || 360-d <= 2
	}()) && ((int64(parameters.Saturation) >= int64(state.Saturation) && int64(parameters.Saturation)-int64(state.Saturation) <= 1) || (int64(state.Saturation) > int64(parameters.Saturation) && int64(state.Saturation)-int64(parameters.Saturation) <= 1))
}
