// Code generated by entitytypegen; DO NOT EDIT.

package binarysensorv1

func ValidateState(support Support, state State) error {
	return nil
}

func ValidateSupport(support Support) error {
	return nil
}

func EqualState(left, right State) bool { return left == right }

// SameSupportIdentity reports whether support fields that define an
// Entity's stable semantic identity are unchanged.
func SameSupportIdentity(previous, next Support) bool {
	return true
}
