// Code generated by entitytypegen; DO NOT EDIT.

package enumeventv1

import (
	"errors"
	"fmt"
	"sync"

	contractenumeventv1 "github.com/mholtzscher/hearth/entitytypes/enumeventv1"
	"github.com/mholtzscher/hearth/sdk/adapter"
	"github.com/mholtzscher/hearth/sdk/adapter/typed"
)

type Support = contractenumeventv1.Support
type State = contractenumeventv1.State
type StateSupport = contractenumeventv1.StateSupport
type OperationSupport = contractenumeventv1.OperationSupport
type SupportEvents = contractenumeventv1.SupportEvents

// Event-source entity types carry no State observations and no Operations;
// the facade defines only typed support and Device Event name behavior.

var (
	compileOnce  sync.Once
	sharedCodecs *contractenumeventv1.Codecs
	compileErr   error
)

func NewEntityDescriptor(metadata adapter.EntityMetadata, support Support) (adapter.EntityDescriptor, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	descriptor, err := typed.NewTypedEntityDescriptor(metadata, contractenumeventv1.TypeID, support, codecs.Support)
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	if err := contractenumeventv1.ValidateSupport(support); err != nil {
		return adapter.EntityDescriptor{}, &adapter.ValidationError{Err: fmt.Errorf("invalid Entity support: %w", err)}
	}
	return descriptor, nil
}

// DeviceEventInput carries one Device Event report for typed validation.
type DeviceEventInput struct {
	EntityID string
	Support  Support
	Name     string
}

// NewDeviceEvent validates Entity identity, Entity support, and the reported
// name, then returns the report a Session publishes.
func NewDeviceEvent(input DeviceEventInput) (adapter.DeviceEvent, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.DeviceEvent{}, err
	}
	if input.EntityID == "" {
		return adapter.DeviceEvent{}, validationError(errors.New("Device Event entity ID is required"))
	}
	if _, err := codecs.Support.Encode(input.Support); err != nil {
		return adapter.DeviceEvent{}, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	if err := contractenumeventv1.ValidateSupport(input.Support); err != nil {
		return adapter.DeviceEvent{}, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	if err := contractenumeventv1.ValidateDeviceEventName(input.Support, input.Name); err != nil {
		return adapter.DeviceEvent{}, validationError(err)
	}
	return adapter.DeviceEvent{EntityID: input.EntityID, Name: input.Name}, nil
}

func codecs() (*contractenumeventv1.Codecs, error) {
	compileOnce.Do(func() { sharedCodecs, compileErr = contractenumeventv1.Compile() })
	if compileErr != nil {
		return nil, fmt.Errorf("compile Entity-type schemas: %w", compileErr)
	}
	return sharedCodecs, nil
}

func validationError(err error) error { return &adapter.ValidationError{Err: err} }
