// Code generated by entitytypegen; DO NOT EDIT.

package colortempv1

import (
	"encoding/json"
	"errors"
	"fmt"
	"sync"
	"time"

	contractcolortempv1 "github.com/mholtzscher/hearth/entitytypes/colortempv1"
	"github.com/mholtzscher/hearth/sdk/adapter"
	"github.com/mholtzscher/hearth/sdk/adapter/typed"
)

type Support = contractcolortempv1.Support
type State = contractcolortempv1.State
type StateSupport = contractcolortempv1.StateSupport
type OperationSupport = contractcolortempv1.OperationSupport
type SetSupport = contractcolortempv1.SetSupport
type SetParameters = contractcolortempv1.SetParameters
type SetCommand = typed.Command[SetParameters]

type Handlers struct {
	Set typed.Handler[SetParameters]
}

type ObservationInput struct {
	EntityID          string
	Support           Support
	State             State
	AdapterReceivedAt time.Time
	SourceUpdatedAt   *time.Time
}

var (
	compileOnce  sync.Once
	sharedCodecs *contractcolortempv1.Codecs
	compileErr   error
)

func NewEntityDescriptor(metadata adapter.EntityMetadata, support Support) (adapter.EntityDescriptor, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	normalized, err := codecs.Support.Encode(support)
	if err != nil {
		return adapter.EntityDescriptor{}, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	return adapter.EntityDescriptor{Key: metadata.Key, ExternalID: metadata.ExternalID, Name: metadata.Name, Type: contractcolortempv1.TypeID, Support: normalized}, nil
}

func NewCommandHandler(entityID string, support Support, handlers Handlers) (adapter.CommandHandler, error) {
	codecs, err := codecs()
	if err != nil {
		return nil, err
	}
	if _, err := codecs.Support.Encode(support); err != nil {
		return nil, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	var routes []typed.Route
	if handlers.Set == nil {
		return nil, validationError(errors.New("set handler is required"))
	}
	setSupport := support.Operations.Set
	setRoute, err := typed.Operation(entityID, contractcolortempv1.OperationSet, func(raw json.RawMessage) (SetParameters, error) {
		parameters, _, err := codecs.SetParameters.Decode(raw)
		if err != nil {
			return SetParameters{}, err
		}
		if err := contractcolortempv1.ValidateSetParameters(support, setSupport, parameters); err != nil {
			return SetParameters{}, err
		}
		return parameters, nil
	}, handlers.Set)
	if err != nil {
		return nil, validationError(err)
	}
	routes = append(routes, setRoute)
	handler, err := typed.NewCommandHandler(routes...)
	if err != nil {
		return nil, validationError(err)
	}
	return handler, nil
}

func NewObservation(input ObservationInput) (adapter.Observation, error) {
	if input.EntityID == "" {
		return adapter.Observation{}, validationError(errors.New("Observation entity ID is required"))
	}
	if input.AdapterReceivedAt.IsZero() {
		return adapter.Observation{}, validationError(errors.New("Observation adapter received time is required"))
	}
	if input.SourceUpdatedAt != nil && input.SourceUpdatedAt.IsZero() {
		return adapter.Observation{}, validationError(errors.New("Observation source updated time must be non-zero"))
	}
	codecs, err := codecs()
	if err != nil {
		return adapter.Observation{}, err
	}
	if _, err := codecs.Support.Encode(input.Support); err != nil {
		return adapter.Observation{}, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	if err := contractcolortempv1.ValidateState(input.Support, input.State); err != nil {
		return adapter.Observation{}, validationError(fmt.Errorf("unsupported State: %w", err))
	}
	value, err := codecs.State.Encode(input.State)
	if err != nil {
		return adapter.Observation{}, validationError(fmt.Errorf("invalid State: %w", err))
	}
	observation := adapter.Observation{EntityID: input.EntityID, Value: value, AdapterReceivedAt: input.AdapterReceivedAt.UTC().Format(time.RFC3339Nano)}
	if input.SourceUpdatedAt != nil {
		formatted := input.SourceUpdatedAt.UTC().Format(time.RFC3339Nano)
		observation.SourceUpdatedAt = &formatted
	}
	return observation, nil
}

func codecs() (*contractcolortempv1.Codecs, error) {
	compileOnce.Do(func() { sharedCodecs, compileErr = contractcolortempv1.Compile() })
	if compileErr != nil {
		return nil, fmt.Errorf("compile Entity-type schemas: %w", compileErr)
	}
	return sharedCodecs, nil
}

func validationError(err error) error { return &adapter.ValidationError{Err: err} }
