// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbsqlc

import (
	"context"
)

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO agent_messages (conversation_id, role, message_json, created_at)
VALUES (?, ?, ?, ?)
`

type InsertMessageParams struct {
	ConversationID string
	Role           string
	MessageJson    string
	CreatedAt      string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ConversationID,
		arg.Role,
		arg.MessageJson,
		arg.CreatedAt,
	)
	return err
}

const insertMessagePair = `-- name: InsertMessagePair :exec
INSERT INTO agent_messages (conversation_id, role, message_json, created_at)
VALUES (?, ?, ?, ?), (?, ?, ?, ?)
`

type InsertMessagePairParams struct {
	ConversationID   string
	Role             string
	MessageJson      string
	CreatedAt        string
	ConversationID_2 string
	Role_2           string
	MessageJson_2    string
	CreatedAt_2      string
}

func (q *Queries) InsertMessagePair(ctx context.Context, arg InsertMessagePairParams) error {
	_, err := q.db.ExecContext(ctx, insertMessagePair,
		arg.ConversationID,
		arg.Role,
		arg.MessageJson,
		arg.CreatedAt,
		arg.ConversationID_2,
		arg.Role_2,
		arg.MessageJson_2,
		arg.CreatedAt_2,
	)
	return err
}

const listMessages = `-- name: ListMessages :many
SELECT id, role, message_json, created_at
FROM agent_messages
WHERE conversation_id = ?
ORDER BY id
`

type ListMessagesParams struct {
	ConversationID string
}

type ListMessagesRow struct {
	ID          int64
	Role        string
	MessageJson string
	CreatedAt   string
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.MessageJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessageJson = `-- name: ListRecentMessageJson :many
SELECT role, message_json
FROM agent_messages
WHERE conversation_id = ?
ORDER BY id DESC
LIMIT ?
`

type ListRecentMessageJsonParams struct {
	ConversationID string
	Limit          int64
}

type ListRecentMessageJsonRow struct {
	Role        string
	MessageJson string
}

func (q *Queries) ListRecentMessageJson(ctx context.Context, arg ListRecentMessageJsonParams) ([]ListRecentMessageJsonRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMessageJson, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMessageJsonRow
	for rows.Next() {
		var i ListRecentMessageJsonRow
		if err := rows.Scan(&i.Role, &i.MessageJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
