// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package dbsqlc

import (
	"context"
)

const deleteConversationsBefore = `-- name: DeleteConversationsBefore :execrows
DELETE FROM agent_conversations
WHERE id IN (
    SELECT c.id
    FROM agent_conversations AS c
    WHERE c.created_at < CAST(?1 AS TEXT)
      AND NOT EXISTS (
          SELECT 1 FROM agent_messages AS m
          WHERE m.conversation_id = c.id AND m.created_at >= CAST(?1 AS TEXT)
      )
    LIMIT CAST(?2 AS INTEGER)
)
`

type DeleteConversationsBeforeParams struct {
	Cutoff    string
	BatchSize int64
}

func (q *Queries) DeleteConversationsBefore(ctx context.Context, arg DeleteConversationsBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConversationsBefore, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
