// Code generated by entitytypegen; DO NOT EDIT.

package devices

import (
	"testing"
	"time"

	"github.com/mholtzscher/hearth/internal/entitytypetest"
)

func TestGeneratedBuiltinCatalogWiring(t *testing.T) {
	catalog, err := NewBuiltinTypeCatalog()
	if err != nil {
		t.Fatal(err)
	}
	t.Run("hearth.binarysensor/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_binarysensorv1"), TypeID: EntityTypeBinarysensorV1, Support: EntitySupport("{\"state\":{},\"operations\":{}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("true"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("true")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "true")
		}
		if equal, err := catalog.EqualState(entity, Value("true"), Value("true")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("false"), Value("true")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_binarysensorv1"), TypeID: EntityTypeBinarysensorV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.brightness/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_brightnessv1"), TypeID: EntityTypeBrightnessV1, Support: EntitySupport("{\"state\":{\"maximum\":80},\"operations\":{\"set\":{\"step\":5}}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{\"maximum\":80},\"operations\":{\"set\":{\"step\":5}}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{\"maximum\":80},\"operations\":{\"set\":{\"step\":5}}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("75"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("75")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "75")
		}
		if _, err := catalog.NormalizeState(entity, Value("85")); err == nil {
			t.Error("catalog support-invalid State unexpectedly accepted")
		}
		resolvedSet, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"value\":75}"))
		if err != nil {
			t.Fatalf("catalog resolve set: %v", err)
		}
		if !entitytypetest.EqualJSON(t, resolvedSet.Parameters, []byte("{\"value\":75}")) {
			t.Errorf("catalog normalized set parameters = %s, want %s", resolvedSet.Parameters, "{\"value\":75}")
		}
		if resolvedSet.Deadline != 10000*time.Millisecond {
			t.Errorf("catalog set deadline = %v, want %v", resolvedSet.Deadline, 10000*time.Millisecond)
		}
		if _, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"value\":76}")); err == nil {
			t.Error("catalog support-invalid set parameters unexpectedly accepted")
		}
		if resolvedSet.Outcome != OutcomeObserved {
			t.Errorf("catalog set outcome = %v, want %v", resolvedSet.Outcome, OutcomeObserved)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"value\":75}")}, Value("75")); err != nil || !satisfied {
			t.Errorf("catalog set satisfied outcome = %v, %v", satisfied, err)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"value\":75}")}, Value("70")); err != nil || satisfied {
			t.Errorf("catalog set unsatisfied outcome = %v, %v", satisfied, err)
		}
		if equal, err := catalog.EqualState(entity, Value("75"), Value("75")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("70"), Value("75")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_brightnessv1"), TypeID: EntityTypeBrightnessV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{\"set\":{\"step\":5}},\"state\":{\"maximum\":80}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.colorhs/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_colorhsv1"), TypeID: EntityTypeColorhsV1, Support: EntitySupport("{\"state\":{},\"operations\":{\"set\":{}}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{\"set\":{}}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{\"set\":{}}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("{\"active\":true,\"hue\":120,\"saturation\":80}"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("{\"active\":true,\"hue\":120,\"saturation\":80}")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "{\"active\":true,\"hue\":120,\"saturation\":80}")
		}
		resolvedSet, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"hue\":120,\"saturation\":80}"))
		if err != nil {
			t.Fatalf("catalog resolve set: %v", err)
		}
		if !entitytypetest.EqualJSON(t, resolvedSet.Parameters, []byte("{\"hue\":120,\"saturation\":80}")) {
			t.Errorf("catalog normalized set parameters = %s, want %s", resolvedSet.Parameters, "{\"hue\":120,\"saturation\":80}")
		}
		if resolvedSet.Deadline != 10000*time.Millisecond {
			t.Errorf("catalog set deadline = %v, want %v", resolvedSet.Deadline, 10000*time.Millisecond)
		}
		if resolvedSet.Outcome != OutcomeObserved {
			t.Errorf("catalog set outcome = %v, want %v", resolvedSet.Outcome, OutcomeObserved)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"hue\":359,\"saturation\":50}")}, Value("{\"active\":true,\"hue\":1,\"saturation\":50}")); err != nil || !satisfied {
			t.Errorf("catalog set satisfied outcome = %v, %v", satisfied, err)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"hue\":359,\"saturation\":50}")}, Value("{\"active\":true,\"hue\":2,\"saturation\":50}")); err != nil || satisfied {
			t.Errorf("catalog set unsatisfied outcome = %v, %v", satisfied, err)
		}
		if equal, err := catalog.EqualState(entity, Value("{\"active\":true,\"hue\":120,\"saturation\":80}"), Value("{\"active\":true,\"hue\":120,\"saturation\":80}")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("{\"active\":false,\"hue\":0,\"saturation\":0}"), Value("{\"active\":true,\"hue\":120,\"saturation\":80}")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_colorhsv1"), TypeID: EntityTypeColorhsV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{\"set\":{}},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.colormode/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_colormodev1"), TypeID: EntityTypeColormodeV1, Support: EntitySupport("{\"state\":{},\"operations\":{}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("\"xy\""))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("\"xy\"")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "\"xy\"")
		}
		if equal, err := catalog.EqualState(entity, Value("\"xy\""), Value("\"xy\"")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("\"hs\""), Value("\"xy\"")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_colormodev1"), TypeID: EntityTypeColormodeV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.colortemp/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_colortempv1"), TypeID: EntityTypeColortempV1, Support: EntitySupport("{\"state\":{\"minimum\":153,\"maximum\":500},\"operations\":{\"set\":{\"step\":1}}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{\"minimum\":153,\"maximum\":500},\"operations\":{\"set\":{\"step\":1}}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{\"minimum\":153,\"maximum\":500},\"operations\":{\"set\":{\"step\":1}}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("{\"active\":true,\"value\":370}"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("{\"active\":true,\"value\":370}")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "{\"active\":true,\"value\":370}")
		}
		if _, err := catalog.NormalizeState(entity, Value("{\"active\":true,\"value\":152}")); err == nil {
			t.Error("catalog support-invalid State unexpectedly accepted")
		}
		resolvedSet, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"value\":370}"))
		if err != nil {
			t.Fatalf("catalog resolve set: %v", err)
		}
		if !entitytypetest.EqualJSON(t, resolvedSet.Parameters, []byte("{\"value\":370}")) {
			t.Errorf("catalog normalized set parameters = %s, want %s", resolvedSet.Parameters, "{\"value\":370}")
		}
		if resolvedSet.Deadline != 10000*time.Millisecond {
			t.Errorf("catalog set deadline = %v, want %v", resolvedSet.Deadline, 10000*time.Millisecond)
		}
		if _, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"value\":152}")); err == nil {
			t.Error("catalog support-invalid set parameters unexpectedly accepted")
		}
		if resolvedSet.Outcome != OutcomeObserved {
			t.Errorf("catalog set outcome = %v, want %v", resolvedSet.Outcome, OutcomeObserved)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"value\":370}")}, Value("{\"active\":true,\"value\":370}")); err != nil || !satisfied {
			t.Errorf("catalog set satisfied outcome = %v, %v", satisfied, err)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"value\":370}")}, Value("{\"active\":false,\"value\":370}")); err != nil || satisfied {
			t.Errorf("catalog set unsatisfied outcome = %v, %v", satisfied, err)
		}
		if equal, err := catalog.EqualState(entity, Value("{\"active\":true,\"value\":370}"), Value("{\"active\":true,\"value\":370}")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("{\"active\":false,\"value\":370}"), Value("{\"active\":true,\"value\":370}")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_colortempv1"), TypeID: EntityTypeColortempV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{\"set\":{\"step\":1}},\"state\":{\"minimum\":153,\"maximum\":500}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.colorxy/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_colorxyv1"), TypeID: EntityTypeColorxyV1, Support: EntitySupport("{\"state\":{},\"operations\":{\"set\":{}}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{\"set\":{}}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{\"set\":{}}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("{\"active\":true,\"x\":3125,\"y\":3291}"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("{\"active\":true,\"x\":3125,\"y\":3291}")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "{\"active\":true,\"x\":3125,\"y\":3291}")
		}
		resolvedSet, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"x\":3125,\"y\":3291}"))
		if err != nil {
			t.Fatalf("catalog resolve set: %v", err)
		}
		if !entitytypetest.EqualJSON(t, resolvedSet.Parameters, []byte("{\"x\":3125,\"y\":3291}")) {
			t.Errorf("catalog normalized set parameters = %s, want %s", resolvedSet.Parameters, "{\"x\":3125,\"y\":3291}")
		}
		if resolvedSet.Deadline != 10000*time.Millisecond {
			t.Errorf("catalog set deadline = %v, want %v", resolvedSet.Deadline, 10000*time.Millisecond)
		}
		if resolvedSet.Outcome != OutcomeObserved {
			t.Errorf("catalog set outcome = %v, want %v", resolvedSet.Outcome, OutcomeObserved)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"x\":3125,\"y\":3291}")}, Value("{\"active\":true,\"x\":3125,\"y\":3291}")); err != nil || !satisfied {
			t.Errorf("catalog set satisfied outcome = %v, %v", satisfied, err)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"x\":3125,\"y\":3291}")}, Value("{\"active\":true,\"x\":3127,\"y\":3291}")); err != nil || satisfied {
			t.Errorf("catalog set unsatisfied outcome = %v, %v", satisfied, err)
		}
		if equal, err := catalog.EqualState(entity, Value("{\"active\":true,\"x\":3125,\"y\":3291}"), Value("{\"active\":true,\"x\":3125,\"y\":3291}")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("{\"active\":false,\"x\":0,\"y\":0}"), Value("{\"active\":true,\"x\":3125,\"y\":3291}")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_colorxyv1"), TypeID: EntityTypeColorxyV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{\"set\":{}},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.enumaction/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_enumactionv1"), TypeID: EntityTypeEnumactionV1, Support: EntitySupport("{\"state\":{},\"operations\":{\"trigger\":{\"values\":[\"blink\",\"breathe\",\"okay\",\"channel_change\",\"finish_effect\",\"stop_effect\"]}}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != true {
			t.Errorf("catalog stateless = %v, %v, want true", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{\"trigger\":{\"values\":[\"blink\",\"breathe\",\"okay\",\"channel_change\",\"finish_effect\",\"stop_effect\"]}}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{\"trigger\":{\"values\":[\"blink\",\"breathe\",\"okay\",\"channel_change\",\"finish_effect\",\"stop_effect\"]}}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("{}"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("{}")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "{}")
		}
		resolvedTrigger, err := catalog.ResolveCommand(entity, OperationName("trigger"), CommandParameters("{\"name\":\"blink\"}"))
		if err != nil {
			t.Fatalf("catalog resolve trigger: %v", err)
		}
		if !entitytypetest.EqualJSON(t, resolvedTrigger.Parameters, []byte("{\"name\":\"blink\"}")) {
			t.Errorf("catalog normalized trigger parameters = %s, want %s", resolvedTrigger.Parameters, "{\"name\":\"blink\"}")
		}
		if resolvedTrigger.Deadline != 10000*time.Millisecond {
			t.Errorf("catalog trigger deadline = %v, want %v", resolvedTrigger.Deadline, 10000*time.Millisecond)
		}
		if _, err := catalog.ResolveCommand(entity, OperationName("trigger"), CommandParameters("{\"name\":\"party\"}")); err == nil {
			t.Error("catalog support-invalid trigger parameters unexpectedly accepted")
		}
		if resolvedTrigger.Outcome != OutcomeDispatched {
			t.Errorf("catalog trigger outcome = %v, want %v", resolvedTrigger.Outcome, OutcomeDispatched)
		}
		if _, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("trigger"), Parameters: CommandParameters("{\"name\":\"blink\"}")}, Value("{}")); err == nil {
			t.Error("catalog trigger satisfies unexpectedly succeeded for dispatched operation")
		}
		if equal, err := catalog.EqualState(entity, Value("{}"), Value("{}")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_enumactionv1"), TypeID: EntityTypeEnumactionV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{\"trigger\":{\"values\":[\"blink\",\"breathe\",\"okay\",\"channel_change\",\"finish_effect\",\"stop_effect\"]}},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.enumevent/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_enumeventv1"), TypeID: EntityTypeEnumeventV1, Support: EntitySupport("{\"state\":{},\"operations\":{},\"events\":{\"names\":[\"single_press\",\"double_press\",\"long_press\"]}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != true {
			t.Errorf("catalog stateless = %v, %v, want true", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{},\"events\":{\"names\":[\"single_press\",\"double_press\",\"long_press\"]}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{},\"events\":{\"names\":[\"single_press\",\"double_press\",\"long_press\"]}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("{}"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("{}")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "{}")
		}
		if equal, err := catalog.EqualState(entity, Value("{}"), Value("{}")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || !supported {
			t.Errorf("catalog supported Entity Event %q = %v, %v", "single_press", supported, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("unknown")); err != nil || supported {
			t.Errorf("catalog unsupported Entity Event %q = %v, %v", "unknown", supported, err)
		}
		corruptEventEntity := Entity{ID: EntityID("generated_enumeventv1"), TypeID: EntityTypeEnumeventV1, Support: EntitySupport("{\"operations\":{},\"state\":{}}")}
		if _, err := catalog.SupportsEntityEvent(corruptEventEntity, EntityEventName("single_press")); err == nil {
			t.Error("catalog accepted a corrupt Entity Event descriptor")
		}
		if _, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters(`null`)); err == nil {
			t.Error("catalog resolved a Command for an event source")
		}
	})
	t.Run("hearth.enumsetting/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_enumsettingv1"), TypeID: EntityTypeEnumsettingV1, Support: EntitySupport("{\"state\":{\"choices\":[\"on\",\"off\",\"previous\",\"toggle\"]},\"operations\":{\"set\":{}}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{\"choices\":[\"on\",\"off\",\"previous\",\"toggle\"]},\"operations\":{\"set\":{}}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{\"choices\":[\"on\",\"off\",\"previous\",\"toggle\"]},\"operations\":{\"set\":{}}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("\"previous\""))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("\"previous\"")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "\"previous\"")
		}
		if _, err := catalog.NormalizeState(entity, Value("\"eco\"")); err == nil {
			t.Error("catalog support-invalid State unexpectedly accepted")
		}
		resolvedSet, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"value\":\"on\"}"))
		if err != nil {
			t.Fatalf("catalog resolve set: %v", err)
		}
		if !entitytypetest.EqualJSON(t, resolvedSet.Parameters, []byte("{\"value\":\"on\"}")) {
			t.Errorf("catalog normalized set parameters = %s, want %s", resolvedSet.Parameters, "{\"value\":\"on\"}")
		}
		if resolvedSet.Deadline != 10000*time.Millisecond {
			t.Errorf("catalog set deadline = %v, want %v", resolvedSet.Deadline, 10000*time.Millisecond)
		}
		if _, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"value\":\"eco\"}")); err == nil {
			t.Error("catalog support-invalid set parameters unexpectedly accepted")
		}
		if resolvedSet.Outcome != OutcomeObserved {
			t.Errorf("catalog set outcome = %v, want %v", resolvedSet.Outcome, OutcomeObserved)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"value\":\"on\"}")}, Value("\"on\"")); err != nil || !satisfied {
			t.Errorf("catalog set satisfied outcome = %v, %v", satisfied, err)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"value\":\"on\"}")}, Value("\"off\"")); err != nil || satisfied {
			t.Errorf("catalog set unsatisfied outcome = %v, %v", satisfied, err)
		}
		if equal, err := catalog.EqualState(entity, Value("\"previous\""), Value("\"previous\"")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("\"on\""), Value("\"previous\"")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_enumsettingv1"), TypeID: EntityTypeEnumsettingV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{\"set\":{}},\"state\":{\"choices\":[\"on\",\"off\",\"previous\",\"toggle\"]}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.numericsensor/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_numericsensorv1"), TypeID: EntityTypeNumericsensorV1, Support: EntitySupport("{\"state\":{\"minimum\":0,\"maximum\":255,\"unit\":\"lqi\"},\"operations\":{}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{\"minimum\":0,\"maximum\":255,\"unit\":\"lqi\"},\"operations\":{}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{\"minimum\":0,\"maximum\":255,\"unit\":\"lqi\"},\"operations\":{}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("18"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("18")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "18")
		}
		if _, err := catalog.NormalizeState(entity, Value("256")); err == nil {
			t.Error("catalog support-invalid State unexpectedly accepted")
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"state\":{\"minimum\":255,\"maximum\":0,\"unit\":\"lqi\"},\"operations\":{}}")); err == nil {
			t.Error("catalog invalid support 1 unexpectedly accepted")
		}
		if equal, err := catalog.EqualState(entity, Value("18"), Value("18")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("18.5"), Value("18")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_numericsensorv1"), TypeID: EntityTypeNumericsensorV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{},\"state\":{\"minimum\":0,\"maximum\":255,\"unit\":\"lqi\"}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.numericsetting/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_numericsettingv1"), TypeID: EntityTypeNumericsettingV1, Support: EntitySupport("{\"state\":{\"minimum\":142,\"maximum\":454,\"unit\":\"mired\",\"choices\":[\"previous\"]},\"operations\":{\"set\":{}}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{\"minimum\":142,\"maximum\":454,\"unit\":\"mired\",\"choices\":[\"previous\"]},\"operations\":{\"set\":{}}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{\"minimum\":142,\"maximum\":454,\"unit\":\"mired\",\"choices\":[\"previous\"]},\"operations\":{\"set\":{}}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("{\"mode\":\"value\",\"value\":250}"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("{\"mode\":\"value\",\"value\":250}")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "{\"mode\":\"value\",\"value\":250}")
		}
		if _, err := catalog.NormalizeState(entity, Value("{\"mode\":\"value\",\"value\":455}")); err == nil {
			t.Error("catalog support-invalid State unexpectedly accepted")
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"state\":{\"minimum\":454,\"maximum\":142,\"unit\":\"mired\",\"choices\":[\"previous\"]},\"operations\":{\"set\":{}}}")); err == nil {
			t.Error("catalog invalid support 1 unexpectedly accepted")
		}
		resolvedSet, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"mode\":\"value\",\"value\":250}"))
		if err != nil {
			t.Fatalf("catalog resolve set: %v", err)
		}
		if !entitytypetest.EqualJSON(t, resolvedSet.Parameters, []byte("{\"mode\":\"value\",\"value\":250}")) {
			t.Errorf("catalog normalized set parameters = %s, want %s", resolvedSet.Parameters, "{\"mode\":\"value\",\"value\":250}")
		}
		if resolvedSet.Deadline != 10000*time.Millisecond {
			t.Errorf("catalog set deadline = %v, want %v", resolvedSet.Deadline, 10000*time.Millisecond)
		}
		if _, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"mode\":\"value\",\"value\":455}")); err == nil {
			t.Error("catalog support-invalid set parameters unexpectedly accepted")
		}
		if resolvedSet.Outcome != OutcomeObserved {
			t.Errorf("catalog set outcome = %v, want %v", resolvedSet.Outcome, OutcomeObserved)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"mode\":\"value\",\"value\":250}")}, Value("{\"mode\":\"value\",\"value\":250}")); err != nil || !satisfied {
			t.Errorf("catalog set satisfied outcome = %v, %v", satisfied, err)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"mode\":\"value\",\"value\":250}")}, Value("{\"mode\":\"value\",\"value\":200}")); err != nil || satisfied {
			t.Errorf("catalog set unsatisfied outcome = %v, %v", satisfied, err)
		}
		if equal, err := catalog.EqualState(entity, Value("{\"mode\":\"value\",\"value\":250}"), Value("{\"mode\":\"value\",\"value\":250}")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("{\"mode\":\"value\",\"value\":250.5}"), Value("{\"mode\":\"value\",\"value\":250}")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_numericsettingv1"), TypeID: EntityTypeNumericsettingV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{\"set\":{}},\"state\":{\"minimum\":142,\"maximum\":454,\"unit\":\"mired\",\"choices\":[\"previous\"]}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.power/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_powerv1"), TypeID: EntityTypePowerV1, Support: EntitySupport("{\"state\":{},\"operations\":{\"set\":{}}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{\"set\":{}}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{\"set\":{}}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("true"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("true")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "true")
		}
		resolvedSet, err := catalog.ResolveCommand(entity, OperationName("set"), CommandParameters("{\"value\":true}"))
		if err != nil {
			t.Fatalf("catalog resolve set: %v", err)
		}
		if !entitytypetest.EqualJSON(t, resolvedSet.Parameters, []byte("{\"value\":true}")) {
			t.Errorf("catalog normalized set parameters = %s, want %s", resolvedSet.Parameters, "{\"value\":true}")
		}
		if resolvedSet.Deadline != 10000*time.Millisecond {
			t.Errorf("catalog set deadline = %v, want %v", resolvedSet.Deadline, 10000*time.Millisecond)
		}
		if resolvedSet.Outcome != OutcomeObserved {
			t.Errorf("catalog set outcome = %v, want %v", resolvedSet.Outcome, OutcomeObserved)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"value\":true}")}, Value("true")); err != nil || !satisfied {
			t.Errorf("catalog set satisfied outcome = %v, %v", satisfied, err)
		}
		if satisfied, err := catalog.Satisfies(entity, CommandRecord{OperationName: OperationName("set"), Parameters: CommandParameters("{\"value\":true}")}, Value("false")); err != nil || satisfied {
			t.Errorf("catalog set unsatisfied outcome = %v, %v", satisfied, err)
		}
		if equal, err := catalog.EqualState(entity, Value("true"), Value("true")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("false"), Value("true")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_powerv1"), TypeID: EntityTypePowerV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{\"set\":{}},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.pressure/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_pressurev1"), TypeID: EntityTypePressureV1, Support: EntitySupport("{\"state\":{},\"operations\":{}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("0"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("0")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "0")
		}
		if equal, err := catalog.EqualState(entity, Value("0"), Value("0")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("1013"), Value("0")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_pressurev1"), TypeID: EntityTypePressureV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.relativehumidity/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_relativehumidityv1"), TypeID: EntityTypeRelativehumidityV1, Support: EntitySupport("{\"state\":{},\"operations\":{}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("0"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("0")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "0")
		}
		if equal, err := catalog.EqualState(entity, Value("0"), Value("0")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("45"), Value("0")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_relativehumidityv1"), TypeID: EntityTypeRelativehumidityV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.speed/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_speedv1"), TypeID: EntityTypeSpeedV1, Support: EntitySupport("{\"state\":{},\"operations\":{}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("0"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("0")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "0")
		}
		if equal, err := catalog.EqualState(entity, Value("0"), Value("0")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("3.58"), Value("0")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_speedv1"), TypeID: EntityTypeSpeedV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
	t.Run("hearth.temperature/v1", func(t *testing.T) {
		entity := Entity{ID: EntityID("generated_temperaturev1"), TypeID: EntityTypeTemperatureV1, Support: EntitySupport("{\"state\":{},\"operations\":{}}")}
		if stateless, err := catalog.IsStateless(entity.TypeID); err != nil || stateless != false {
			t.Errorf("catalog stateless = %v, %v, want false", stateless, err)
		}
		normalizedSupport, err := catalog.NormalizeSupport(entity.TypeID, entity.Support)
		if err != nil {
			t.Fatalf("catalog support: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedSupport, []byte("{\"state\":{},\"operations\":{}}")) {
			t.Errorf("catalog normalized support = %s, want %s", normalizedSupport, "{\"state\":{},\"operations\":{}}")
		}
		normalizedState, err := catalog.NormalizeState(entity, Value("21500"))
		if err != nil {
			t.Fatalf("catalog State: %v", err)
		}
		if !entitytypetest.EqualJSON(t, normalizedState, []byte("21500")) {
			t.Errorf("catalog normalized State = %s, want %s", normalizedState, "21500")
		}
		if equal, err := catalog.EqualState(entity, Value("21500"), Value("21500")); err != nil || !equal {
			t.Errorf("catalog equal State = %v, %v", equal, err)
		}
		if equal, err := catalog.EqualState(entity, Value("-273150"), Value("21500")); err != nil || equal {
			t.Errorf("catalog unequal State = %v, %v", equal, err)
		}
		if supported, err := catalog.SupportsEntityEvent(entity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type accepted an Entity Event: %v, %v", supported, err)
		}
		malformedNonEventEntity := Entity{ID: EntityID("generated_temperaturev1"), TypeID: EntityTypeTemperatureV1, Support: EntitySupport("[]")}
		if supported, err := catalog.SupportsEntityEvent(malformedNonEventEntity, EntityEventName("single_press")); err != nil || supported {
			t.Errorf("catalog non-event type with malformed support accepted an Entity Event: %v, %v", supported, err)
		}
		if _, err := catalog.NormalizeSupport(entity.TypeID, EntitySupport("{\"events\":{\"names\":[\"single_press\"]},\"operations\":{},\"state\":{}}")); err == nil {
			t.Error("catalog accepted event support for a closed type")
		}
	})
}
