package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

var generatedPrefix = []byte("// Code generated by entitytypegen; DO NOT EDIT.\n")

func applyOutputs(root string, outputs []output, check bool) error {
	sort.Slice(outputs, func(left, right int) bool { return outputs[left].path < outputs[right].path })
	expected := make(map[string]struct{}, len(outputs))
	for _, generated := range outputs {
		absolute, err := filepath.Abs(generated.path)
		if err != nil {
			return err
		}
		if _, duplicate := expected[absolute]; duplicate {
			return fmt.Errorf("duplicate generated output %s", absolute)
		}
		expected[absolute] = struct{}{}
	}
	owned, err := ownedGeneratedFiles(root)
	if err != nil {
		return err
	}
	for _, path := range owned {
		if _, exists := expected[path]; exists {
			continue
		}
		if check {
			return fmt.Errorf("generated file %s is orphaned; run go generate ./entitytypes", path)
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	for _, generated := range outputs {
		if err := applyOutput(generated, check); err != nil {
			return err
		}
	}
	return nil
}

func ownedGeneratedFiles(root string) ([]string, error) {
	patterns := []string{
		filepath.Join(root, "entitytypes", "*", "zz_generated_*.go"),
		filepath.Join(root, "sdk", "adapter", "*", "zz_generated_*.go"),
		filepath.Join(root, "internal", "modules", "devices", "zz_generated_entitytypes*.go"),
	}
	var owned []string
	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return nil, err
		}
		for _, path := range matches {
			raw, err := os.ReadFile(path)
			if err != nil {
				return nil, err
			}
			if !bytes.HasPrefix(raw, generatedPrefix) {
				continue
			}
			absolute, err := filepath.Abs(path)
			if err != nil {
				return nil, err
			}
			owned = append(owned, absolute)
		}
	}
	sort.Strings(owned)
	return owned, nil
}
