package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"golang.org/x/tools/imports"
)

const generatedPrefix = "// Code generated by entitytypegen; DO NOT EDIT.\n"

// generatedTabWidth matches gofmt's tab width: formatting must stay
// byte-identical to what gofmt produces, and generate-check compares bytes.
const generatedTabWidth = 8

// formatGeneratedOutputs formats every collected generated output exactly once,
// in order, before applyOutputs checks or writes any of them. Both -check and
// normal generation call it, so they compare and write identical bytes.
//
// Key invariant: every collected output is a Go file, and each one is formatted
// against its own destination path. imports.Process resolves candidate imports
// relative to the destination directory and deletes unused imports, so
// renderers emit an import block without hand-tuning it and still get the
// imports their real package needs. Generated source always declares the
// imports it references, so formatting stays on Process's first pass, which
// never consults the module resolver: generation stays deterministic and
// offline even though Process shells out to `go env`.
//
// The returned slice is new and shares no backing array with outputs, so callers
// keep the unformatted content they passed in.
func formatGeneratedOutputs(outputs []output) ([]output, error) {
	formatted := make([]output, len(outputs))
	for index, generated := range outputs {
		content, err := imports.Process(generated.path, generated.content, &imports.Options{
			Comments:  true,
			TabIndent: true,
			TabWidth:  generatedTabWidth,
		})
		if err != nil {
			return nil, fmt.Errorf("format generated Go %s: %w\n%s", generated.path, err, generated.content)
		}
		formatted[index] = output{path: generated.path, content: content}
	}
	return formatted, nil
}

func applyOutputs(root string, outputs []output, check bool) error {
	sort.Slice(outputs, func(left, right int) bool { return outputs[left].path < outputs[right].path })
	expected := make(map[string]struct{}, len(outputs))
	for _, generated := range outputs {
		absolute, err := filepath.Abs(generated.path)
		if err != nil {
			return err
		}
		if _, duplicate := expected[absolute]; duplicate {
			return fmt.Errorf("duplicate generated output %s", absolute)
		}
		expected[absolute] = struct{}{}
	}
	owned, discoveryErr := ownedGeneratedFiles(root)
	if discoveryErr != nil {
		return discoveryErr
	}
	for _, path := range owned {
		if _, exists := expected[path]; exists {
			continue
		}
		if check {
			return fmt.Errorf("generated file %s is orphaned; run go generate ./entitytypes", path)
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	for _, generated := range outputs {
		if err := applyOutput(generated, check); err != nil {
			return err
		}
	}
	return nil
}

func ownedGeneratedFiles(root string) ([]string, error) {
	patterns := []string{
		filepath.Join(root, "entitytypes", "*", "zz_generated_*.go"),
		filepath.Join(root, "sdk", "adapter", "*", "zz_generated_*.go"),
		filepath.Join(root, "internal", "modules", "devices", "zz_generated_entitytypes*.go"),
	}
	var owned []string
	for _, pattern := range patterns {
		matches, globErr := filepath.Glob(pattern)
		if globErr != nil {
			return nil, globErr
		}
		for _, path := range matches {
			raw, err := os.ReadFile(path)
			if err != nil {
				return nil, err
			}
			if !bytes.HasPrefix(raw, []byte(generatedPrefix)) {
				continue
			}
			absolute, err := filepath.Abs(path)
			if err != nil {
				return nil, err
			}
			owned = append(owned, absolute)
		}
	}
	sort.Strings(owned)
	return owned, nil
}
