// Code generated by entitytypegen; DO NOT EDIT.

package speedv1

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/mholtzscher/hearth/internal/entitytypetest"
	"github.com/mholtzscher/hearth/sdk/adapter"
	"github.com/mholtzscher/hearth/sdk/adapter/adaptertest"
)

func TestGeneratedObservationConformance(t *testing.T) {
	codecs, err := codecs()
	if err != nil {
		t.Fatal(err)
	}
	t.Run("metres-per-second-envelope", func(t *testing.T) {
		support, _, err := codecs.Support.Decode(json.RawMessage("{\"state\": {}, \"operations\": {}}"))
		if err != nil {
			t.Fatalf("support: %v", err)
		}
		{
			raw := json.RawMessage("0")
			state, _, codecErr := codecs.State.Decode(raw)
			if codecErr != nil {
				t.Errorf("State example 1 marked valid but rejected by State codec: %v", codecErr)
			}
			if codecErr == nil {
				if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr != nil {
					t.Errorf("State example 1 marked valid but rejected by Observation constructor: %v", observationErr)
				}
			}
		}
		{
			raw := json.RawMessage("3.58")
			state, _, codecErr := codecs.State.Decode(raw)
			if codecErr != nil {
				t.Errorf("State example 2 marked valid but rejected by State codec: %v", codecErr)
			}
			if codecErr == nil {
				if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr != nil {
					t.Errorf("State example 2 marked valid but rejected by Observation constructor: %v", observationErr)
				}
			}
		}
		{
			raw := json.RawMessage("0.44704")
			state, _, codecErr := codecs.State.Decode(raw)
			if codecErr != nil {
				t.Errorf("State example 3 marked valid but rejected by State codec: %v", codecErr)
			}
			if codecErr == nil {
				if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr != nil {
					t.Errorf("State example 3 marked valid but rejected by Observation constructor: %v", observationErr)
				}
			}
		}
		{
			raw := json.RawMessage("199.999")
			state, _, codecErr := codecs.State.Decode(raw)
			if codecErr != nil {
				t.Errorf("State example 4 marked valid but rejected by State codec: %v", codecErr)
			}
			if codecErr == nil {
				if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr != nil {
					t.Errorf("State example 4 marked valid but rejected by Observation constructor: %v", observationErr)
				}
			}
		}
		{
			raw := json.RawMessage("200")
			state, _, codecErr := codecs.State.Decode(raw)
			if codecErr != nil {
				t.Errorf("State example 5 marked valid but rejected by State codec: %v", codecErr)
			}
			if codecErr == nil {
				if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr != nil {
					t.Errorf("State example 5 marked valid but rejected by Observation constructor: %v", observationErr)
				}
			}
		}
		{
			raw := json.RawMessage("-0.001")
			state, _, codecErr := codecs.State.Decode(raw)
			var plainState State
			plainErr := json.Unmarshal(raw, &plainState)
			if codecErr == nil {
				if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr == nil {
					t.Errorf("State example 6 marked invalid was accepted by Observation constructor")
				} else {
					adaptertest.RequireValidationError(t, observationErr, "reject support-incompatible State")
				}
			} else if plainErr == nil {
				// Schema-invalid but Go-representable values must reach the
				// Observation constructor through ordinary JSON and be
				// rejected there. Wire-only values that Go cannot represent
				// stay in contract-test territory. Ordinary JSON construction
				// may drop authored invalidity (a missing required field
				// becomes a valid zero-filled field); only inputs that survive
				// an ordinary JSON roundtrip carry a constructor claim, judged
				// without production validation.
				if entitytypetest.CanonicalValue(t, plainState) == entitytypetest.CanonicalJSON(t, raw) {
					if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: plainState, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr == nil {
						t.Errorf("typed-invalid State example 6 was accepted by Observation constructor")
					} else {
						adaptertest.RequireValidationError(t, observationErr, "reject typed-invalid State")
					}
				}
			}
		}
		{
			raw := json.RawMessage("200.001")
			state, _, codecErr := codecs.State.Decode(raw)
			var plainState State
			plainErr := json.Unmarshal(raw, &plainState)
			if codecErr == nil {
				if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr == nil {
					t.Errorf("State example 7 marked invalid was accepted by Observation constructor")
				} else {
					adaptertest.RequireValidationError(t, observationErr, "reject support-incompatible State")
				}
			} else if plainErr == nil {
				// Schema-invalid but Go-representable values must reach the
				// Observation constructor through ordinary JSON and be
				// rejected there. Wire-only values that Go cannot represent
				// stay in contract-test territory. Ordinary JSON construction
				// may drop authored invalidity (a missing required field
				// becomes a valid zero-filled field); only inputs that survive
				// an ordinary JSON roundtrip carry a constructor claim, judged
				// without production validation.
				if entitytypetest.CanonicalValue(t, plainState) == entitytypetest.CanonicalJSON(t, raw) {
					if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: plainState, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr == nil {
						t.Errorf("typed-invalid State example 7 was accepted by Observation constructor")
					} else {
						adaptertest.RequireValidationError(t, observationErr, "reject typed-invalid State")
					}
				}
			}
		}
		{
			raw := json.RawMessage("\"3.58\"")
			state, _, codecErr := codecs.State.Decode(raw)
			var plainState State
			plainErr := json.Unmarshal(raw, &plainState)
			if codecErr == nil {
				if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr == nil {
					t.Errorf("State example 8 marked invalid was accepted by Observation constructor")
				} else {
					adaptertest.RequireValidationError(t, observationErr, "reject support-incompatible State")
				}
			} else if plainErr == nil {
				// Schema-invalid but Go-representable values must reach the
				// Observation constructor through ordinary JSON and be
				// rejected there. Wire-only values that Go cannot represent
				// stay in contract-test territory. Ordinary JSON construction
				// may drop authored invalidity (a missing required field
				// becomes a valid zero-filled field); only inputs that survive
				// an ordinary JSON roundtrip carry a constructor claim, judged
				// without production validation.
				if entitytypetest.CanonicalValue(t, plainState) == entitytypetest.CanonicalJSON(t, raw) {
					if _, observationErr := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: plainState, AdapterReceivedAt: time.Unix(0, 0).UTC()}); observationErr == nil {
						t.Errorf("typed-invalid State example 8 was accepted by Observation constructor")
					} else {
						adaptertest.RequireValidationError(t, observationErr, "reject typed-invalid State")
					}
				}
			}
		}
	})
}

func TestGeneratedObservationMetadata(t *testing.T) {
	codecs, err := codecs()
	if err != nil {
		t.Fatal(err)
	}
	support, _, err := codecs.Support.Decode(json.RawMessage("{\"state\": {}, \"operations\": {}}"))
	if err != nil {
		t.Fatalf("support: %v", err)
	}
	state, _, err := codecs.State.Decode(json.RawMessage("0"))
	if err != nil {
		t.Fatalf("State: %v", err)
	}
	receivedAt := time.Date(2026, time.March, 10, 14, 30, 0,
		123456789, time.FixedZone("CET", 3600))
	observation, err := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: receivedAt})
	if err != nil {
		t.Fatalf("observation: %v", err)
	}
	if observation.EntityID != "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab" {
		t.Errorf("observation entity ID = %q", observation.EntityID)
	}
	if entitytypetest.CanonicalJSON(t, observation.Value) != entitytypetest.CanonicalJSON(t, json.RawMessage("0")) {
		t.Errorf("observation value = %s", observation.Value)
	}
	if received := adaptertest.ParseAdapterTime(t, "adapter received time", observation.AdapterReceivedAt); !received.Equal(receivedAt) {
		t.Errorf("adapter received time = %s, want %s", observation.AdapterReceivedAt, receivedAt.UTC().Format(time.RFC3339Nano))
	}
	if observation.SourceUpdatedAt != nil {
		t.Errorf("observation without source time carries SourceUpdatedAt = %s", *observation.SourceUpdatedAt)
	}
	sourceAt := time.Date(2026, time.March, 9, 8, 15, 30, 0, time.FixedZone("EST", -5*3600))
	sourced, err := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: receivedAt, SourceUpdatedAt: &sourceAt})
	if err != nil {
		t.Fatalf("sourced observation: %v", err)
	}
	if sourced.SourceUpdatedAt == nil {
		t.Fatal("observation with source time has no SourceUpdatedAt")
	}
	if updated := adaptertest.ParseAdapterTime(t, "source updated time", *sourced.SourceUpdatedAt); !updated.Equal(sourceAt) {
		t.Errorf("source updated time = %s, want %s", *sourced.SourceUpdatedAt, sourceAt.UTC().Format(time.RFC3339Nano))
	}
}

func TestGeneratedObservationValidation(t *testing.T) {
	codecs, err := codecs()
	if err != nil {
		t.Fatal(err)
	}
	support, _, err := codecs.Support.Decode(json.RawMessage("{\"state\": {}, \"operations\": {}}"))
	if err != nil {
		t.Fatalf("support: %v", err)
	}
	state, _, err := codecs.State.Decode(json.RawMessage("0"))
	if err != nil {
		t.Fatalf("State: %v", err)
	}
	receivedAt := time.Date(2026, time.March, 10, 14, 30, 0, 0, time.UTC)
	if _, err := NewObservation(ObservationInput{Support: support, State: state, AdapterReceivedAt: receivedAt}); err == nil {
		t.Error("Observation without entity ID was accepted")
	} else {
		adaptertest.RequireValidationError(t, err, "reject empty entity ID")
	}
	if _, err := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state}); err == nil {
		t.Error("Observation without adapter received time was accepted")
	} else {
		adaptertest.RequireValidationError(t, err, "reject zero adapter received time")
	}
	zeroSource := time.Time{}
	if _, err := NewObservation(ObservationInput{EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", Support: support, State: state, AdapterReceivedAt: receivedAt, SourceUpdatedAt: &zeroSource}); err == nil {
		t.Error("Observation with zero source updated time was accepted")
	} else {
		adaptertest.RequireValidationError(t, err, "reject zero source updated time")
	}
}

func TestGeneratedEntityDescriptor(t *testing.T) {
	codecs, err := codecs()
	if err != nil {
		t.Fatal(err)
	}
	support, _, err := codecs.Support.Decode(json.RawMessage("{\"state\": {}, \"operations\": {}}"))
	if err != nil {
		t.Fatalf("support: %v", err)
	}
	metadata := adapter.EntityMetadata{Key: "key_01890f47-7a6b-7c4d-8e9f-0123456789ab", ExternalID: "ext-001", Name: "generated entity"}
	descriptor, err := NewEntityDescriptor(metadata, support)
	if err != nil {
		t.Fatalf("descriptor: %v", err)
	}
	if descriptor.Key != metadata.Key {
		t.Errorf("descriptor key = %q", descriptor.Key)
	}
	if descriptor.ExternalID != metadata.ExternalID {
		t.Errorf("descriptor external ID = %q", descriptor.ExternalID)
	}
	if descriptor.Name != metadata.Name {
		t.Errorf("descriptor name = %q", descriptor.Name)
	}
	if descriptor.Type != "hearth.speed/v1" {
		t.Errorf("descriptor type = %q", descriptor.Type)
	}
	if entitytypetest.CanonicalJSON(t, descriptor.Support) != entitytypetest.CanonicalJSON(t, json.RawMessage("{\"state\": {}, \"operations\": {}}")) {
		t.Errorf("descriptor support = %s", descriptor.Support)
	}
}
