// Code generated by entitytypegen; DO NOT EDIT.

package enumeventv1

import (
	_ "embed"
	"encoding/json"
	"testing"

	"github.com/mholtzscher/hearth/internal/entitytypetest"
)

//go:embed "examples.json"
var examplesJSON []byte

func TestGeneratedConformance(t *testing.T) {
	codecs, err := Compile()
	if err != nil {
		t.Fatal(err)
	}
	entitytypetest.RunContractExamples(t, examplesJSON, entitytypetest.ContractProbe{
		ValidateSupport: func(support json.RawMessage) error {
			decodedSupport, _, err := codecs.Support.Decode(support)
			if err != nil {
				return err
			}
			return ValidateSupport(decodedSupport)
		},
		ValidateState: func(support, state json.RawMessage) error {
			decodedSupport, _, err := codecs.Support.Decode(support)
			if err != nil {
				return err
			}
			decodedState, _, err := codecs.State.Decode(state)
			if err != nil {
				return err
			}
			return ValidateState(decodedSupport, decodedState)
		},
		Operations: nil,
	})
}

func TestGeneratedEntityEventNames(t *testing.T) {
	codecs, err := Compile()
	if err != nil {
		t.Fatal(err)
	}
	support, _, err := codecs.Support.Decode(json.RawMessage("{\n        \"state\": {},\n        \"operations\": {},\n        \"events\": {\"names\": [\"single_press\", \"double_press\", \"long_press\"]}\n      }"))
	if err != nil {
		t.Fatalf("support: %v", err)
	}
	names := EntityEventNames(support)
	if len(names) != 3 {
		t.Fatalf("Entity Event names = %v", names)
	}
	if names[0] != "single_press" {
		t.Errorf("Entity Event name = %q, want %q", names[0], "single_press")
	}
	if names[1] != "double_press" {
		t.Errorf("Entity Event name = %q, want %q", names[1], "double_press")
	}
	if names[2] != "long_press" {
		t.Errorf("Entity Event name = %q, want %q", names[2], "long_press")
	}
	if err := ValidateEntityEventName(support, "single_press"); err != nil {
		t.Errorf("supported Entity Event name rejected: %v", err)
	}
	if err := ValidateEntityEventName(support, "unknown"); err == nil {
		t.Error("unsupported Entity Event name was accepted")
	}
	if err := ValidateEntityEventName(support, "not a name"); err == nil {
		t.Error("non-canonical Entity Event name was accepted")
	}
	names[0] = "mutated"
	if got := EntityEventNames(support); got[0] != "single_press" {
		t.Errorf("EntityEventNames returned a shared slice: %v", got)
	}
}
