// Code generated by entitytypegen; DO NOT EDIT.

// Package enumeventv1 provides schemas, behavior, and Go bindings for hearth.enumevent/v1.
package enumeventv1

const TypeID = "hearth.enumevent/v1"

type State struct {
}

type StateSupport struct {
}

type OperationSupport struct {
}

type SupportEventsNames []string

type SupportEvents struct {
	Names SupportEventsNames `json:"names"`
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
	Events     SupportEvents    `json:"events"`
}
