// Code generated by entitytypegen; DO NOT EDIT.

package enumeventv1

import (
	"fmt"
	"regexp"
)

func ValidateState(support Support, state State) error {
	return nil
}

func ValidateSupport(support Support) error {
	return nil
}

func EqualState(left, right State) bool { return left == right }

// SameSupportIdentity reports whether support fields that define an
// Entity's stable semantic identity are unchanged.
func SameSupportIdentity(previous, next Support) bool {
	return true
}

var entityEventNamePattern = regexp.MustCompile("^[a-z0-9][a-z0-9_-]{0,62}$")

// EntityEventNames returns an owned copy of the support's supported Entity Event names.
func EntityEventNames(support Support) []string {
	names := make([]string, 0, len(support.Events.Names))
	return append(names, support.Events.Names...)
}

// ValidateEntityEventName reports whether name is a canonical Entity Event name
// that the Entity's current support accepts.
func ValidateEntityEventName(support Support, name string) error {
	if !entityEventNamePattern.MatchString(name) {
		return fmt.Errorf("Entity Event name %q is not a canonical name slug", name)
	}
	for _, supported := range support.Events.Names {
		if supported == name {
			return nil
		}
	}
	return fmt.Errorf("Entity Event name %q is not supported", name)
}
