// Code generated by entitytypegen; DO NOT EDIT.

package enumeventv1

import (
	"embed"
	"encoding/json"
	"fmt"
	"sync"

	"github.com/mholtzscher/hearth/entitytypes"
)

const (
	StateSchemaID   = "urn:hearth:schema:entity-type:enumevent:v1:state"
	SupportSchemaID = "urn:hearth:schema:entity-type:enumevent:v1:support"
)

// FS contains the authoritative Entity-type JSON Schemas.
//
//go:embed "state.schema.json" "support.schema.json"
var FS embed.FS

func SchemaFiles() map[string]string {
	return map[string]string{
		StateSchemaID:   "state.schema.json",
		SupportSchemaID: "support.schema.json",
	}
}

type Codecs struct {
	State   *entitytypes.JSONCodec[State]
	Support *entitytypes.JSONCodec[Support]
}

//nolint:gochecknoglobals // Only this package's immutable embedded schemas are compiled once.
var sharedCodecs = sync.OnceValues(compileCodecs)

func Compile() (*Codecs, error) {
	shared, err := sharedCodecs()
	if err != nil {
		return nil, err
	}
	return &Codecs{State: cloneCodec(shared.State), Support: cloneCodec(shared.Support)}, nil
}

func cloneCodec[T any](codec *entitytypes.JSONCodec[T]) *entitytypes.JSONCodec[T] {
	clone := *codec
	return &clone
}

func compileCodecs() (*Codecs, error) {
	state, err := compileCodec[State](StateSchemaID, SchemaFiles()[StateSchemaID])
	if err != nil {
		return nil, err
	}
	support, err := compileCodec[Support](SupportSchemaID, SchemaFiles()[SupportSchemaID])
	if err != nil {
		return nil, err
	}
	return &Codecs{State: state, Support: support}, nil
}

func compileCodec[T any](schemaID, path string) (*entitytypes.JSONCodec[T], error) {
	raw, err := FS.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	return entitytypes.CompileJSONCodec[T](schemaID, json.RawMessage(raw), nil)
}
