// Code generated by entitytypegen; DO NOT EDIT.

package powerv1

import (
	"time"
)

func ValidateState(support Support, state State) error {
	return nil
}

func EqualState(left, right State) bool { return left == right }

const (
	SetDeadline time.Duration = 10000 * time.Millisecond
)

func ValidateSetParameters(support Support, operationSupport SetSupport, parameters SetParameters) error {
	return nil
}

func SetSatisfied(parameters SetParameters, state State) bool {
	return (bool(parameters.Value) == bool(state))
}
