// Code generated by entitytypegen; DO NOT EDIT.

package measurementv1

import (
	_ "embed"
	"encoding/json"
	"testing"

	"github.com/mholtzscher/hearth/internal/entitytypetest"
)

//go:embed "examples.json"
var examplesJSON []byte

func TestGeneratedConformance(t *testing.T) {
	codecs, err := Compile()
	if err != nil {
		t.Fatal(err)
	}
	entitytypetest.RunContractExamples(t, examplesJSON, entitytypetest.ContractProbe{
		ValidateSupport: func(support json.RawMessage) error {
			decodedSupport, _, err := codecs.Support.Decode(support)
			if err != nil {
				return err
			}
			return ValidateSupport(decodedSupport)
		},
		ValidateState: func(support, state json.RawMessage) error {
			decodedSupport, _, err := codecs.Support.Decode(support)
			if err != nil {
				return err
			}
			decodedState, _, err := codecs.State.Decode(state)
			if err != nil {
				return err
			}
			return ValidateState(decodedSupport, decodedState)
		},
		Operations: nil,
	})
	invalidSupport1, _, err := codecs.Support.Decode(json.RawMessage("{\"state\":{\"measurement_kind\":\"temperature\",\"unit\":\"Cel\",\"minimum\":1000,\"maximum\":-273.15},\"operations\":{}}"))
	if err != nil {
		t.Fatalf("invalid support 1 is not schema-decodable: %v", err)
	}
	if err := ValidateSupport(invalidSupport1); err == nil {
		t.Error("invalid support 1 was accepted")
	}
	invalidSupport2, _, err := codecs.Support.Decode(json.RawMessage("{\"state\":{\"measurement_kind\":\"relative_humidity\",\"unit\":\"%\",\"minimum\":100,\"maximum\":0},\"operations\":{}}"))
	if err != nil {
		t.Fatalf("invalid support 2 is not schema-decodable: %v", err)
	}
	if err := ValidateSupport(invalidSupport2); err == nil {
		t.Error("invalid support 2 was accepted")
	}
	invalidSupport3, _, err := codecs.Support.Decode(json.RawMessage("{\"state\":{\"measurement_kind\":\"illuminance\",\"unit\":\"lx\",\"minimum\":1000000000,\"maximum\":0},\"operations\":{}}"))
	if err != nil {
		t.Fatalf("invalid support 3 is not schema-decodable: %v", err)
	}
	if err := ValidateSupport(invalidSupport3); err == nil {
		t.Error("invalid support 3 was accepted")
	}
	invalidSupport4, _, err := codecs.Support.Decode(json.RawMessage("{\"state\":{\"measurement_kind\":\"battery_level\",\"unit\":\"%\",\"minimum\":100,\"maximum\":0},\"operations\":{}}"))
	if err != nil {
		t.Fatalf("invalid support 4 is not schema-decodable: %v", err)
	}
	if err := ValidateSupport(invalidSupport4); err == nil {
		t.Error("invalid support 4 was accepted")
	}
}
