// Code generated by entitytypegen; DO NOT EDIT.

// Package measurementv1 provides schemas, behavior, and Go bindings for hearth.measurement/v1.
package measurementv1

const TypeID = "hearth.measurement/v1"

type State float64

type StateSupport struct {
	Maximum         float64 `json:"maximum"`
	MeasurementKind string  `json:"measurement_kind"`
	Minimum         float64 `json:"minimum"`
	Unit            string  `json:"unit"`
}

type OperationSupport struct {
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}
