// Code generated by entitytypegen; DO NOT EDIT.

// Package colortempv1 provides schemas, behavior, and Go bindings for hearth.colortemp/v1.
package colortempv1

const TypeID = "hearth.colortemp/v1"

const (
	OperationSet = "set"
)

type State struct {
	Active bool  `json:"active"`
	Value  int64 `json:"value"`
}

type StateSupport struct {
	Maximum int64 `json:"maximum"`
	Minimum int64 `json:"minimum"`
}

type SetSupport struct {
	Step int64 `json:"step"`
}

type OperationSupport struct {
	Set SetSupport `json:"set"`
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}

type SetParameters struct {
	Value int64 `json:"value"`
}
