// Code generated by entitytypegen; DO NOT EDIT.

package colorxyv1

import (
	"encoding/json"
	"errors"
	"fmt"
	"sync"
	"time"

	contractcolorxyv1 "github.com/mholtzscher/hearth/entitytypes/colorxyv1"
	"github.com/mholtzscher/hearth/sdk/adapter"
	"github.com/mholtzscher/hearth/sdk/adapter/typed"
)

type Support = contractcolorxyv1.Support
type State = contractcolorxyv1.State
type StateSupport = contractcolorxyv1.StateSupport
type OperationSupport = contractcolorxyv1.OperationSupport
type SetSupport = contractcolorxyv1.SetSupport
type SetParameters = contractcolorxyv1.SetParameters
type SetCommand = typed.Command[SetParameters]

type Handlers struct {
	Set typed.Handler[SetParameters]
}

type ObservationInput struct {
	EntityID          string
	Support           Support
	State             State
	AdapterReceivedAt time.Time
	SourceUpdatedAt   *time.Time
}

var (
	compileOnce  sync.Once
	sharedCodecs *contractcolorxyv1.Codecs
	compileErr   error
)

func NewEntityDescriptor(metadata adapter.EntityMetadata, support Support) (adapter.EntityDescriptor, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	descriptor, err := typed.NewTypedEntityDescriptor(metadata, contractcolorxyv1.TypeID, support, codecs.Support)
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	if err := contractcolorxyv1.ValidateSupport(support); err != nil {
		return adapter.EntityDescriptor{}, &adapter.ValidationError{Err: fmt.Errorf("invalid Entity support: %w", err)}
	}
	return descriptor, nil
}

func NewCommandHandler(entityID string, support Support, handlers Handlers) (adapter.CommandHandler, error) {
	codecs, err := codecs()
	if err != nil {
		return nil, err
	}
	if _, err := codecs.Support.Encode(support); err != nil {
		return nil, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	if err := contractcolorxyv1.ValidateSupport(support); err != nil {
		return nil, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	var routes []typed.Route
	if handlers.Set == nil {
		return nil, validationError(errors.New("set handler is required"))
	}
	setSupport := support.Operations.Set
	setRoute, err := typed.Operation(entityID, contractcolorxyv1.OperationSet, func(raw json.RawMessage) (SetParameters, error) {
		parameters, _, err := codecs.SetParameters.Decode(raw)
		if err != nil {
			return SetParameters{}, err
		}
		if err := contractcolorxyv1.ValidateSetParameters(support, setSupport, parameters); err != nil {
			return SetParameters{}, err
		}
		return parameters, nil
	}, handlers.Set)
	if err != nil {
		return nil, validationError(err)
	}
	routes = append(routes, setRoute)
	handler, err := typed.NewCommandHandler(routes...)
	if err != nil {
		return nil, validationError(err)
	}
	return handler, nil
}

func NewObservation(input ObservationInput) (adapter.Observation, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.Observation{}, err
	}
	return typed.NewTypedEntityObservation(typed.EntityObservationInput[State, Support]{EntityID: input.EntityID, Support: input.Support, State: input.State, AdapterReceivedAt: input.AdapterReceivedAt, SourceUpdatedAt: input.SourceUpdatedAt}, codecs.State, codecs.Support, contractcolorxyv1.ValidateState)
}

func codecs() (*contractcolorxyv1.Codecs, error) {
	compileOnce.Do(func() { sharedCodecs, compileErr = contractcolorxyv1.Compile() })
	if compileErr != nil {
		return nil, fmt.Errorf("compile Entity-type schemas: %w", compileErr)
	}
	return sharedCodecs, nil
}

func validationError(err error) error { return &adapter.ValidationError{Err: err} }
