// Code generated by entitytypegen; DO NOT EDIT.

package numericsensorv1

import (
	_ "embed"
	"encoding/json"
	"testing"

	"github.com/mholtzscher/hearth/internal/entitytypetest"
)

//go:embed "examples.json"
var examplesJSON []byte

func TestGeneratedConformance(t *testing.T) {
	codecs, err := Compile()
	if err != nil {
		t.Fatal(err)
	}
	entitytypetest.RunContractExamples(t, examplesJSON, entitytypetest.ContractProbe{
		ValidateSupport: func(support json.RawMessage) error {
			decodedSupport, _, err := codecs.Support.Decode(support)
			if err != nil {
				return err
			}
			return ValidateSupport(decodedSupport)
		},
		ValidateState: func(support, state json.RawMessage) error {
			decodedSupport, _, err := codecs.Support.Decode(support)
			if err != nil {
				return err
			}
			decodedState, _, err := codecs.State.Decode(state)
			if err != nil {
				return err
			}
			return ValidateState(decodedSupport, decodedState)
		},
		Operations: nil,
	})
	invalidSupport1, _, err := codecs.Support.Decode(json.RawMessage("{\"state\":{\"minimum\":255,\"maximum\":0,\"unit\":\"lqi\"},\"operations\":{}}"))
	if err != nil {
		t.Fatalf("invalid support 1 is not schema-decodable: %v", err)
	}
	if err := ValidateSupport(invalidSupport1); err == nil {
		t.Error("invalid support 1 was accepted")
	}
}
