// Code generated by entitytypegen; DO NOT EDIT.

// Package numericsensorv1 provides schemas, behavior, and Go bindings for hearth.numericsensor/v1.
package numericsensorv1

const TypeID = "hearth.numericsensor/v1"

type State float64

type StateSupport struct {
	Maximum float64 `json:"maximum"`
	Minimum float64 `json:"minimum"`
	Unit    string  `json:"unit"`
}

type OperationSupport struct {
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}
