// Code generated by entitytypegen; DO NOT EDIT.

package numericsensorv1

import (
	"errors"
)

func ValidateState(support Support, state State) error {
	if !(float64(state) >= float64(support.State.Minimum)) {
		return errors.New("state must be greater than or equal to support/state/minimum")
	}
	if !(float64(state) <= float64(support.State.Maximum)) {
		return errors.New("state must be less than or equal to support/state/maximum")
	}
	return nil
}

func ValidateSupport(support Support) error {
	if !(float64(support.State.Maximum) >= float64(support.State.Minimum)) {
		return errors.New("support/state/maximum must be greater than or equal to support/state/minimum")
	}
	return nil
}

func EqualState(left, right State) bool { return left == right }
