// Code generated by entitytypegen; DO NOT EDIT.

package temperaturev1

import (
	"fmt"
	"sync"
	"time"

	contracttemperaturev1 "github.com/mholtzscher/hearth/entitytypes/temperaturev1"
	"github.com/mholtzscher/hearth/sdk/adapter"
	"github.com/mholtzscher/hearth/sdk/adapter/typed"
)

type Support = contracttemperaturev1.Support
type State = contracttemperaturev1.State
type StateSupport = contracttemperaturev1.StateSupport
type OperationSupport = contracttemperaturev1.OperationSupport

type ObservationInput struct {
	EntityID          string
	Support           Support
	State             State
	AdapterReceivedAt time.Time
	SourceUpdatedAt   *time.Time
}

var (
	compileOnce  sync.Once
	sharedCodecs *contracttemperaturev1.Codecs
	compileErr   error
)

func NewEntityDescriptor(metadata adapter.EntityMetadata, support Support) (adapter.EntityDescriptor, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	return typed.NewTypedEntityDescriptor(metadata, contracttemperaturev1.TypeID, support, codecs.Support)
}

func NewObservation(input ObservationInput) (adapter.Observation, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.Observation{}, err
	}
	return typed.NewTypedEntityObservation(typed.EntityObservationInput[State, Support]{EntityID: input.EntityID, Support: input.Support, State: input.State, AdapterReceivedAt: input.AdapterReceivedAt, SourceUpdatedAt: input.SourceUpdatedAt}, codecs.State, codecs.Support, contracttemperaturev1.ValidateState)
}

func codecs() (*contracttemperaturev1.Codecs, error) {
	compileOnce.Do(func() { sharedCodecs, compileErr = contracttemperaturev1.Compile() })
	if compileErr != nil {
		return nil, fmt.Errorf("compile Entity-type schemas: %w", compileErr)
	}
	return sharedCodecs, nil
}
