// Code generated by entitytypegen; DO NOT EDIT.

// Package brightnessv1 provides schemas, behavior, and Go bindings for hearth.brightness/v1.
package brightnessv1

const TypeID = "hearth.brightness/v1"

const (
	OperationSet = "set"
)

type State int64

type StateSupport struct {
	Maximum int64 `json:"maximum"`
}

type SetSupport struct {
	Step int64 `json:"step"`
}

type OperationSupport struct {
	Set SetSupport `json:"set"`
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}

type SetParameters struct {
	Value int64 `json:"value"`
}
