// Code generated by entitytypegen; DO NOT EDIT.

package brightnessv1

import (
	"encoding/json"
	"testing"
)

func TestGeneratedConformance(t *testing.T) {
	codecs, err := Compile()
	if err != nil {
		t.Fatal(err)
	}
	t.Run("maximum-80-step-5", func(t *testing.T) {
		support, _, err := codecs.Support.Decode(json.RawMessage("{\n        \"state\": {\"maximum\": 80},\n        \"operations\": {\"set\": {\"step\": 5}}\n      }"))
		if err != nil {
			t.Fatalf("support: %v", err)
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("75"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != true {
				t.Errorf("state example 1: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("85"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != false {
				t.Errorf("state example 2: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("101"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != false {
				t.Errorf("state example 3: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		setSupport := support.Operations.Set
		{
			value, _, decodeErr := codecs.SetParameters.Decode(json.RawMessage("{\"value\": 75}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateSetParameters(support, setSupport, value) == nil
			}
			if valid != true {
				t.Errorf("set parameter example 1: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.SetParameters.Decode(json.RawMessage("{\"value\": 76}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateSetParameters(support, setSupport, value) == nil
			}
			if valid != false {
				t.Errorf("set parameter example 2: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.SetParameters.Decode(json.RawMessage("{\"value\": 85}"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateSetParameters(support, setSupport, value) == nil
			}
			if valid != false {
				t.Errorf("set parameter example 3: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			parameters, _, err := codecs.SetParameters.Decode(json.RawMessage("{\"value\": 75}"))
			if err != nil {
				t.Fatalf("set outcome 1 parameters: %v", err)
			}
			state, _, err := codecs.State.Decode(json.RawMessage("75"))
			if err != nil {
				t.Fatalf("set outcome 1 State: %v", err)
			}
			if satisfied := SetSatisfied(parameters, state); satisfied != true {
				t.Errorf("set outcome 1: satisfied = %v", satisfied)
			}
		}
		{
			parameters, _, err := codecs.SetParameters.Decode(json.RawMessage("{\"value\": 75}"))
			if err != nil {
				t.Fatalf("set outcome 2 parameters: %v", err)
			}
			state, _, err := codecs.State.Decode(json.RawMessage("70"))
			if err != nil {
				t.Fatalf("set outcome 2 State: %v", err)
			}
			if satisfied := SetSatisfied(parameters, state); satisfied != false {
				t.Errorf("set outcome 2: satisfied = %v", satisfied)
			}
		}
		{
			parameters, _, err := codecs.SetParameters.Decode(json.RawMessage("{\"value\": 85}"))
			if err != nil {
				t.Fatalf("set outcome 3 parameters: %v", err)
			}
			state, _, err := codecs.State.Decode(json.RawMessage("85"))
			if err != nil {
				t.Fatalf("set outcome 3 State: %v", err)
			}
			if satisfied := SetSatisfied(parameters, state); satisfied != true {
				t.Errorf("set outcome 3: satisfied = %v", satisfied)
			}
		}
	})
}
