// Code generated by entitytypegen; DO NOT EDIT.

// Package temperaturev1 provides schemas, behavior, and Go bindings for hearth.temperature/v1.
package temperaturev1

const TypeID = "hearth.temperature/v1"

type State int64

type StateSupport struct {
	Unit string `json:"unit"`
}

type OperationSupport struct {
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}
