// Code generated by entitytypegen; DO NOT EDIT.

package numericsettingv1

import (
	"errors"
	"reflect"
	"time"
)

func ValidateState(support Support, state State) error {
	if !(state.Value == nil || float64(*state.Value) >= float64(support.State.Minimum)) {
		return errors.New("state/value must be absent or greater than or equal to support/state/minimum")
	}
	if !(state.Value == nil || float64(*state.Value) <= float64(support.State.Maximum)) {
		return errors.New("state/value must be absent or less than or equal to support/state/maximum")
	}
	if !(state.Choice == nil || (func() bool {
		for _, candidate := range support.State.Choices {
			if string(*state.Choice) == string(candidate) {
				return true
			}
		}
		return false
	}())) {
		return errors.New("state/choice must be absent or one of support/state/choices")
	}
	return nil
}

func ValidateSupport(support Support) error {
	if !(float64(support.State.Maximum) >= float64(support.State.Minimum)) {
		return errors.New("support/state/maximum must be greater than or equal to support/state/minimum")
	}
	return nil
}

func EqualState(left, right State) bool { return reflect.DeepEqual(left, right) }

// SameSupportIdentity reports whether support fields that define an
// Entity's stable semantic identity are unchanged.
func SameSupportIdentity(previous, next Support) bool {
	return true
}

const (
	SetDeadline time.Duration = 10000 * time.Millisecond
)

func ValidateSetParameters(support Support, operationSupport SetSupport, parameters SetParameters) error {
	if !(parameters.Value == nil || float64(*parameters.Value) >= float64(support.State.Minimum)) {
		return errors.New("parameters/value must be absent or greater than or equal to support/state/minimum")
	}
	if !(parameters.Value == nil || float64(*parameters.Value) <= float64(support.State.Maximum)) {
		return errors.New("parameters/value must be absent or less than or equal to support/state/maximum")
	}
	if !(parameters.Choice == nil || (func() bool {
		for _, candidate := range support.State.Choices {
			if string(*parameters.Choice) == string(candidate) {
				return true
			}
		}
		return false
	}())) {
		return errors.New("parameters/choice must be absent or one of support/state/choices")
	}
	return nil
}

func SetSatisfied(parameters SetParameters, state State) bool {
	return (string(parameters.Mode) == string(state.Mode)) && ((parameters.Value == nil && state.Value == nil) || (parameters.Value != nil && state.Value != nil && float64(*parameters.Value) == float64(*state.Value))) && ((parameters.Choice == nil && state.Choice == nil) || (parameters.Choice != nil && state.Choice != nil && string(*parameters.Choice) == string(*state.Choice)))
}
