// Code generated by entitytypegen; DO NOT EDIT.

// Package numericsettingv1 provides schemas, behavior, and Go bindings for hearth.numericsetting/v1.
package numericsettingv1

const TypeID = "hearth.numericsetting/v1"

const (
	OperationSet = "set"
)

type State struct {
	Choice *string  `json:"choice,omitempty"`
	Mode   string   `json:"mode"`
	Value  *float64 `json:"value,omitempty"`
}

type StateSupportChoices []string

type StateSupport struct {
	Choices StateSupportChoices `json:"choices"`
	Maximum float64             `json:"maximum"`
	Minimum float64             `json:"minimum"`
	Unit    *string             `json:"unit,omitempty"`
}

type SetSupport struct {
}

type OperationSupport struct {
	Set SetSupport `json:"set"`
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}

type SetParameters struct {
	Choice *string  `json:"choice,omitempty"`
	Mode   string   `json:"mode"`
	Value  *float64 `json:"value,omitempty"`
}
