// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automations.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const advanceStaleHeldStateFact = `-- name: AdvanceStaleHeldStateFact :exec
INSERT INTO automation_holds (automation_id, revision, trigger_id, last_receive_order, phase)
VALUES (?, ?, ?, ?, 'idle')
ON CONFLICT (automation_id, trigger_id) DO UPDATE SET
    revision = excluded.revision,
    last_receive_order = excluded.last_receive_order
WHERE excluded.last_receive_order > automation_holds.last_receive_order
`

type AdvanceStaleHeldStateFactParams struct {
	AutomationID     string
	Revision         int64
	TriggerID        string
	LastReceiveOrder int64
}

func (q *Queries) AdvanceStaleHeldStateFact(ctx context.Context, arg AdvanceStaleHeldStateFactParams) error {
	_, err := q.db.ExecContext(ctx, advanceStaleHeldStateFact,
		arg.AutomationID,
		arg.Revision,
		arg.TriggerID,
		arg.LastReceiveOrder,
	)
	return err
}

const cancelHeldStateFact = `-- name: CancelHeldStateFact :exec
INSERT INTO automation_holds (automation_id, revision, trigger_id, last_receive_order, phase)
VALUES (?, ?, ?, ?, 'idle')
ON CONFLICT (automation_id, trigger_id) DO UPDATE SET
    revision = excluded.revision,
    last_receive_order = excluded.last_receive_order,
    phase = 'idle', started_at = NULL, due_at = NULL
WHERE excluded.last_receive_order > automation_holds.last_receive_order
`

type CancelHeldStateFactParams struct {
	AutomationID     string
	Revision         int64
	TriggerID        string
	LastReceiveOrder int64
}

func (q *Queries) CancelHeldStateFact(ctx context.Context, arg CancelHeldStateFactParams) error {
	_, err := q.db.ExecContext(ctx, cancelHeldStateFact,
		arg.AutomationID,
		arg.Revision,
		arg.TriggerID,
		arg.LastReceiveOrder,
	)
	return err
}

const cancelHeldStateWithReceiveOrder = `-- name: CancelHeldStateWithReceiveOrder :exec
UPDATE automation_holds SET phase = 'idle', started_at = NULL, due_at = NULL,
    last_receive_order = MAX(last_receive_order, ?)
WHERE automation_id = ? AND trigger_id = ?
`

type CancelHeldStateWithReceiveOrderParams struct {
	MAX          interface{}
	AutomationID string
	TriggerID    string
}

func (q *Queries) CancelHeldStateWithReceiveOrder(ctx context.Context, arg CancelHeldStateWithReceiveOrderParams) error {
	_, err := q.db.ExecContext(ctx, cancelHeldStateWithReceiveOrder, arg.MAX, arg.AutomationID, arg.TriggerID)
	return err
}

const cancelHeldStateWithoutState = `-- name: CancelHeldStateWithoutState :exec
UPDATE automation_holds SET phase = 'idle', started_at = NULL, due_at = NULL
WHERE automation_id = ? AND trigger_id = ?
`

type CancelHeldStateWithoutStateParams struct {
	AutomationID string
	TriggerID    string
}

func (q *Queries) CancelHeldStateWithoutState(ctx context.Context, arg CancelHeldStateWithoutStateParams) error {
	_, err := q.db.ExecContext(ctx, cancelHeldStateWithoutState, arg.AutomationID, arg.TriggerID)
	return err
}

const completeRun = `-- name: CompleteRun :execrows
UPDATE automation_history
SET run_status = ?,
    run_failure_code = ?,
    run_completed_at = ?
WHERE id = ? AND kind = 'run' AND run_status = 'running'
`

type CompleteRunParams struct {
	RunStatus      sql.NullString
	RunFailureCode sql.NullString
	RunCompletedAt sql.NullString
	ID             string
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeRun,
		arg.RunStatus,
		arg.RunFailureCode,
		arg.RunCompletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeStep = `-- name: CompleteStep :execrows
UPDATE automation_run_steps
SET status = ?,
    verified_command_id = ?,
    failure_code = ?,
    started_at = COALESCE(started_at, ?),
    completed_at = ?
WHERE run_id = ? AND position = ? AND status IN ('running', 'not_attempted')
`

type CompleteStepParams struct {
	Status            string
	VerifiedCommandID sql.NullString
	FailureCode       sql.NullString
	StartedAt         sql.NullString
	CompletedAt       sql.NullString
	RunID             string
	Position          int64
}

func (q *Queries) CompleteStep(ctx context.Context, arg CompleteStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeStep,
		arg.Status,
		arg.VerifiedCommandID,
		arg.FailureCode,
		arg.StartedAt,
		arg.CompletedAt,
		arg.RunID,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeDueHeldState = `-- name: ConsumeDueHeldState :exec
UPDATE automation_holds SET phase = 'consumed', started_at = NULL, due_at = NULL,
    last_receive_order = MAX(last_receive_order, ?)
WHERE automation_id = ? AND trigger_id = ? AND revision = ? AND phase = 'pending'
    AND due_at <= ?
`

type ConsumeDueHeldStateParams struct {
	MAX          interface{}
	AutomationID string
	TriggerID    string
	Revision     int64
	DueAt        sql.NullString
}

func (q *Queries) ConsumeDueHeldState(ctx context.Context, arg ConsumeDueHeldStateParams) error {
	_, err := q.db.ExecContext(ctx, consumeDueHeldState,
		arg.MAX,
		arg.AutomationID,
		arg.TriggerID,
		arg.Revision,
		arg.DueAt,
	)
	return err
}

const countFactReceipts = `-- name: CountFactReceipts :one
SELECT count(*) FROM automation_fact_receipts
WHERE fact_id = ? AND automation_id = ?
`

type CountFactReceiptsParams struct {
	FactID       string
	AutomationID string
}

func (q *Queries) CountFactReceipts(ctx context.Context, arg CountFactReceiptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFactReceipts, arg.FactID, arg.AutomationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunningRuns = `-- name: CountRunningRuns :one
SELECT count(*) FROM automation_history
WHERE automation_id = ? AND kind = 'run' AND run_status = 'running'
`

type CountRunningRunsParams struct {
	AutomationID string
}

func (q *Queries) CountRunningRuns(ctx context.Context, arg CountRunningRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunningRuns, arg.AutomationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAutomation = `-- name: CreateAutomation :one

INSERT INTO automations (id, revision, definition_json, created_at, updated_at)
VALUES (?, 1, ?, ?, ?)
RETURNING id, revision, definition_json, created_at, updated_at
`

type CreateAutomationParams struct {
	ID             string
	DefinitionJson string
	CreatedAt      string
	UpdatedAt      string
}

// Store normalized definition documents under optimistic revision control.
func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) (Automation, error) {
	row := q.db.QueryRowContext(ctx, createAutomation,
		arg.ID,
		arg.DefinitionJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFactReceipt = `-- name: CreateFactReceipt :exec
INSERT INTO automation_fact_receipts (fact_id, automation_id, outcome_kind, history_id)
VALUES (?, ?, ?, ?)
`

type CreateFactReceiptParams struct {
	FactID       string
	AutomationID string
	OutcomeKind  string
	HistoryID    string
}

func (q *Queries) CreateFactReceipt(ctx context.Context, arg CreateFactReceiptParams) error {
	_, err := q.db.ExecContext(ctx, createFactReceipt,
		arg.FactID,
		arg.AutomationID,
		arg.OutcomeKind,
		arg.HistoryID,
	)
	return err
}

const createHistoryRun = `-- name: CreateHistoryRun :exec
INSERT INTO automation_history (
    id, automation_id, automation_name, kind, revision, recorded_at,
    fact_id, fact_family, fact_entity_id, fact_variant, fact_causation_id,
    fact_value_json, fact_previous_value_json, fact_emitted_at,
    hold_trigger_id, hold_started_at, hold_due_at,
    run_snapshot_json, run_source, run_status, run_started_at,
    run_matched_trigger_ids_json,
    condition_mode, condition_bypassed, condition_result, condition_decision_json
) VALUES (?, ?, ?, 'run', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'running', ?, ?, ?, ?, ?, ?)
`

type CreateHistoryRunParams struct {
	ID                       string
	AutomationID             string
	AutomationName           string
	Revision                 int64
	RecordedAt               string
	FactID                   sql.NullString
	FactFamily               sql.NullString
	FactEntityID             sql.NullString
	FactVariant              sql.NullString
	FactCausationID          sql.NullString
	FactValueJson            sql.NullString
	FactPreviousValueJson    sql.NullString
	FactEmittedAt            sql.NullString
	HoldTriggerID            sql.NullString
	HoldStartedAt            sql.NullString
	HoldDueAt                sql.NullString
	RunSnapshotJson          sql.NullString
	RunSource                sql.NullString
	RunStartedAt             sql.NullString
	RunMatchedTriggerIdsJson sql.NullString
	ConditionMode            string
	ConditionBypassed        int64
	ConditionResult          sql.NullString
	ConditionDecisionJson    string
}

func (q *Queries) CreateHistoryRun(ctx context.Context, arg CreateHistoryRunParams) error {
	_, err := q.db.ExecContext(ctx, createHistoryRun,
		arg.ID,
		arg.AutomationID,
		arg.AutomationName,
		arg.Revision,
		arg.RecordedAt,
		arg.FactID,
		arg.FactFamily,
		arg.FactEntityID,
		arg.FactVariant,
		arg.FactCausationID,
		arg.FactValueJson,
		arg.FactPreviousValueJson,
		arg.FactEmittedAt,
		arg.HoldTriggerID,
		arg.HoldStartedAt,
		arg.HoldDueAt,
		arg.RunSnapshotJson,
		arg.RunSource,
		arg.RunStartedAt,
		arg.RunMatchedTriggerIdsJson,
		arg.ConditionMode,
		arg.ConditionBypassed,
		arg.ConditionResult,
		arg.ConditionDecisionJson,
	)
	return err
}

const createHistorySkip = `-- name: CreateHistorySkip :exec
INSERT INTO automation_history (
    id, automation_id, automation_name, kind, revision, recorded_at,
    fact_id, fact_family, fact_entity_id, fact_variant, fact_causation_id,
    fact_value_json, fact_previous_value_json, fact_emitted_at, skip_matched_triggers_json, skip_reason,
    skip_source, hold_trigger_id, hold_started_at, hold_due_at,
    condition_mode, condition_bypassed, condition_result, condition_decision_json
) VALUES (?, ?, ?, 'skip', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHistorySkipParams struct {
	ID                      string
	AutomationID            string
	AutomationName          string
	Revision                int64
	RecordedAt              string
	FactID                  sql.NullString
	FactFamily              sql.NullString
	FactEntityID            sql.NullString
	FactVariant             sql.NullString
	FactCausationID         sql.NullString
	FactValueJson           sql.NullString
	FactPreviousValueJson   sql.NullString
	FactEmittedAt           sql.NullString
	SkipMatchedTriggersJson sql.NullString
	SkipReason              sql.NullString
	SkipSource              sql.NullString
	HoldTriggerID           sql.NullString
	HoldStartedAt           sql.NullString
	HoldDueAt               sql.NullString
	ConditionMode           string
	ConditionBypassed       int64
	ConditionResult         sql.NullString
	ConditionDecisionJson   string
}

func (q *Queries) CreateHistorySkip(ctx context.Context, arg CreateHistorySkipParams) error {
	_, err := q.db.ExecContext(ctx, createHistorySkip,
		arg.ID,
		arg.AutomationID,
		arg.AutomationName,
		arg.Revision,
		arg.RecordedAt,
		arg.FactID,
		arg.FactFamily,
		arg.FactEntityID,
		arg.FactVariant,
		arg.FactCausationID,
		arg.FactValueJson,
		arg.FactPreviousValueJson,
		arg.FactEmittedAt,
		arg.SkipMatchedTriggersJson,
		arg.SkipReason,
		arg.SkipSource,
		arg.HoldTriggerID,
		arg.HoldStartedAt,
		arg.HoldDueAt,
		arg.ConditionMode,
		arg.ConditionBypassed,
		arg.ConditionResult,
		arg.ConditionDecisionJson,
	)
	return err
}

const createRunStep = `-- name: CreateRunStep :exec
INSERT INTO automation_run_steps (run_id, position, step_id, status)
VALUES (?, ?, ?, 'not_attempted')
`

type CreateRunStepParams struct {
	RunID    string
	Position int64
	StepID   string
}

func (q *Queries) CreateRunStep(ctx context.Context, arg CreateRunStepParams) error {
	_, err := q.db.ExecContext(ctx, createRunStep, arg.RunID, arg.Position, arg.StepID)
	return err
}

const deleteAutomation = `-- name: DeleteAutomation :execrows
DELETE FROM automations
WHERE id = ? AND revision = ?
`

type DeleteAutomationParams struct {
	ID       string
	Revision int64
}

func (q *Queries) DeleteAutomation(ctx context.Context, arg DeleteAutomationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAutomation, arg.ID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAutomationHolds = `-- name: DeleteAutomationHolds :exec
DELETE FROM automation_holds
WHERE automation_id = ?
`

type DeleteAutomationHoldsParams struct {
	AutomationID string
}

func (q *Queries) DeleteAutomationHolds(ctx context.Context, arg DeleteAutomationHoldsParams) error {
	_, err := q.db.ExecContext(ctx, deleteAutomationHolds, arg.AutomationID)
	return err
}

const deleteHeldState = `-- name: DeleteHeldState :exec
DELETE FROM automation_holds WHERE automation_id = ? AND trigger_id = ?
`

type DeleteHeldStateParams struct {
	AutomationID string
	TriggerID    string
}

func (q *Queries) DeleteHeldState(ctx context.Context, arg DeleteHeldStateParams) error {
	_, err := q.db.ExecContext(ctx, deleteHeldState, arg.AutomationID, arg.TriggerID)
	return err
}

const deleteHistoryBefore = `-- name: DeleteHistoryBefore :execrows
DELETE FROM automation_history
WHERE id IN (
    SELECT candidate.id FROM automation_history AS candidate
    WHERE candidate.recorded_at < ?
      AND (candidate.kind = 'skip' OR candidate.run_status <> 'running')
    ORDER BY candidate.recorded_at
    LIMIT ?
)
`

type DeleteHistoryBeforeParams struct {
	RecordedAt string
	Limit      int64
}

func (q *Queries) DeleteHistoryBefore(ctx context.Context, arg DeleteHistoryBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHistoryBefore, arg.RecordedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAutomation = `-- name: GetAutomation :one
SELECT id, revision, definition_json, created_at, updated_at
FROM automations
WHERE id = ?
`

type GetAutomationParams struct {
	ID string
}

func (q *Queries) GetAutomation(ctx context.Context, arg GetAutomationParams) (Automation, error) {
	row := q.db.QueryRowContext(ctx, getAutomation, arg.ID)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHeldStateEntityState = `-- name: GetHeldStateEntityState :one
SELECT value_json, receive_order FROM entity_states WHERE entity_id = ?
`

type GetHeldStateEntityStateParams struct {
	EntityID string
}

type GetHeldStateEntityStateRow struct {
	ValueJson    string
	ReceiveOrder int64
}

func (q *Queries) GetHeldStateEntityState(ctx context.Context, arg GetHeldStateEntityStateParams) (GetHeldStateEntityStateRow, error) {
	row := q.db.QueryRowContext(ctx, getHeldStateEntityState, arg.EntityID)
	var i GetHeldStateEntityStateRow
	err := row.Scan(&i.ValueJson, &i.ReceiveOrder)
	return i, err
}

const getHeldStateObservationReceiveOrder = `-- name: GetHeldStateObservationReceiveOrder :one

SELECT receive_order FROM observations WHERE observation_id = ?
`

type GetHeldStateObservationReceiveOrderParams struct {
	ObservationID string
}

// Held-state cursor and deadline transitions run inside automation-owned transactions.
func (q *Queries) GetHeldStateObservationReceiveOrder(ctx context.Context, arg GetHeldStateObservationReceiveOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getHeldStateObservationReceiveOrder, arg.ObservationID)
	var receive_order int64
	err := row.Scan(&receive_order)
	return receive_order, err
}

const getHistoryEntry = `-- name: GetHistoryEntry :one
SELECT id, automation_id, automation_name, kind, revision, recorded_at, fact_id, fact_family, fact_entity_id, fact_variant, fact_causation_id, fact_value_json, fact_emitted_at, fact_previous_value_json, run_snapshot_json, run_source, run_status, run_failure_code, run_started_at, run_completed_at, run_matched_trigger_ids_json, skip_matched_triggers_json, skip_reason, skip_source, hold_trigger_id, hold_started_at, hold_due_at, condition_decision_json, condition_mode, condition_bypassed, condition_result FROM automation_history
WHERE automation_id = ? AND id = ?
`

type GetHistoryEntryParams struct {
	AutomationID string
	ID           string
}

func (q *Queries) GetHistoryEntry(ctx context.Context, arg GetHistoryEntryParams) (AutomationHistory, error) {
	row := q.db.QueryRowContext(ctx, getHistoryEntry, arg.AutomationID, arg.ID)
	var i AutomationHistory
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.AutomationName,
		&i.Kind,
		&i.Revision,
		&i.RecordedAt,
		&i.FactID,
		&i.FactFamily,
		&i.FactEntityID,
		&i.FactVariant,
		&i.FactCausationID,
		&i.FactValueJson,
		&i.FactEmittedAt,
		&i.FactPreviousValueJson,
		&i.RunSnapshotJson,
		&i.RunSource,
		&i.RunStatus,
		&i.RunFailureCode,
		&i.RunStartedAt,
		&i.RunCompletedAt,
		&i.RunMatchedTriggerIdsJson,
		&i.SkipMatchedTriggersJson,
		&i.SkipReason,
		&i.SkipSource,
		&i.HoldTriggerID,
		&i.HoldStartedAt,
		&i.HoldDueAt,
		&i.ConditionDecisionJson,
		&i.ConditionMode,
		&i.ConditionBypassed,
		&i.ConditionResult,
	)
	return i, err
}

const interruptRunningRuns = `-- name: InterruptRunningRuns :execrows
UPDATE automation_history
SET run_status = 'interrupted',
    run_failure_code = ?,
    run_completed_at = ?
WHERE kind = 'run' AND run_status = 'running'
`

type InterruptRunningRunsParams struct {
	RunFailureCode sql.NullString
	RunCompletedAt sql.NullString
}

func (q *Queries) InterruptRunningRuns(ctx context.Context, arg InterruptRunningRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptRunningRuns, arg.RunFailureCode, arg.RunCompletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const interruptRunningSteps = `-- name: InterruptRunningSteps :execrows
UPDATE automation_run_steps
SET status = 'interrupted',
    failure_code = ?,
    completed_at = ?
WHERE status = 'running'
`

type InterruptRunningStepsParams struct {
	FailureCode sql.NullString
	CompletedAt sql.NullString
}

func (q *Queries) InterruptRunningSteps(ctx context.Context, arg InterruptRunningStepsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptRunningSteps, arg.FailureCode, arg.CompletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllAutomations = `-- name: ListAllAutomations :many

SELECT id, revision, definition_json, created_at, updated_at
FROM automations
ORDER BY id
`

// Runtime admission, execution, and history queries use automation-owned transactions.
func (q *Queries) ListAllAutomations(ctx context.Context) ([]Automation, error) {
	rows, err := q.db.QueryContext(ctx, listAllAutomations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.DefinitionJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationsAfter = `-- name: ListAutomationsAfter :many
SELECT id, revision, definition_json, created_at, updated_at
FROM automations
WHERE id > ?
ORDER BY id
LIMIT ?
`

type ListAutomationsAfterParams struct {
	ID    string
	Limit int64
}

func (q *Queries) ListAutomationsAfter(ctx context.Context, arg ListAutomationsAfterParams) ([]Automation, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.DefinitionJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationsFirstPage = `-- name: ListAutomationsFirstPage :many
SELECT id, revision, definition_json, created_at, updated_at
FROM automations
ORDER BY id
LIMIT ?
`

type ListAutomationsFirstPageParams struct {
	Limit int64
}

func (q *Queries) ListAutomationsFirstPage(ctx context.Context, arg ListAutomationsFirstPageParams) ([]Automation, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationsFirstPage, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.DefinitionJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueHeldStateCandidates = `-- name: ListDueHeldStateCandidates :many
SELECT automation_id, revision, trigger_id, due_at
FROM automation_holds WHERE phase = 'pending' AND due_at <= ?
ORDER BY due_at, automation_id, trigger_id LIMIT ?
`

type ListDueHeldStateCandidatesParams struct {
	DueAt sql.NullString
	Limit int64
}

type ListDueHeldStateCandidatesRow struct {
	AutomationID string
	Revision     int64
	TriggerID    string
	DueAt        sql.NullString
}

func (q *Queries) ListDueHeldStateCandidates(ctx context.Context, arg ListDueHeldStateCandidatesParams) ([]ListDueHeldStateCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueHeldStateCandidates, arg.DueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueHeldStateCandidatesRow
	for rows.Next() {
		var i ListDueHeldStateCandidatesRow
		if err := rows.Scan(
			&i.AutomationID,
			&i.Revision,
			&i.TriggerID,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueHeldStateRows = `-- name: ListDueHeldStateRows :many
SELECT automation_id, revision, trigger_id, last_receive_order, phase, started_at, due_at
FROM automation_holds WHERE phase = 'pending' AND due_at <= ?
ORDER BY due_at, automation_id, trigger_id LIMIT ?
`

type ListDueHeldStateRowsParams struct {
	DueAt sql.NullString
	Limit int64
}

func (q *Queries) ListDueHeldStateRows(ctx context.Context, arg ListDueHeldStateRowsParams) ([]AutomationHold, error) {
	rows, err := q.db.QueryContext(ctx, listDueHeldStateRows, arg.DueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationHold
	for rows.Next() {
		var i AutomationHold
		if err := rows.Scan(
			&i.AutomationID,
			&i.Revision,
			&i.TriggerID,
			&i.LastReceiveOrder,
			&i.Phase,
			&i.StartedAt,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryAfter = `-- name: ListHistoryAfter :many
SELECT id, automation_id, automation_name, kind, revision, recorded_at, fact_id, fact_family, fact_entity_id, fact_variant, fact_causation_id, fact_value_json, fact_emitted_at, fact_previous_value_json, run_snapshot_json, run_source, run_status, run_failure_code, run_started_at, run_completed_at, run_matched_trigger_ids_json, skip_matched_triggers_json, skip_reason, skip_source, hold_trigger_id, hold_started_at, hold_due_at, condition_decision_json, condition_mode, condition_bypassed, condition_result FROM automation_history
WHERE automation_id = ?
  AND (recorded_at < ? OR (recorded_at = ? AND id < ?))
ORDER BY recorded_at DESC, id DESC
LIMIT ?
`

type ListHistoryAfterParams struct {
	AutomationID string
	RecordedAt   string
	RecordedAt_2 string
	ID           string
	Limit        int64
}

func (q *Queries) ListHistoryAfter(ctx context.Context, arg ListHistoryAfterParams) ([]AutomationHistory, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryAfter,
		arg.AutomationID,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationHistory
	for rows.Next() {
		var i AutomationHistory
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.AutomationName,
			&i.Kind,
			&i.Revision,
			&i.RecordedAt,
			&i.FactID,
			&i.FactFamily,
			&i.FactEntityID,
			&i.FactVariant,
			&i.FactCausationID,
			&i.FactValueJson,
			&i.FactEmittedAt,
			&i.FactPreviousValueJson,
			&i.RunSnapshotJson,
			&i.RunSource,
			&i.RunStatus,
			&i.RunFailureCode,
			&i.RunStartedAt,
			&i.RunCompletedAt,
			&i.RunMatchedTriggerIdsJson,
			&i.SkipMatchedTriggersJson,
			&i.SkipReason,
			&i.SkipSource,
			&i.HoldTriggerID,
			&i.HoldStartedAt,
			&i.HoldDueAt,
			&i.ConditionDecisionJson,
			&i.ConditionMode,
			&i.ConditionBypassed,
			&i.ConditionResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryFirstPage = `-- name: ListHistoryFirstPage :many
SELECT id, automation_id, automation_name, kind, revision, recorded_at, fact_id, fact_family, fact_entity_id, fact_variant, fact_causation_id, fact_value_json, fact_emitted_at, fact_previous_value_json, run_snapshot_json, run_source, run_status, run_failure_code, run_started_at, run_completed_at, run_matched_trigger_ids_json, skip_matched_triggers_json, skip_reason, skip_source, hold_trigger_id, hold_started_at, hold_due_at, condition_decision_json, condition_mode, condition_bypassed, condition_result FROM automation_history
WHERE automation_id = ?
ORDER BY recorded_at DESC, id DESC
LIMIT ?
`

type ListHistoryFirstPageParams struct {
	AutomationID string
	Limit        int64
}

func (q *Queries) ListHistoryFirstPage(ctx context.Context, arg ListHistoryFirstPageParams) ([]AutomationHistory, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryFirstPage, arg.AutomationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationHistory
	for rows.Next() {
		var i AutomationHistory
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.AutomationName,
			&i.Kind,
			&i.Revision,
			&i.RecordedAt,
			&i.FactID,
			&i.FactFamily,
			&i.FactEntityID,
			&i.FactVariant,
			&i.FactCausationID,
			&i.FactValueJson,
			&i.FactEmittedAt,
			&i.FactPreviousValueJson,
			&i.RunSnapshotJson,
			&i.RunSource,
			&i.RunStatus,
			&i.RunFailureCode,
			&i.RunStartedAt,
			&i.RunCompletedAt,
			&i.RunMatchedTriggerIdsJson,
			&i.SkipMatchedTriggersJson,
			&i.SkipReason,
			&i.SkipSource,
			&i.HoldTriggerID,
			&i.HoldStartedAt,
			&i.HoldDueAt,
			&i.ConditionDecisionJson,
			&i.ConditionMode,
			&i.ConditionBypassed,
			&i.ConditionResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT run_id, position, step_id, status, reserved_command_id, reserved_correlation_id, verified_command_id, failure_code, started_at, completed_at FROM automation_run_steps
WHERE run_id = ?
ORDER BY position
`

type ListRunStepsParams struct {
	RunID string
}

func (q *Queries) ListRunSteps(ctx context.Context, arg ListRunStepsParams) ([]AutomationRunStep, error) {
	rows, err := q.db.QueryContext(ctx, listRunSteps, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationRunStep
	for rows.Next() {
		var i AutomationRunStep
		if err := rows.Scan(
			&i.RunID,
			&i.Position,
			&i.StepID,
			&i.Status,
			&i.ReservedCommandID,
			&i.ReservedCorrelationID,
			&i.VerifiedCommandID,
			&i.FailureCode,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStepRunning = `-- name: MarkStepRunning :execrows
UPDATE automation_run_steps
SET status = 'running',
    reserved_command_id = ?,
    reserved_correlation_id = ?,
    started_at = ?
WHERE run_id = ? AND position = ? AND status = 'not_attempted'
`

type MarkStepRunningParams struct {
	ReservedCommandID     sql.NullString
	ReservedCorrelationID sql.NullString
	StartedAt             sql.NullString
	RunID                 string
	Position              int64
}

func (q *Queries) MarkStepRunning(ctx context.Context, arg MarkStepRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markStepRunning,
		arg.ReservedCommandID,
		arg.ReservedCorrelationID,
		arg.StartedAt,
		arg.RunID,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const replaceAutomation = `-- name: ReplaceAutomation :one
UPDATE automations
SET revision = revision + 1,
    definition_json = ?,
    updated_at = ?
WHERE id = ? AND revision = ?
RETURNING id, revision, definition_json, created_at, updated_at
`

type ReplaceAutomationParams struct {
	DefinitionJson string
	UpdatedAt      string
	ID             string
	Revision       int64
}

func (q *Queries) ReplaceAutomation(ctx context.Context, arg ReplaceAutomationParams) (Automation, error) {
	row := q.db.QueryRowContext(ctx, replaceAutomation,
		arg.DefinitionJson,
		arg.UpdatedAt,
		arg.ID,
		arg.Revision,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetPendingHeldStates = `-- name: ResetPendingHeldStates :exec
UPDATE automation_holds SET phase = 'idle', started_at = NULL, due_at = NULL
WHERE phase = 'pending'
`

func (q *Queries) ResetPendingHeldStates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPendingHeldStates)
	return err
}

const startHeldStateFact = `-- name: StartHeldStateFact :exec
INSERT INTO automation_holds (
    automation_id, revision, trigger_id, last_receive_order, phase, started_at, due_at
) VALUES (?, ?, ?, ?, 'pending', ?, ?)
ON CONFLICT (automation_id, trigger_id) DO UPDATE SET
    revision = excluded.revision,
    last_receive_order = excluded.last_receive_order,
    phase = CASE WHEN automation_holds.phase = 'idle' THEN 'pending'
        ELSE automation_holds.phase END,
    started_at = CASE WHEN automation_holds.phase = 'idle' THEN excluded.started_at
        ELSE automation_holds.started_at END,
    due_at = CASE WHEN automation_holds.phase = 'idle' THEN excluded.due_at
        ELSE automation_holds.due_at END
WHERE excluded.last_receive_order > automation_holds.last_receive_order
`

type StartHeldStateFactParams struct {
	AutomationID     string
	Revision         int64
	TriggerID        string
	LastReceiveOrder int64
	StartedAt        sql.NullString
	DueAt            sql.NullString
}

func (q *Queries) StartHeldStateFact(ctx context.Context, arg StartHeldStateFactParams) error {
	_, err := q.db.ExecContext(ctx, startHeldStateFact,
		arg.AutomationID,
		arg.Revision,
		arg.TriggerID,
		arg.LastReceiveOrder,
		arg.StartedAt,
		arg.DueAt,
	)
	return err
}
