// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delays.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const completeRunDelay = `-- name: CompleteRunDelay :execrows
UPDATE automation_run_delays SET status = ?, completed_at = ?, failure_code = ?
WHERE run_id = ? AND step_id = ? AND status = 'running'
    AND EXISTS (SELECT 1 FROM automation_history
        WHERE id = automation_run_delays.run_id AND kind = 'run' AND run_status = 'running')
`

type CompleteRunDelayParams struct {
	Status      string
	CompletedAt sql.NullString
	FailureCode sql.NullString
	RunID       string
	StepID      string
}

func (q *Queries) CompleteRunDelay(ctx context.Context, arg CompleteRunDelayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeRunDelay,
		arg.Status,
		arg.CompletedAt,
		arg.FailureCode,
		arg.RunID,
		arg.StepID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createRunDelay = `-- name: CreateRunDelay :exec
INSERT INTO automation_run_delays (run_id, step_id, position, status, started_at)
VALUES (?, ?, ?, 'running', ?)
`

type CreateRunDelayParams struct {
	RunID     string
	StepID    string
	Position  int64
	StartedAt string
}

func (q *Queries) CreateRunDelay(ctx context.Context, arg CreateRunDelayParams) error {
	_, err := q.db.ExecContext(ctx, createRunDelay,
		arg.RunID,
		arg.StepID,
		arg.Position,
		arg.StartedAt,
	)
	return err
}

const getDelayParent = `-- name: GetDelayParent :one
SELECT id, automation_id, automation_name, kind, revision, recorded_at, fact_id, fact_family, fact_entity_id, fact_variant, fact_causation_id, fact_value_json, fact_emitted_at, fact_previous_value_json, run_snapshot_json, run_source, run_status, run_failure_code, run_started_at, run_completed_at, run_matched_trigger_ids_json, skip_matched_triggers_json, skip_reason, skip_source, hold_trigger_id, hold_started_at, hold_due_at, condition_decision_json, condition_mode, condition_bypassed, condition_result FROM automation_history WHERE id = ?
`

type GetDelayParentParams struct {
	ID string
}

func (q *Queries) GetDelayParent(ctx context.Context, arg GetDelayParentParams) (AutomationHistory, error) {
	row := q.db.QueryRowContext(ctx, getDelayParent, arg.ID)
	var i AutomationHistory
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.AutomationName,
		&i.Kind,
		&i.Revision,
		&i.RecordedAt,
		&i.FactID,
		&i.FactFamily,
		&i.FactEntityID,
		&i.FactVariant,
		&i.FactCausationID,
		&i.FactValueJson,
		&i.FactEmittedAt,
		&i.FactPreviousValueJson,
		&i.RunSnapshotJson,
		&i.RunSource,
		&i.RunStatus,
		&i.RunFailureCode,
		&i.RunStartedAt,
		&i.RunCompletedAt,
		&i.RunMatchedTriggerIdsJson,
		&i.SkipMatchedTriggersJson,
		&i.SkipReason,
		&i.SkipSource,
		&i.HoldTriggerID,
		&i.HoldStartedAt,
		&i.HoldDueAt,
		&i.ConditionDecisionJson,
		&i.ConditionMode,
		&i.ConditionBypassed,
		&i.ConditionResult,
	)
	return i, err
}

const interruptRunningDelays = `-- name: InterruptRunningDelays :execrows
UPDATE automation_run_delays SET status = 'interrupted', completed_at = ?, failure_code = ?
WHERE status = 'running'
`

type InterruptRunningDelaysParams struct {
	CompletedAt sql.NullString
	FailureCode sql.NullString
}

func (q *Queries) InterruptRunningDelays(ctx context.Context, arg InterruptRunningDelaysParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptRunningDelays, arg.CompletedAt, arg.FailureCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listRunDelays = `-- name: ListRunDelays :many
SELECT run_id, step_id, position, status, started_at, completed_at, failure_code FROM automation_run_delays WHERE run_id = ? ORDER BY position
`

type ListRunDelaysParams struct {
	RunID string
}

func (q *Queries) ListRunDelays(ctx context.Context, arg ListRunDelaysParams) ([]AutomationRunDelay, error) {
	rows, err := q.db.QueryContext(ctx, listRunDelays, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationRunDelay
	for rows.Next() {
		var i AutomationRunDelay
		if err := rows.Scan(
			&i.RunID,
			&i.StepID,
			&i.Position,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
