// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"database/sql"
)

type AdapterBinding struct {
	AdapterID        string
	BindingKey       string
	DeviceID         string
	ExternalDeviceID sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

type AdapterEntityMapping struct {
	AdapterID        string
	BindingKey       string
	EntityKey        string
	EntityID         string
	ExternalEntityID string
	CreatedAt        string
	UpdatedAt        string
}

type AdapterInstance struct {
	AdapterID              string
	ActiveRuntimeID        sql.NullString
	HealthRuntimeID        sql.NullString
	HealthStatus           string
	HealthReasonCode       sql.NullString
	HealthSource           string
	HealthSince            string
	HealthEvidenceAt       string
	HealthSourceObservedAt sql.NullString
}

type AdapterRuntime struct {
	RuntimeID       string
	AdapterID       string
	SoftwareName    string
	SoftwareVersion string
	ClaimedAt       string
	LastHeartbeatAt sql.NullString
	LeaseExpiresAt  string
	EndedAt         sql.NullString
	EndReason       sql.NullString
}

type Automation struct {
	ID             string
	Revision       int64
	DefinitionJson string
	CreatedAt      string
	UpdatedAt      string
}

type AutomationFactReceipt struct {
	FactID       string
	AutomationID string
	OutcomeKind  string
	HistoryID    string
}

type AutomationHistory struct {
	ID                       string
	AutomationID             string
	AutomationName           string
	Kind                     string
	Revision                 int64
	RecordedAt               string
	FactID                   sql.NullString
	FactFamily               sql.NullString
	FactEntityID             sql.NullString
	FactVariant              sql.NullString
	FactCausationID          sql.NullString
	FactValueJson            sql.NullString
	FactEmittedAt            sql.NullString
	RunSnapshotJson          sql.NullString
	RunSource                sql.NullString
	RunStatus                sql.NullString
	RunFailureCode           sql.NullString
	RunStartedAt             sql.NullString
	RunCompletedAt           sql.NullString
	RunMatchedTriggerIdsJson sql.NullString
	SkipMatchedTriggersJson  sql.NullString
	SkipReason               sql.NullString
}

type AutomationRunStep struct {
	RunID                 string
	Position              int64
	StepID                string
	Status                string
	ReservedCommandID     sql.NullString
	ReservedCorrelationID sql.NullString
	VerifiedCommandID     sql.NullString
	FailureCode           sql.NullString
	StartedAt             sql.NullString
	CompletedAt           sql.NullString
}

type Command struct {
	ID                   string
	EntityID             string
	AdapterID            string
	RuntimeID            sql.NullString
	Operation            string
	ParametersJson       string
	CorrelationID        string
	Status               string
	RequestedAt          string
	DeadlineAt           string
	AcceptedAt           sql.NullString
	CompletedAt          sql.NullString
	OutcomeObservationID sql.NullString
	FailureCode          sql.NullString
}

type Device struct {
	ID        string
	Kind      string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type DeviceFactsOutbox struct {
	EnqueueOrder      int64
	FactID            string
	Family            string
	EntityID          string
	Variant           string
	SourceID          string
	CorrelationID     string
	CreatedAt         string
	Traceparent       string
	Tracestate        string
	ValueJson         sql.NullString
	AdapterReceivedAt sql.NullString
	SourceUpdatedAt   sql.NullString
	ObservedAt        sql.NullString
	ReportedAt        sql.NullString
	ReceivedAt        sql.NullString
	RecordedAt        sql.NullString
}

type Entity struct {
	ID          string
	DeviceID    string
	Name        string
	TypeID      string
	SupportJson string
	CreatedAt   string
	UpdatedAt   string
	Enabled     int64
}

type EntityAvailabilityCurrent struct {
	EntityID                     string
	AdapterID                    string
	RuntimeID                    string
	Status                       string
	ReasonCode                   sql.NullString
	SourceObservedAt             string
	EvidenceAt                   string
	CurrentSince                 string
	LatestTransitionReceiveOrder sql.NullInt64
}

type EntityAvailabilityReceipt struct {
	RequestID   string
	Fingerprint string
	ReportedAt  string
}

type EntityEvent struct {
	ReceiveOrder  int64
	EventID       string
	AdapterID     string
	RuntimeID     string
	EntityID      string
	CorrelationID string
	Name          string
	Fingerprint   []byte
	Disposition   string
	RejectionCode sql.NullString
	EmittedAt     string
	ReceivedAt    string
	RecordedAt    string
}

type EntityReadProjection struct {
	ID                                   string
	DeviceID                             string
	AdapterID                            string
	Name                                 string
	TypeID                               string
	SupportJson                          string
	Enabled                              int64
	EntityCreatedAt                      string
	ObservationID                        sql.NullString
	ValueJson                            sql.NullString
	AdapterReceivedAt                    sql.NullString
	SourceUpdatedAt                      sql.NullString
	ObservedAt                           sql.NullString
	ReceiveOrder                         sql.NullInt64
	AdapterHealthStatus                  sql.NullString
	AdapterHealthReasonCode              sql.NullString
	AdapterHealthSince                   sql.NullString
	AdapterHealthEvidenceAt              sql.NullString
	AdapterHealthSourceObservedAt        sql.NullString
	ReportedAvailabilityStatus           sql.NullString
	ReportedAvailabilityReasonCode       sql.NullString
	ReportedAvailabilitySourceObservedAt sql.NullString
	ReportedAvailabilityEvidenceAt       sql.NullString
	ReportedAvailabilitySince            sql.NullString
}

type EntityState struct {
	EntityID          string
	ObservationID     string
	ValueJson         string
	AdapterReceivedAt string
	SourceUpdatedAt   sql.NullString
	ObservedAt        string
	ReceiveOrder      int64
}

type HealthTransition struct {
	ReceiveOrder     int64
	ResourceKind     string
	AdapterID        string
	EntityID         sql.NullString
	RuntimeID        sql.NullString
	Status           string
	Source           string
	ReasonCode       sql.NullString
	SourceObservedAt sql.NullString
	ObservedAt       string
}

type Observation struct {
	ReceiveOrder      int64
	ObservationID     string
	AdapterID         string
	RuntimeID         sql.NullString
	EntityID          string
	Disposition       string
	RejectionCode     sql.NullString
	StateValueJson    sql.NullString
	AdapterReceivedAt string
	SourceUpdatedAt   sql.NullString
	ObservedAt        string
}
