// Code generated by entitytypegen; DO NOT EDIT.

package enumactionv1

import (
	"encoding/json"
	"errors"
	"fmt"
	"sync"

	contractenumactionv1 "github.com/mholtzscher/hearth/entitytypes/enumactionv1"
	"github.com/mholtzscher/hearth/sdk/adapter"
	"github.com/mholtzscher/hearth/sdk/adapter/typed"
)

type Support = contractenumactionv1.Support
type State = contractenumactionv1.State
type StateSupport = contractenumactionv1.StateSupport
type OperationSupport = contractenumactionv1.OperationSupport
type TriggerSupport = contractenumactionv1.TriggerSupport
type TriggerParameters = contractenumactionv1.TriggerParameters
type TriggerCommand = typed.Command[TriggerParameters]

type Handlers struct {
	Trigger typed.Handler[TriggerParameters]
}

// Stateless entity types carry no State observations; the facade
// intentionally defines no ObservationInput or NewObservation.

var (
	compileOnce  sync.Once
	sharedCodecs *contractenumactionv1.Codecs
	compileErr   error
)

func NewEntityDescriptor(metadata adapter.EntityMetadata, support Support) (adapter.EntityDescriptor, error) {
	codecs, err := codecs()
	if err != nil {
		return adapter.EntityDescriptor{}, err
	}
	return typed.NewTypedEntityDescriptor(metadata, contractenumactionv1.TypeID, support, codecs.Support)
}

func NewCommandHandler(entityID string, support Support, handlers Handlers) (adapter.CommandHandler, error) {
	codecs, err := codecs()
	if err != nil {
		return nil, err
	}
	if _, err := codecs.Support.Encode(support); err != nil {
		return nil, validationError(fmt.Errorf("invalid Entity support: %w", err))
	}
	var routes []typed.Route
	if handlers.Trigger == nil {
		return nil, validationError(errors.New("trigger handler is required"))
	}
	triggerSupport := support.Operations.Trigger
	triggerRoute, err := typed.Operation(entityID, contractenumactionv1.OperationTrigger, func(raw json.RawMessage) (TriggerParameters, error) {
		parameters, _, err := codecs.TriggerParameters.Decode(raw)
		if err != nil {
			return TriggerParameters{}, err
		}
		if err := contractenumactionv1.ValidateTriggerParameters(support, triggerSupport, parameters); err != nil {
			return TriggerParameters{}, err
		}
		return parameters, nil
	}, handlers.Trigger)
	if err != nil {
		return nil, validationError(err)
	}
	routes = append(routes, triggerRoute)
	handler, err := typed.NewCommandHandler(routes...)
	if err != nil {
		return nil, validationError(err)
	}
	return handler, nil
}

func codecs() (*contractenumactionv1.Codecs, error) {
	compileOnce.Do(func() { sharedCodecs, compileErr = contractenumactionv1.Compile() })
	if compileErr != nil {
		return nil, fmt.Errorf("compile Entity-type schemas: %w", compileErr)
	}
	return sharedCodecs, nil
}

func validationError(err error) error { return &adapter.ValidationError{Err: err} }
