// Code generated by entitytypegen; DO NOT EDIT.

package enumactionv1

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/mholtzscher/hearth/internal/entitytypetest"
	"github.com/mholtzscher/hearth/sdk/adapter"
	"github.com/mholtzscher/hearth/sdk/adapter/adaptertest"
)

func TestGeneratedStatelessOmitsObservation(t *testing.T) {
	t.Log("stateless hearth.enumaction/v1 defines no ObservationInput or NewObservation")
}

func TestGeneratedEntityDescriptor(t *testing.T) {
	codecs, err := codecs()
	if err != nil {
		t.Fatal(err)
	}
	support, _, err := codecs.Support.Decode(json.RawMessage("{\n        \"state\": {},\n        \"operations\": {\"trigger\": {\"values\": [\"blink\", \"breathe\", \"okay\", \"channel_change\", \"finish_effect\", \"stop_effect\"]}}\n      }"))
	if err != nil {
		t.Fatalf("support: %v", err)
	}
	metadata := adapter.EntityMetadata{Key: "key_01890f47-7a6b-7c4d-8e9f-0123456789ab", ExternalID: "ext-001", Name: "generated entity"}
	descriptor, err := NewEntityDescriptor(metadata, support)
	if err != nil {
		t.Fatalf("descriptor: %v", err)
	}
	if descriptor.Key != metadata.Key {
		t.Errorf("descriptor key = %q", descriptor.Key)
	}
	if descriptor.ExternalID != metadata.ExternalID {
		t.Errorf("descriptor external ID = %q", descriptor.ExternalID)
	}
	if descriptor.Name != metadata.Name {
		t.Errorf("descriptor name = %q", descriptor.Name)
	}
	if descriptor.Type != "hearth.enumaction/v1" {
		t.Errorf("descriptor type = %q", descriptor.Type)
	}
	if entitytypetest.CanonicalJSON(t, descriptor.Support) != entitytypetest.CanonicalJSON(t, json.RawMessage("{\n        \"state\": {},\n        \"operations\": {\"trigger\": {\"values\": [\"blink\", \"breathe\", \"okay\", \"channel_change\", \"finish_effect\", \"stop_effect\"]}}\n      }")) {
		t.Errorf("descriptor support = %s", descriptor.Support)
	}
}

func TestGeneratedCommandConformance(t *testing.T) {
	codecs, err := codecs()
	if err != nil {
		t.Fatal(err)
	}
	t.Run("effects", func(t *testing.T) {
		support, _, err := codecs.Support.Decode(json.RawMessage("{\n        \"state\": {},\n        \"operations\": {\"trigger\": {\"values\": [\"blink\", \"breathe\", \"okay\", \"channel_change\", \"finish_effect\", \"stop_effect\"]}}\n      }"))
		if err != nil {
			t.Fatalf("support: %v", err)
		}
		triggerCalls := []TriggerCommand{}
		handler, err := NewCommandHandler("ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", support, Handlers{
			Trigger: func(_ context.Context, command TriggerCommand, _ adapter.Responder) error {
				triggerCalls = append(triggerCalls, command)
				return nil
			},
		})
		if err != nil {
			t.Fatalf("command handler: %v", err)
		}
		deadline := time.Date(2026, time.June, 15, 12, 0, 0, 0, time.UTC)
		if err := handler(context.Background(), adapter.Command{ID: "cmd_trigger_one", CorrelationID: "cor_trigger_one", EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", OperationName: "trigger", Parameters: json.RawMessage("{\"name\": \"blink\"}"), Deadline: deadline.Format(time.RFC3339Nano)}, nil); err != nil {
			t.Fatalf("trigger command: %v", err)
		}
		if len(triggerCalls) != 1 {
			t.Fatalf("trigger handler calls = %d, want 1", len(triggerCalls))
		}
		receivedTrigger := triggerCalls[0]
		if receivedTrigger.ID != "cmd_trigger_one" || receivedTrigger.CorrelationID != "cor_trigger_one" || receivedTrigger.EntityID != "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab" {
			t.Errorf("trigger command identity = %+v", receivedTrigger)
		}
		if !receivedTrigger.Deadline.Equal(deadline) {
			t.Errorf("trigger command deadline = %v", receivedTrigger.Deadline)
		}
		if entitytypetest.CanonicalValue(t, receivedTrigger.Parameters) != entitytypetest.CanonicalJSON(t, json.RawMessage("{\"name\": \"blink\"}")) {
			t.Errorf("trigger command parameters = %+v", receivedTrigger.Parameters)
		}
		{
			if _, _, decodeErr := codecs.TriggerParameters.Decode(json.RawMessage("{\"name\": \"blink\"}")); decodeErr != nil {
				t.Errorf("trigger parameter example 1 marked valid but rejected by parameters codec: %v", decodeErr)
			}
		}
		{
			if _, _, decodeErr := codecs.TriggerParameters.Decode(json.RawMessage("{\"name\": \"stop_effect\"}")); decodeErr != nil {
				t.Errorf("trigger parameter example 2 marked valid but rejected by parameters codec: %v", decodeErr)
			}
		}
		{
			raw := json.RawMessage("{\"name\": \"party\"}")
			before := len(triggerCalls)
			if invokeErr := handler(context.Background(), adapter.Command{ID: "cmd_trigger_invalid_3", CorrelationID: "cor_trigger_invalid_3", EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", OperationName: "trigger", Parameters: raw, Deadline: deadline.Format(time.RFC3339Nano)}, nil); invokeErr == nil {
				t.Errorf("invalid trigger parameter example 3 was accepted")
			}
			if len(triggerCalls) != before {
				t.Errorf("trigger handler invoked for invalid trigger parameter example 3")
			}
		}
		{
			raw := json.RawMessage("{\"name\": \"\"}")
			before := len(triggerCalls)
			if invokeErr := handler(context.Background(), adapter.Command{ID: "cmd_trigger_invalid_4", CorrelationID: "cor_trigger_invalid_4", EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", OperationName: "trigger", Parameters: raw, Deadline: deadline.Format(time.RFC3339Nano)}, nil); invokeErr == nil {
				t.Errorf("invalid trigger parameter example 4 was accepted")
			}
			if len(triggerCalls) != before {
				t.Errorf("trigger handler invoked for invalid trigger parameter example 4")
			}
		}
		{
			before := len(triggerCalls)
			if invokeErr := handler(context.Background(), adapter.Command{ID: "cmd_wrong_entity", CorrelationID: "cor_wrong_entity", EntityID: "ent_6ba7b810-9b21-11d1-80b4-00c04fd430c8", OperationName: "trigger", Parameters: json.RawMessage("{\"name\": \"blink\"}"), Deadline: deadline.Format(time.RFC3339Nano)}, nil); invokeErr == nil {
				t.Error("command for wrong entity ID was accepted")
			}
			if invokeErr := handler(context.Background(), adapter.Command{ID: "cmd_unknown_operation", CorrelationID: "cor_unknown_operation", EntityID: "ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", OperationName: "unknown", Parameters: json.RawMessage("{\"name\": \"blink\"}"), Deadline: deadline.Format(time.RFC3339Nano)}, nil); invokeErr == nil {
				t.Error("command for unknown operation was accepted")
			}
			if total := len(triggerCalls); total != before {
				t.Errorf("misrouted command invoked a handler: calls = %d, want %d", total, before)
			}
		}
		if _, err := NewCommandHandler("ent_01890f47-7a6b-7c4d-8e9f-0123456789ab", support, Handlers{}); err == nil {
			t.Error("command handler without trigger handler was accepted")
		} else {
			adaptertest.RequireValidationError(t, err, "reject command handler without trigger handler")
		}
	})
}
