// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package receipts

import (
	"context"
)

type Querier interface {
	DeleteExpiredObservationReceipts(ctx context.Context, arg DeleteExpiredObservationReceiptsParams) (int64, error)
	GetObservationReceipt(ctx context.Context, arg GetObservationReceiptParams) (ObservationReceipt, error)
	InsertObservationReceipt(ctx context.Context, arg InsertObservationReceiptParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
