// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package receipts

import (
	"context"
	"database/sql"
)

const deleteExpiredObservationReceipts = `-- name: DeleteExpiredObservationReceipts :execrows
DELETE FROM observation_receipts
WHERE julianday(expires_at) < julianday(CAST(?1 AS TEXT))
  AND NOT EXISTS (
      SELECT 1
      FROM entity_states
      WHERE entity_states.observation_id = observation_receipts.observation_id
  )
`

type DeleteExpiredObservationReceiptsParams struct {
	ExpiresAt string
}

func (q *Queries) DeleteExpiredObservationReceipts(ctx context.Context, arg DeleteExpiredObservationReceiptsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredObservationReceipts, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getObservationReceipt = `-- name: GetObservationReceipt :one
SELECT receive_order, observation_id, adapter_id, entity_id, disposition,
       rejection_code, adapter_received_at, observed_at, expires_at
FROM observation_receipts
WHERE observation_id = ?
`

type GetObservationReceiptParams struct {
	ObservationID string
}

func (q *Queries) GetObservationReceipt(ctx context.Context, arg GetObservationReceiptParams) (ObservationReceipt, error) {
	row := q.db.QueryRowContext(ctx, getObservationReceipt, arg.ObservationID)
	var i ObservationReceipt
	err := row.Scan(
		&i.ReceiveOrder,
		&i.ObservationID,
		&i.AdapterID,
		&i.EntityID,
		&i.Disposition,
		&i.RejectionCode,
		&i.AdapterReceivedAt,
		&i.ObservedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertObservationReceipt = `-- name: InsertObservationReceipt :one
INSERT INTO observation_receipts (
    observation_id, adapter_id, entity_id, disposition, rejection_code,
    adapter_received_at, observed_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING receive_order
`

type InsertObservationReceiptParams struct {
	ObservationID     string
	AdapterID         string
	EntityID          string
	Disposition       string
	RejectionCode     sql.NullString
	AdapterReceivedAt string
	ObservedAt        string
	ExpiresAt         string
}

func (q *Queries) InsertObservationReceipt(ctx context.Context, arg InsertObservationReceiptParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertObservationReceipt,
		arg.ObservationID,
		arg.AdapterID,
		arg.EntityID,
		arg.Disposition,
		arg.RejectionCode,
		arg.AdapterReceivedAt,
		arg.ObservedAt,
		arg.ExpiresAt,
	)
	var receive_order int64
	err := row.Scan(&receive_order)
	return receive_order, err
}
