// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package registration

import (
	"database/sql"
)

type AdapterBinding struct {
	AdapterID        string
	BindingKey       string
	DeviceID         string
	ExternalDeviceID sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

type AdapterEntityMapping struct {
	AdapterID        string
	BindingKey       string
	EntityKey        string
	EntityID         string
	ExternalEntityID string
	CreatedAt        string
	UpdatedAt        string
}

type AdapterInstance struct {
	AdapterID                      string
	ArchivedAt                     sql.NullString
	CreatedAt                      string
	UpdatedAt                      string
	ActiveRuntimeID                sql.NullString
	HealthRuntimeID                sql.NullString
	HealthStatus                   sql.NullString
	HealthReasonCode               sql.NullString
	HealthReasonDetail             sql.NullString
	HealthSince                    sql.NullString
	HealthEvidenceAt               sql.NullString
	ExternalSystemStatus           sql.NullString
	ExternalSystemReasonCode       sql.NullString
	ExternalSystemReasonDetail     sql.NullString
	ExternalSystemSourceObservedAt sql.NullString
	ExternalSystemEvidenceAt       sql.NullString
	AvailabilityEpoch              int64
	LatestTransitionReceiveOrder   sql.NullInt64
}

type AdapterRuntime struct {
	RuntimeID       string
	ClaimID         string
	AdapterID       string
	SoftwareName    string
	SoftwareVersion string
	ClaimedAt       string
	LastHeartbeatAt sql.NullString
	LeaseExpiresAt  string
	EndedAt         sql.NullString
	EndReason       sql.NullString
}

type Command struct {
	ID                   string
	EntityID             string
	AdapterID            string
	RuntimeID            sql.NullString
	Operation            string
	ParametersJson       string
	CorrelationID        string
	Status               string
	RequestedAt          string
	DeadlineAt           string
	AcceptedAt           sql.NullString
	CompletedAt          sql.NullString
	OutcomeObservationID sql.NullString
	FailureCode          sql.NullString
}

type Device struct {
	ID        string
	Kind      string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type Entity struct {
	ID          string
	DeviceID    string
	Name        string
	TypeID      string
	SupportJson string
	CreatedAt   string
	UpdatedAt   string
	Enabled     int64
}

type EntityAvailabilityCurrent struct {
	EntityID                     string
	AdapterID                    string
	RuntimeID                    string
	AvailabilityEpoch            int64
	Status                       string
	ReasonCode                   sql.NullString
	ReasonDetail                 sql.NullString
	SourceObservedAt             string
	EvidenceAt                   string
	CurrentSince                 string
	LatestTransitionReceiveOrder sql.NullInt64
}

type EntityOwnershipInterval struct {
	EntityID             string
	AdapterID            string
	StartingReceiveOrder int64
	EndingReceiveOrder   sql.NullInt64
}

type EntityState struct {
	EntityID          string
	ObservationID     string
	ValueJson         string
	AdapterReceivedAt string
	SourceUpdatedAt   sql.NullString
	ObservedAt        string
	ReceiveOrder      int64
}

type HealthTransition struct {
	ReceiveOrder     int64
	ResourceKind     string
	AdapterID        string
	EntityID         sql.NullString
	RuntimeID        sql.NullString
	Status           string
	Source           string
	ReasonCode       sql.NullString
	ReasonDetail     sql.NullString
	SourceObservedAt sql.NullString
	ObservedAt       string
}

type ObservationReceipt struct {
	ReceiveOrder      int64
	ObservationID     string
	AdapterID         string
	RuntimeID         sql.NullString
	EntityID          string
	Disposition       string
	RejectionCode     sql.NullString
	AdapterReceivedAt string
	ObservedAt        string
	ExpiresAt         string
}
