// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package registration

import (
	"context"
)

type Querier interface {
	CountDeviceEntities(ctx context.Context, arg CountDeviceEntitiesParams) (int64, error)
	CreateBinding(ctx context.Context, arg CreateBindingParams) error
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	CreateEntity(ctx context.Context, arg CreateEntityParams) error
	CreateEntityMapping(ctx context.Context, arg CreateEntityMappingParams) error
	GetBinding(ctx context.Context, arg GetBindingParams) (GetBindingRow, error)
	GetBindingByExternalDeviceID(ctx context.Context, arg GetBindingByExternalDeviceIDParams) (GetBindingByExternalDeviceIDRow, error)
	GetEntityMapping(ctx context.Context, arg GetEntityMappingParams) (GetEntityMappingRow, error)
	GetEntityMappingByExternalID(ctx context.Context, arg GetEntityMappingByExternalIDParams) (GetEntityMappingByExternalIDRow, error)
	UpdateBindingExternalID(ctx context.Context, arg UpdateBindingExternalIDParams) error
	UpdateDeviceDescriptor(ctx context.Context, arg UpdateDeviceDescriptorParams) error
	UpdateEntityDescriptor(ctx context.Context, arg UpdateEntityDescriptorParams) error
	UpdateEntityMappingExternalID(ctx context.Context, arg UpdateEntityMappingExternalIDParams) error
}

var _ Querier = (*Queries)(nil)
