// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package registration

import (
	"context"
	"database/sql"
)

const createBinding = `-- name: CreateBinding :exec
INSERT INTO adapter_bindings (
    adapter_id, binding_key, device_id, external_device_id, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateBindingParams struct {
	AdapterID        string
	BindingKey       string
	DeviceID         string
	ExternalDeviceID sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateBinding(ctx context.Context, arg CreateBindingParams) error {
	_, err := q.db.ExecContext(ctx, createBinding,
		arg.AdapterID,
		arg.BindingKey,
		arg.DeviceID,
		arg.ExternalDeviceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, kind, name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeviceParams struct {
	ID        string
	Kind      string
	Name      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createEntity = `-- name: CreateEntity :exec
INSERT INTO entities (
    id, device_id, name, type_id, support_json, enabled, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEntityParams struct {
	ID          string
	DeviceID    string
	Name        string
	TypeID      string
	SupportJson string
	Enabled     int64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) error {
	_, err := q.db.ExecContext(ctx, createEntity,
		arg.ID,
		arg.DeviceID,
		arg.Name,
		arg.TypeID,
		arg.SupportJson,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createEntityMapping = `-- name: CreateEntityMapping :exec
INSERT INTO adapter_entity_mappings (
    adapter_id, binding_key, entity_key, entity_id, external_entity_id,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEntityMappingParams struct {
	AdapterID        string
	BindingKey       string
	EntityKey        string
	EntityID         string
	ExternalEntityID string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateEntityMapping(ctx context.Context, arg CreateEntityMappingParams) error {
	_, err := q.db.ExecContext(ctx, createEntityMapping,
		arg.AdapterID,
		arg.BindingKey,
		arg.EntityKey,
		arg.EntityID,
		arg.ExternalEntityID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getBinding = `-- name: GetBinding :one
SELECT
    b.adapter_id,
    b.binding_key,
    b.device_id,
    b.external_device_id,
    d.kind AS device_kind,
    d.name AS device_name
FROM adapter_bindings AS b
JOIN devices AS d ON d.id = b.device_id
WHERE b.adapter_id = ? AND b.binding_key = ?
`

type GetBindingParams struct {
	AdapterID  string
	BindingKey string
}

type GetBindingRow struct {
	AdapterID        string
	BindingKey       string
	DeviceID         string
	ExternalDeviceID sql.NullString
	DeviceKind       string
	DeviceName       string
}

func (q *Queries) GetBinding(ctx context.Context, arg GetBindingParams) (GetBindingRow, error) {
	row := q.db.QueryRowContext(ctx, getBinding, arg.AdapterID, arg.BindingKey)
	var i GetBindingRow
	err := row.Scan(
		&i.AdapterID,
		&i.BindingKey,
		&i.DeviceID,
		&i.ExternalDeviceID,
		&i.DeviceKind,
		&i.DeviceName,
	)
	return i, err
}

const getBindingByExternalDeviceID = `-- name: GetBindingByExternalDeviceID :one
SELECT adapter_id, binding_key, device_id, external_device_id
FROM adapter_bindings
WHERE adapter_id = ? AND external_device_id = ?
`

type GetBindingByExternalDeviceIDParams struct {
	AdapterID        string
	ExternalDeviceID sql.NullString
}

type GetBindingByExternalDeviceIDRow struct {
	AdapterID        string
	BindingKey       string
	DeviceID         string
	ExternalDeviceID sql.NullString
}

func (q *Queries) GetBindingByExternalDeviceID(ctx context.Context, arg GetBindingByExternalDeviceIDParams) (GetBindingByExternalDeviceIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBindingByExternalDeviceID, arg.AdapterID, arg.ExternalDeviceID)
	var i GetBindingByExternalDeviceIDRow
	err := row.Scan(
		&i.AdapterID,
		&i.BindingKey,
		&i.DeviceID,
		&i.ExternalDeviceID,
	)
	return i, err
}

const getEntityMapping = `-- name: GetEntityMapping :one
SELECT
    m.adapter_id,
    m.binding_key,
    m.entity_key,
    m.entity_id,
    m.external_entity_id,
    e.device_id,
    e.name AS entity_name,
    e.type_id,
    e.support_json,
    e.enabled
FROM adapter_entity_mappings AS m
JOIN entities AS e ON e.id = m.entity_id
WHERE m.adapter_id = ? AND m.binding_key = ? AND m.entity_key = ?
`

type GetEntityMappingParams struct {
	AdapterID  string
	BindingKey string
	EntityKey  string
}

type GetEntityMappingRow struct {
	AdapterID        string
	BindingKey       string
	EntityKey        string
	EntityID         string
	ExternalEntityID string
	DeviceID         string
	EntityName       string
	TypeID           string
	SupportJson      string
	Enabled          int64
}

func (q *Queries) GetEntityMapping(ctx context.Context, arg GetEntityMappingParams) (GetEntityMappingRow, error) {
	row := q.db.QueryRowContext(ctx, getEntityMapping, arg.AdapterID, arg.BindingKey, arg.EntityKey)
	var i GetEntityMappingRow
	err := row.Scan(
		&i.AdapterID,
		&i.BindingKey,
		&i.EntityKey,
		&i.EntityID,
		&i.ExternalEntityID,
		&i.DeviceID,
		&i.EntityName,
		&i.TypeID,
		&i.SupportJson,
		&i.Enabled,
	)
	return i, err
}

const getEntityMappingByExternalID = `-- name: GetEntityMappingByExternalID :one
SELECT adapter_id, binding_key, entity_key, entity_id, external_entity_id
FROM adapter_entity_mappings
WHERE adapter_id = ? AND external_entity_id = ?
`

type GetEntityMappingByExternalIDParams struct {
	AdapterID        string
	ExternalEntityID string
}

type GetEntityMappingByExternalIDRow struct {
	AdapterID        string
	BindingKey       string
	EntityKey        string
	EntityID         string
	ExternalEntityID string
}

func (q *Queries) GetEntityMappingByExternalID(ctx context.Context, arg GetEntityMappingByExternalIDParams) (GetEntityMappingByExternalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEntityMappingByExternalID, arg.AdapterID, arg.ExternalEntityID)
	var i GetEntityMappingByExternalIDRow
	err := row.Scan(
		&i.AdapterID,
		&i.BindingKey,
		&i.EntityKey,
		&i.EntityID,
		&i.ExternalEntityID,
	)
	return i, err
}

const updateBindingExternalID = `-- name: UpdateBindingExternalID :exec
UPDATE adapter_bindings
SET external_device_id = ?, updated_at = ?
WHERE adapter_id = ? AND binding_key = ?
`

type UpdateBindingExternalIDParams struct {
	ExternalDeviceID sql.NullString
	UpdatedAt        string
	AdapterID        string
	BindingKey       string
}

func (q *Queries) UpdateBindingExternalID(ctx context.Context, arg UpdateBindingExternalIDParams) error {
	_, err := q.db.ExecContext(ctx, updateBindingExternalID,
		arg.ExternalDeviceID,
		arg.UpdatedAt,
		arg.AdapterID,
		arg.BindingKey,
	)
	return err
}

const updateDeviceDescriptor = `-- name: UpdateDeviceDescriptor :exec
UPDATE devices
SET kind = ?, name = ?, updated_at = ?
WHERE id = ?
`

type UpdateDeviceDescriptorParams struct {
	Kind      string
	Name      string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateDeviceDescriptor(ctx context.Context, arg UpdateDeviceDescriptorParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceDescriptor,
		arg.Kind,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateEntityDescriptor = `-- name: UpdateEntityDescriptor :exec
UPDATE entities
SET name = ?, support_json = ?, updated_at = ?
WHERE id = ?
`

type UpdateEntityDescriptorParams struct {
	Name        string
	SupportJson string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateEntityDescriptor(ctx context.Context, arg UpdateEntityDescriptorParams) error {
	_, err := q.db.ExecContext(ctx, updateEntityDescriptor,
		arg.Name,
		arg.SupportJson,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateEntityMappingExternalID = `-- name: UpdateEntityMappingExternalID :exec
UPDATE adapter_entity_mappings
SET external_entity_id = ?, updated_at = ?
WHERE adapter_id = ? AND binding_key = ? AND entity_key = ?
`

type UpdateEntityMappingExternalIDParams struct {
	ExternalEntityID string
	UpdatedAt        string
	AdapterID        string
	BindingKey       string
	EntityKey        string
}

func (q *Queries) UpdateEntityMappingExternalID(ctx context.Context, arg UpdateEntityMappingExternalIDParams) error {
	_, err := q.db.ExecContext(ctx, updateEntityMappingExternalID,
		arg.ExternalEntityID,
		arg.UpdatedAt,
		arg.AdapterID,
		arg.BindingKey,
		arg.EntityKey,
	)
	return err
}
