// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package state

import (
	"context"
)

type Querier interface {
	GetDevice(ctx context.Context, arg GetDeviceParams) ([]GetDeviceRow, error)
	GetEntity(ctx context.Context, arg GetEntityParams) (GetEntityRow, error)
	GetEntityState(ctx context.Context, arg GetEntityStateParams) (EntityState, error)
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error)
	ListEntities(ctx context.Context, arg ListEntitiesParams) ([]ListEntitiesRow, error)
	ListEntitiesByDevice(ctx context.Context, arg ListEntitiesByDeviceParams) ([]ListEntitiesByDeviceRow, error)
	UpsertEntityState(ctx context.Context, arg UpsertEntityStateParams) error
}

var _ Querier = (*Queries)(nil)
