// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state.sql

package state

import (
	"context"
	"database/sql"
)

const getEntityState = `-- name: GetEntityState :one
SELECT entity_id, observation_id, value_json, adapter_received_at,
       source_updated_at, observed_at, receive_order
FROM entity_states
WHERE entity_id = ?
`

type GetEntityStateParams struct {
	EntityID string
}

func (q *Queries) GetEntityState(ctx context.Context, arg GetEntityStateParams) (EntityState, error) {
	row := q.db.QueryRowContext(ctx, getEntityState, arg.EntityID)
	var i EntityState
	err := row.Scan(
		&i.EntityID,
		&i.ObservationID,
		&i.ValueJson,
		&i.AdapterReceivedAt,
		&i.SourceUpdatedAt,
		&i.ObservedAt,
		&i.ReceiveOrder,
	)
	return i, err
}

const getEntityView = `-- name: GetEntityView :one
SELECT
    e.id,
    e.device_id,
    m.adapter_id,
    e.name,
    e.type_id,
    e.constraints_json,
    CAST((
        SELECT json_group_array(operation)
        FROM entity_operations
        WHERE entity_id = e.id
    ) AS TEXT) AS operations_json,
    s.observation_id,
    s.value_json,
    s.adapter_received_at,
    s.source_updated_at,
    s.observed_at,
    s.receive_order
FROM entities AS e
JOIN adapter_entity_mappings AS m ON m.entity_id = e.id
LEFT JOIN entity_states AS s ON s.entity_id = e.id
WHERE e.id = ?
`

type GetEntityViewParams struct {
	ID string
}

type GetEntityViewRow struct {
	ID                string
	DeviceID          string
	AdapterID         string
	Name              string
	TypeID            string
	ConstraintsJson   string
	OperationsJson    string
	ObservationID     sql.NullString
	ValueJson         sql.NullString
	AdapterReceivedAt sql.NullString
	SourceUpdatedAt   sql.NullString
	ObservedAt        sql.NullString
	ReceiveOrder      sql.NullInt64
}

func (q *Queries) GetEntityView(ctx context.Context, arg GetEntityViewParams) (GetEntityViewRow, error) {
	row := q.db.QueryRowContext(ctx, getEntityView, arg.ID)
	var i GetEntityViewRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.AdapterID,
		&i.Name,
		&i.TypeID,
		&i.ConstraintsJson,
		&i.OperationsJson,
		&i.ObservationID,
		&i.ValueJson,
		&i.AdapterReceivedAt,
		&i.SourceUpdatedAt,
		&i.ObservedAt,
		&i.ReceiveOrder,
	)
	return i, err
}

const upsertEntityState = `-- name: UpsertEntityState :exec
INSERT INTO entity_states (
    entity_id, observation_id, value_json, adapter_received_at,
    source_updated_at, observed_at, receive_order
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (entity_id) DO UPDATE SET
    observation_id = excluded.observation_id,
    value_json = excluded.value_json,
    adapter_received_at = excluded.adapter_received_at,
    source_updated_at = excluded.source_updated_at,
    observed_at = excluded.observed_at,
    receive_order = excluded.receive_order
`

type UpsertEntityStateParams struct {
	EntityID          string
	ObservationID     string
	ValueJson         string
	AdapterReceivedAt string
	SourceUpdatedAt   sql.NullString
	ObservedAt        string
	ReceiveOrder      int64
}

func (q *Queries) UpsertEntityState(ctx context.Context, arg UpsertEntityStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntityState,
		arg.EntityID,
		arg.ObservationID,
		arg.ValueJson,
		arg.AdapterReceivedAt,
		arg.SourceUpdatedAt,
		arg.ObservedAt,
		arg.ReceiveOrder,
	)
	return err
}
