// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state.sql

package state

import (
	"context"
	"database/sql"
)

const getDevice = `-- name: GetDevice :one
SELECT id, kind, name
FROM devices
WHERE id = ?
`

type GetDeviceParams struct {
	ID string
}

type GetDeviceRow struct {
	ID   string
	Kind string
	Name string
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (GetDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getDevice, arg.ID)
	var i GetDeviceRow
	err := row.Scan(&i.ID, &i.Kind, &i.Name)
	return i, err
}

const getEntity = `-- name: GetEntity :one
SELECT
    e.id,
    e.device_id,
    m.adapter_id,
    e.name,
    e.type_id,
    e.support_json,
    e.enabled,
    e.created_at AS entity_created_at,
    s.observation_id,
    s.value_json,
    s.adapter_received_at,
    s.source_updated_at,
    s.observed_at,
    s.receive_order,
    ai.active_runtime_id AS availability_runtime_id,
    ai.health_status AS adapter_health_status,
    ai.health_reason_code AS adapter_health_reason_code,
    ai.health_reason_detail AS adapter_health_reason_detail,
    ai.health_since AS adapter_health_since,
    ai.health_evidence_at AS adapter_health_evidence_at,
    ai.availability_epoch AS adapter_availability_epoch,
    current.status AS reported_availability_status,
    current.reason_code AS reported_availability_reason_code,
    current.reason_detail AS reported_availability_reason_detail,
    current.source_observed_at AS reported_availability_source_observed_at,
    current.evidence_at AS reported_availability_evidence_at,
    current.current_since AS reported_availability_since
FROM entities AS e
JOIN adapter_entity_mappings AS m ON m.entity_id = e.id
LEFT JOIN entity_states AS s ON s.entity_id = e.id
LEFT JOIN adapter_instances AS ai ON ai.adapter_id = m.adapter_id AND ai.archived_at IS NULL
LEFT JOIN entity_availability_current AS current
    ON current.entity_id = e.id
    AND current.adapter_id = m.adapter_id
    AND current.availability_epoch = ai.availability_epoch
WHERE e.id = ?
`

type GetEntityParams struct {
	ID string
}

type GetEntityRow struct {
	ID                                   string
	DeviceID                             string
	AdapterID                            string
	Name                                 string
	TypeID                               string
	SupportJson                          string
	Enabled                              int64
	EntityCreatedAt                      string
	ObservationID                        sql.NullString
	ValueJson                            sql.NullString
	AdapterReceivedAt                    sql.NullString
	SourceUpdatedAt                      sql.NullString
	ObservedAt                           sql.NullString
	ReceiveOrder                         sql.NullInt64
	AvailabilityRuntimeID                sql.NullString
	AdapterHealthStatus                  sql.NullString
	AdapterHealthReasonCode              sql.NullString
	AdapterHealthReasonDetail            sql.NullString
	AdapterHealthSince                   sql.NullString
	AdapterHealthEvidenceAt              sql.NullString
	AdapterAvailabilityEpoch             sql.NullInt64
	ReportedAvailabilityStatus           sql.NullString
	ReportedAvailabilityReasonCode       sql.NullString
	ReportedAvailabilityReasonDetail     sql.NullString
	ReportedAvailabilitySourceObservedAt sql.NullString
	ReportedAvailabilityEvidenceAt       sql.NullString
	ReportedAvailabilitySince            sql.NullString
}

func (q *Queries) GetEntity(ctx context.Context, arg GetEntityParams) (GetEntityRow, error) {
	row := q.db.QueryRowContext(ctx, getEntity, arg.ID)
	var i GetEntityRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.AdapterID,
		&i.Name,
		&i.TypeID,
		&i.SupportJson,
		&i.Enabled,
		&i.EntityCreatedAt,
		&i.ObservationID,
		&i.ValueJson,
		&i.AdapterReceivedAt,
		&i.SourceUpdatedAt,
		&i.ObservedAt,
		&i.ReceiveOrder,
		&i.AvailabilityRuntimeID,
		&i.AdapterHealthStatus,
		&i.AdapterHealthReasonCode,
		&i.AdapterHealthReasonDetail,
		&i.AdapterHealthSince,
		&i.AdapterHealthEvidenceAt,
		&i.AdapterAvailabilityEpoch,
		&i.ReportedAvailabilityStatus,
		&i.ReportedAvailabilityReasonCode,
		&i.ReportedAvailabilityReasonDetail,
		&i.ReportedAvailabilitySourceObservedAt,
		&i.ReportedAvailabilityEvidenceAt,
		&i.ReportedAvailabilitySince,
	)
	return i, err
}

const getEntityState = `-- name: GetEntityState :one
SELECT entity_id, observation_id, value_json, adapter_received_at,
       source_updated_at, observed_at, receive_order
FROM entity_states
WHERE entity_id = ?
`

type GetEntityStateParams struct {
	EntityID string
}

func (q *Queries) GetEntityState(ctx context.Context, arg GetEntityStateParams) (EntityState, error) {
	row := q.db.QueryRowContext(ctx, getEntityState, arg.EntityID)
	var i EntityState
	err := row.Scan(
		&i.EntityID,
		&i.ObservationID,
		&i.ValueJson,
		&i.AdapterReceivedAt,
		&i.SourceUpdatedAt,
		&i.ObservedAt,
		&i.ReceiveOrder,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, kind, name
FROM devices
WHERE id > ?
ORDER BY id ASC
LIMIT ?
`

type ListDevicesParams struct {
	ID    string
	Limit int64
}

type ListDevicesRow struct {
	ID   string
	Kind string
	Name string
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]ListDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesRow
	for rows.Next() {
		var i ListDevicesRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntities = `-- name: ListEntities :many
SELECT
    e.id,
    e.device_id,
    m.adapter_id,
    e.name,
    e.type_id,
    e.support_json,
    e.enabled,
    e.created_at AS entity_created_at,
    s.observation_id,
    s.value_json,
    s.adapter_received_at,
    s.source_updated_at,
    s.observed_at,
    s.receive_order,
    ai.active_runtime_id AS availability_runtime_id,
    ai.health_status AS adapter_health_status,
    ai.health_reason_code AS adapter_health_reason_code,
    ai.health_reason_detail AS adapter_health_reason_detail,
    ai.health_since AS adapter_health_since,
    ai.health_evidence_at AS adapter_health_evidence_at,
    ai.availability_epoch AS adapter_availability_epoch,
    current.status AS reported_availability_status,
    current.reason_code AS reported_availability_reason_code,
    current.reason_detail AS reported_availability_reason_detail,
    current.source_observed_at AS reported_availability_source_observed_at,
    current.evidence_at AS reported_availability_evidence_at,
    current.current_since AS reported_availability_since
FROM entities AS e
JOIN adapter_entity_mappings AS m ON m.entity_id = e.id
LEFT JOIN entity_states AS s ON s.entity_id = e.id
LEFT JOIN adapter_instances AS ai ON ai.adapter_id = m.adapter_id AND ai.archived_at IS NULL
LEFT JOIN entity_availability_current AS current
    ON current.entity_id = e.id
    AND current.adapter_id = m.adapter_id
    AND current.availability_epoch = ai.availability_epoch
WHERE e.id > ?
ORDER BY e.id ASC
LIMIT ?
`

type ListEntitiesParams struct {
	ID    string
	Limit int64
}

type ListEntitiesRow struct {
	ID                                   string
	DeviceID                             string
	AdapterID                            string
	Name                                 string
	TypeID                               string
	SupportJson                          string
	Enabled                              int64
	EntityCreatedAt                      string
	ObservationID                        sql.NullString
	ValueJson                            sql.NullString
	AdapterReceivedAt                    sql.NullString
	SourceUpdatedAt                      sql.NullString
	ObservedAt                           sql.NullString
	ReceiveOrder                         sql.NullInt64
	AvailabilityRuntimeID                sql.NullString
	AdapterHealthStatus                  sql.NullString
	AdapterHealthReasonCode              sql.NullString
	AdapterHealthReasonDetail            sql.NullString
	AdapterHealthSince                   sql.NullString
	AdapterHealthEvidenceAt              sql.NullString
	AdapterAvailabilityEpoch             sql.NullInt64
	ReportedAvailabilityStatus           sql.NullString
	ReportedAvailabilityReasonCode       sql.NullString
	ReportedAvailabilityReasonDetail     sql.NullString
	ReportedAvailabilitySourceObservedAt sql.NullString
	ReportedAvailabilityEvidenceAt       sql.NullString
	ReportedAvailabilitySince            sql.NullString
}

func (q *Queries) ListEntities(ctx context.Context, arg ListEntitiesParams) ([]ListEntitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntities, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntitiesRow
	for rows.Next() {
		var i ListEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.AdapterID,
			&i.Name,
			&i.TypeID,
			&i.SupportJson,
			&i.Enabled,
			&i.EntityCreatedAt,
			&i.ObservationID,
			&i.ValueJson,
			&i.AdapterReceivedAt,
			&i.SourceUpdatedAt,
			&i.ObservedAt,
			&i.ReceiveOrder,
			&i.AvailabilityRuntimeID,
			&i.AdapterHealthStatus,
			&i.AdapterHealthReasonCode,
			&i.AdapterHealthReasonDetail,
			&i.AdapterHealthSince,
			&i.AdapterHealthEvidenceAt,
			&i.AdapterAvailabilityEpoch,
			&i.ReportedAvailabilityStatus,
			&i.ReportedAvailabilityReasonCode,
			&i.ReportedAvailabilityReasonDetail,
			&i.ReportedAvailabilitySourceObservedAt,
			&i.ReportedAvailabilityEvidenceAt,
			&i.ReportedAvailabilitySince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByDevice = `-- name: ListEntitiesByDevice :many
SELECT
    e.id,
    e.device_id,
    m.adapter_id,
    e.name,
    e.type_id,
    e.support_json,
    e.enabled,
    e.created_at AS entity_created_at,
    s.observation_id,
    s.value_json,
    s.adapter_received_at,
    s.source_updated_at,
    s.observed_at,
    s.receive_order,
    ai.active_runtime_id AS availability_runtime_id,
    ai.health_status AS adapter_health_status,
    ai.health_reason_code AS adapter_health_reason_code,
    ai.health_reason_detail AS adapter_health_reason_detail,
    ai.health_since AS adapter_health_since,
    ai.health_evidence_at AS adapter_health_evidence_at,
    ai.availability_epoch AS adapter_availability_epoch,
    current.status AS reported_availability_status,
    current.reason_code AS reported_availability_reason_code,
    current.reason_detail AS reported_availability_reason_detail,
    current.source_observed_at AS reported_availability_source_observed_at,
    current.evidence_at AS reported_availability_evidence_at,
    current.current_since AS reported_availability_since
FROM entities AS e
JOIN adapter_entity_mappings AS m ON m.entity_id = e.id
LEFT JOIN entity_states AS s ON s.entity_id = e.id
LEFT JOIN adapter_instances AS ai ON ai.adapter_id = m.adapter_id AND ai.archived_at IS NULL
LEFT JOIN entity_availability_current AS current
    ON current.entity_id = e.id
    AND current.adapter_id = m.adapter_id
    AND current.availability_epoch = ai.availability_epoch
WHERE e.device_id = ? AND e.id > ?
ORDER BY e.id ASC
LIMIT ?
`

type ListEntitiesByDeviceParams struct {
	DeviceID string
	ID       string
	Limit    int64
}

type ListEntitiesByDeviceRow struct {
	ID                                   string
	DeviceID                             string
	AdapterID                            string
	Name                                 string
	TypeID                               string
	SupportJson                          string
	Enabled                              int64
	EntityCreatedAt                      string
	ObservationID                        sql.NullString
	ValueJson                            sql.NullString
	AdapterReceivedAt                    sql.NullString
	SourceUpdatedAt                      sql.NullString
	ObservedAt                           sql.NullString
	ReceiveOrder                         sql.NullInt64
	AvailabilityRuntimeID                sql.NullString
	AdapterHealthStatus                  sql.NullString
	AdapterHealthReasonCode              sql.NullString
	AdapterHealthReasonDetail            sql.NullString
	AdapterHealthSince                   sql.NullString
	AdapterHealthEvidenceAt              sql.NullString
	AdapterAvailabilityEpoch             sql.NullInt64
	ReportedAvailabilityStatus           sql.NullString
	ReportedAvailabilityReasonCode       sql.NullString
	ReportedAvailabilityReasonDetail     sql.NullString
	ReportedAvailabilitySourceObservedAt sql.NullString
	ReportedAvailabilityEvidenceAt       sql.NullString
	ReportedAvailabilitySince            sql.NullString
}

func (q *Queries) ListEntitiesByDevice(ctx context.Context, arg ListEntitiesByDeviceParams) ([]ListEntitiesByDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntitiesByDevice, arg.DeviceID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntitiesByDeviceRow
	for rows.Next() {
		var i ListEntitiesByDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.AdapterID,
			&i.Name,
			&i.TypeID,
			&i.SupportJson,
			&i.Enabled,
			&i.EntityCreatedAt,
			&i.ObservationID,
			&i.ValueJson,
			&i.AdapterReceivedAt,
			&i.SourceUpdatedAt,
			&i.ObservedAt,
			&i.ReceiveOrder,
			&i.AvailabilityRuntimeID,
			&i.AdapterHealthStatus,
			&i.AdapterHealthReasonCode,
			&i.AdapterHealthReasonDetail,
			&i.AdapterHealthSince,
			&i.AdapterHealthEvidenceAt,
			&i.AdapterAvailabilityEpoch,
			&i.ReportedAvailabilityStatus,
			&i.ReportedAvailabilityReasonCode,
			&i.ReportedAvailabilityReasonDetail,
			&i.ReportedAvailabilitySourceObservedAt,
			&i.ReportedAvailabilityEvidenceAt,
			&i.ReportedAvailabilitySince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntityEnablement = `-- name: UpdateEntityEnablement :execrows
UPDATE entities
SET enabled = ?1, updated_at = ?2
WHERE id = ?3 AND enabled <> ?1
`

type UpdateEntityEnablementParams struct {
	Enabled   int64
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateEntityEnablement(ctx context.Context, arg UpdateEntityEnablementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEntityEnablement, arg.Enabled, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEntityState = `-- name: UpsertEntityState :exec
INSERT INTO entity_states (
    entity_id, observation_id, value_json, adapter_received_at,
    source_updated_at, observed_at, receive_order
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (entity_id) DO UPDATE SET
    observation_id = excluded.observation_id,
    value_json = excluded.value_json,
    adapter_received_at = excluded.adapter_received_at,
    source_updated_at = excluded.source_updated_at,
    observed_at = excluded.observed_at,
    receive_order = excluded.receive_order
`

type UpsertEntityStateParams struct {
	EntityID          string
	ObservationID     string
	ValueJson         string
	AdapterReceivedAt string
	SourceUpdatedAt   sql.NullString
	ObservedAt        string
	ReceiveOrder      int64
}

func (q *Queries) UpsertEntityState(ctx context.Context, arg UpsertEntityStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntityState,
		arg.EntityID,
		arg.ObservationID,
		arg.ValueJson,
		arg.AdapterReceivedAt,
		arg.SourceUpdatedAt,
		arg.ObservedAt,
		arg.ReceiveOrder,
	)
	return err
}
