// Code generated by entitytypegen; DO NOT EDIT.

package colormodev1

import (
	"encoding/json"
	"testing"
)

func TestGeneratedConformance(t *testing.T) {
	codecs, err := Compile()
	if err != nil {
		t.Fatal(err)
	}
	t.Run("reported-modes", func(t *testing.T) {
		support, _, err := codecs.Support.Decode(json.RawMessage("{\"state\": {}, \"operations\": {}}"))
		if err != nil {
			t.Fatalf("support: %v", err)
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("\"xy\""))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != true {
				t.Errorf("state example 1: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("\"hs\""))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != true {
				t.Errorf("state example 2: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("\"color_temp\""))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != true {
				t.Errorf("state example 3: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("\"rgb\""))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != false {
				t.Errorf("state example 4: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
		{
			value, _, decodeErr := codecs.State.Decode(json.RawMessage("123"))
			valid := decodeErr == nil
			if decodeErr == nil {
				valid = ValidateState(support, value) == nil
			}
			if valid != false {
				t.Errorf("state example 5: valid = %v, decode error = %v", valid, decodeErr)
			}
		}
	})
}
