// Code generated by entitytypegen; DO NOT EDIT.

// Package colormodev1 provides schemas, behavior, and Go bindings for hearth.colormode/v1.
package colormodev1

const TypeID = "hearth.colormode/v1"

type State string

type StateSupport struct {
}

type OperationSupport struct {
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}
