// Code generated by entitytypegen; DO NOT EDIT.

// Package pressurev1 provides schemas, behavior, and Go bindings for hearth.pressure/v1.
package pressurev1

const TypeID = "hearth.pressure/v1"

type State float64

type StateSupport struct {
}

type OperationSupport struct {
}

type Support struct {
	State      StateSupport     `json:"state"`
	Operations OperationSupport `json:"operations"`
}
