name: mise

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - name: Run checks
        run: |
          mise run hearth:validate
          git diff --exit-code
          test -z "$(git ls-files --others --exclude-standard)"
